// Code generated by go generate; DO NOT EDIT.

//go:build !ffigo_cgo

package ffi

import "github.com/ebitengine/purego"

func registerFunctions() error {
	// VideoEncoder
	registerLibFunc(&shimVideoEncoderCreate, libHandle, "shim_video_encoder_create")
	registerLibFunc(&shimVideoEncoderEncode, libHandle, "shim_video_encoder_encode")
	registerLibFunc(&shimVideoEncoderSetBitrate, libHandle, "shim_video_encoder_set_bitrate")
	registerLibFunc(&shimVideoEncoderSetFramerate, libHandle, "shim_video_encoder_set_framerate")
	registerLibFunc(&shimVideoEncoderRequestKeyframe, libHandle, "shim_video_encoder_request_keyframe")
	registerLibFunc(&shimVideoEncoderDestroy, libHandle, "shim_video_encoder_destroy")

	// VideoDecoder
	registerLibFunc(&shimVideoDecoderCreate, libHandle, "shim_video_decoder_create")
	registerLibFunc(&shimVideoDecoderDecode, libHandle, "shim_video_decoder_decode")
	registerLibFunc(&shimVideoDecoderDestroy, libHandle, "shim_video_decoder_destroy")

	// AudioEncoder
	registerLibFunc(&shimAudioEncoderCreate, libHandle, "shim_audio_encoder_create")
	registerLibFunc(&shimAudioEncoderEncode, libHandle, "shim_audio_encoder_encode")
	registerLibFunc(&shimAudioEncoderSetBitrate, libHandle, "shim_audio_encoder_set_bitrate")
	registerLibFunc(&shimAudioEncoderDestroy, libHandle, "shim_audio_encoder_destroy")

	// AudioDecoder
	registerLibFunc(&shimAudioDecoderCreate, libHandle, "shim_audio_decoder_create")
	registerLibFunc(&shimAudioDecoderDecode, libHandle, "shim_audio_decoder_decode")
	registerLibFunc(&shimAudioDecoderDestroy, libHandle, "shim_audio_decoder_destroy")

	// Packetizer
	registerLibFunc(&shimPacketizerCreate, libHandle, "shim_packetizer_create")
	registerLibFunc(&shimPacketizerPacketize, libHandle, "shim_packetizer_packetize")
	registerLibFunc(&shimPacketizerSeqNum, libHandle, "shim_packetizer_sequence_number")
	registerLibFunc(&shimPacketizerDestroy, libHandle, "shim_packetizer_destroy")

	// Depacketizer
	registerLibFunc(&shimDepacketizerCreate, libHandle, "shim_depacketizer_create")
	registerLibFunc(&shimDepacketizerPush, libHandle, "shim_depacketizer_push")
	registerLibFunc(&shimDepacketizerPop, libHandle, "shim_depacketizer_pop")
	registerLibFunc(&shimDepacketizerDestroy, libHandle, "shim_depacketizer_destroy")

	// Memory
	registerLibFunc(&shimFreeBuffer, libHandle, "shim_free_buffer")
	registerLibFunc(&shimFreePackets, libHandle, "shim_free_packets")

	// Version
	registerLibFunc(&shimLibwebrtcVersion, libHandle, "shim_libwebrtc_version")
	registerLibFunc(&shimVersion, libHandle, "shim_version")

	// PeerConnection
	registerLibFunc(&shimPeerConnectionCreate, libHandle, "shim_peer_connection_create")
	registerLibFunc(&shimPeerConnectionDestroy, libHandle, "shim_peer_connection_destroy")
	registerLibFunc(&shimPeerConnectionSetOnICECandidate, libHandle, "shim_peer_connection_set_on_ice_candidate")
	registerLibFunc(&shimPeerConnectionSetOnConnectionStateChange, libHandle, "shim_peer_connection_set_on_connection_state_change")
	registerLibFunc(&shimPeerConnectionSetOnTrack, libHandle, "shim_peer_connection_set_on_track")
	registerLibFunc(&shimPeerConnectionSetOnDataChannel, libHandle, "shim_peer_connection_set_on_data_channel")
	registerLibFunc(&shimPeerConnectionCreateOffer, libHandle, "shim_peer_connection_create_offer")
	registerLibFunc(&shimPeerConnectionCreateAnswer, libHandle, "shim_peer_connection_create_answer")
	registerLibFunc(&shimPeerConnectionSetLocalDescription, libHandle, "shim_peer_connection_set_local_description")
	registerLibFunc(&shimPeerConnectionSetRemoteDescription, libHandle, "shim_peer_connection_set_remote_description")
	registerLibFunc(&shimPeerConnectionAddICECandidate, libHandle, "shim_peer_connection_add_ice_candidate")
	registerLibFunc(&shimPeerConnectionSignalingState, libHandle, "shim_peer_connection_signaling_state")
	registerLibFunc(&shimPeerConnectionICEConnectionState, libHandle, "shim_peer_connection_ice_connection_state")
	registerLibFunc(&shimPeerConnectionICEGatheringState, libHandle, "shim_peer_connection_ice_gathering_state")
	registerLibFunc(&shimPeerConnectionConnectionState, libHandle, "shim_peer_connection_connection_state")
	registerLibFunc(&shimPeerConnectionAddTrack, libHandle, "shim_peer_connection_add_track")
	registerLibFunc(&shimPeerConnectionRemoveTrack, libHandle, "shim_peer_connection_remove_track")
	registerLibFunc(&shimPeerConnectionCreateDataChannel, libHandle, "shim_peer_connection_create_data_channel")
	registerLibFunc(&shimPeerConnectionClose, libHandle, "shim_peer_connection_close")

	// PeerConnectionExtended
	registerLibFunc(&shimPeerConnectionAddTransceiver, libHandle, "shim_peer_connection_add_transceiver")
	registerLibFunc(&shimPeerConnectionGetSenders, libHandle, "shim_peer_connection_get_senders")
	registerLibFunc(&shimPeerConnectionGetReceivers, libHandle, "shim_peer_connection_get_receivers")
	registerLibFunc(&shimPeerConnectionGetTransceivers, libHandle, "shim_peer_connection_get_transceivers")
	registerLibFunc(&shimPeerConnectionRestartICE, libHandle, "shim_peer_connection_restart_ice")
	registerLibFunc(&shimPeerConnectionGetStats, libHandle, "shim_peer_connection_get_stats")
	registerLibFunc(&shimPeerConnectionSetOnSignalingStateChange, libHandle, "shim_peer_connection_set_on_signaling_state_change")
	registerLibFunc(&shimPeerConnectionSetOnICEConnectionStateChange, libHandle, "shim_peer_connection_set_on_ice_connection_state_change")
	registerLibFunc(&shimPeerConnectionSetOnICEGatheringStateChange, libHandle, "shim_peer_connection_set_on_ice_gathering_state_change")
	registerLibFunc(&shimPeerConnectionSetOnNegotiationNeeded, libHandle, "shim_peer_connection_set_on_negotiation_needed")

	// RTPSender
	registerLibFunc(&shimRTPSenderSetBitrate, libHandle, "shim_rtp_sender_set_bitrate")
	registerLibFunc(&shimRTPSenderReplaceTrack, libHandle, "shim_rtp_sender_replace_track")
	registerLibFunc(&shimRTPSenderDestroy, libHandle, "shim_rtp_sender_destroy")
	registerLibFunc(&shimRTPSenderGetParameters, libHandle, "shim_rtp_sender_get_parameters")
	registerLibFunc(&shimRTPSenderSetParameters, libHandle, "shim_rtp_sender_set_parameters")
	registerLibFunc(&shimRTPSenderGetTrack, libHandle, "shim_rtp_sender_get_track")
	registerLibFunc(&shimRTPSenderGetStats, libHandle, "shim_rtp_sender_get_stats")
	registerLibFunc(&shimRTPSenderSetOnRTCPFeedback, libHandle, "shim_rtp_sender_set_on_rtcp_feedback")
	registerLibFunc(&shimRTPSenderSetLayerActive, libHandle, "shim_rtp_sender_set_layer_active")
	registerLibFunc(&shimRTPSenderSetLayerBitrate, libHandle, "shim_rtp_sender_set_layer_bitrate")
	registerLibFunc(&shimRTPSenderGetActiveLayers, libHandle, "shim_rtp_sender_get_active_layers")

	// RTPReceiver
	registerLibFunc(&shimRTPReceiverGetTrack, libHandle, "shim_rtp_receiver_get_track")
	registerLibFunc(&shimRTPReceiverGetStats, libHandle, "shim_rtp_receiver_get_stats")
	registerLibFunc(&shimRTPReceiverRequestKeyframe, libHandle, "shim_rtp_receiver_request_keyframe")
	registerLibFunc(&shimRTPReceiverSetJitterBufferMinDelay, libHandle, "shim_rtp_receiver_set_jitter_buffer_min_delay")

	// RTPTransceiver
	registerLibFunc(&shimTransceiverGetDirection, libHandle, "shim_transceiver_get_direction")
	registerLibFunc(&shimTransceiverSetDirection, libHandle, "shim_transceiver_set_direction")
	registerLibFunc(&shimTransceiverGetCurrentDirection, libHandle, "shim_transceiver_get_current_direction")
	registerLibFunc(&shimTransceiverStop, libHandle, "shim_transceiver_stop")
	registerLibFunc(&shimTransceiverMid, libHandle, "shim_transceiver_mid")
	registerLibFunc(&shimTransceiverGetSender, libHandle, "shim_transceiver_get_sender")
	registerLibFunc(&shimTransceiverGetReceiver, libHandle, "shim_transceiver_get_receiver")
	registerLibFunc(&shimTransceiverSetCodecPreferences, libHandle, "shim_transceiver_set_codec_preferences")
	registerLibFunc(&shimTransceiverGetCodecPreferences, libHandle, "shim_transceiver_get_codec_preferences")

	// DataChannel
	registerLibFunc(&shimDataChannelSetOnMessage, libHandle, "shim_data_channel_set_on_message")
	registerLibFunc(&shimDataChannelSetOnOpen, libHandle, "shim_data_channel_set_on_open")
	registerLibFunc(&shimDataChannelSetOnClose, libHandle, "shim_data_channel_set_on_close")
	registerLibFunc(&shimDataChannelSend, libHandle, "shim_data_channel_send")
	registerLibFunc(&shimDataChannelLabel, libHandle, "shim_data_channel_label")
	registerLibFunc(&shimDataChannelReadyState, libHandle, "shim_data_channel_ready_state")
	registerLibFunc(&shimDataChannelClose, libHandle, "shim_data_channel_close")
	registerLibFunc(&shimDataChannelDestroy, libHandle, "shim_data_channel_destroy")

	// VideoTrackSource
	registerLibFunc(&shimVideoTrackSourceCreate, libHandle, "shim_video_track_source_create")
	registerLibFunc(&shimVideoTrackSourcePushFrame, libHandle, "shim_video_track_source_push_frame")
	registerLibFunc(&shimPeerConnectionAddVideoTrackFromSource, libHandle, "shim_peer_connection_add_video_track_from_source")
	registerLibFunc(&shimVideoTrackSourceDestroy, libHandle, "shim_video_track_source_destroy")

	// AudioTrackSource
	registerLibFunc(&shimAudioTrackSourceCreate, libHandle, "shim_audio_track_source_create")
	registerLibFunc(&shimAudioTrackSourcePushFrame, libHandle, "shim_audio_track_source_push_frame")
	registerLibFunc(&shimPeerConnectionAddAudioTrackFromSource, libHandle, "shim_peer_connection_add_audio_track_from_source")
	registerLibFunc(&shimAudioTrackSourceDestroy, libHandle, "shim_audio_track_source_destroy")

	// RemoteTrack
	registerLibFunc(&shimTrackSetVideoSink, libHandle, "shim_track_set_video_sink")
	registerLibFunc(&shimTrackSetAudioSink, libHandle, "shim_track_set_audio_sink")
	registerLibFunc(&shimTrackRemoveVideoSink, libHandle, "shim_track_remove_video_sink")
	registerLibFunc(&shimTrackRemoveAudioSink, libHandle, "shim_track_remove_audio_sink")
	registerLibFunc(&shimTrackKind, libHandle, "shim_track_kind")
	registerLibFunc(&shimTrackID, libHandle, "shim_track_id")

	// ScalabilityMode
	registerLibFunc(&shimRTPSenderSetScalabilityMode, libHandle, "shim_rtp_sender_set_scalability_mode")
	registerLibFunc(&shimRTPSenderGetScalabilityMode, libHandle, "shim_rtp_sender_get_scalability_mode")

	// CodecCapabilities
	registerLibFunc(&shimGetSupportedVideoCodecs, libHandle, "shim_get_supported_video_codecs")
	registerLibFunc(&shimGetSupportedAudioCodecs, libHandle, "shim_get_supported_audio_codecs")
	registerLibFunc(&shimIsCodecSupported, libHandle, "shim_is_codec_supported")

	// RTPSenderCodec
	registerLibFunc(&shimRTPSenderGetNegotiatedCodecs, libHandle, "shim_rtp_sender_get_negotiated_codecs")
	registerLibFunc(&shimRTPSenderSetPreferredCodec, libHandle, "shim_rtp_sender_set_preferred_codec")

	// BandwidthEstimation
	registerLibFunc(&shimPeerConnectionSetOnBandwidthEstimate, libHandle, "shim_peer_connection_set_on_bandwidth_estimate")
	registerLibFunc(&shimPeerConnectionGetBandwidthEstimate, libHandle, "shim_peer_connection_get_bandwidth_estimate")

	// DeviceCapture
	registerLibFunc(&shimEnumerateDevices, libHandle, "shim_enumerate_devices")
	registerLibFunc(&shimVideoCaptureCreate, libHandle, "shim_video_capture_create")
	registerLibFunc(&shimVideoCaptureStart, libHandle, "shim_video_capture_start")
	registerLibFunc(&shimVideoCaptureStop, libHandle, "shim_video_capture_stop")
	registerLibFunc(&shimVideoCaptureDestroy, libHandle, "shim_video_capture_destroy")
	registerLibFunc(&shimAudioCaptureCreate, libHandle, "shim_audio_capture_create")
	registerLibFunc(&shimAudioCaptureStart, libHandle, "shim_audio_capture_start")
	registerLibFunc(&shimAudioCaptureStop, libHandle, "shim_audio_capture_stop")
	registerLibFunc(&shimAudioCaptureDestroy, libHandle, "shim_audio_capture_destroy")

	// ScreenCapture
	registerLibFunc(&shimEnumerateScreens, libHandle, "shim_enumerate_screens")
	registerLibFunc(&shimScreenCaptureCreate, libHandle, "shim_screen_capture_create")
	registerLibFunc(&shimScreenCaptureStart, libHandle, "shim_screen_capture_start")
	registerLibFunc(&shimScreenCaptureStop, libHandle, "shim_screen_capture_stop")
	registerLibFunc(&shimScreenCaptureDestroy, libHandle, "shim_screen_capture_destroy")

	// Permissions
	registerLibFunc(&shimCheckCameraPermission, libHandle, "shim_check_camera_permission")
	registerLibFunc(&shimCheckMicrophonePermission, libHandle, "shim_check_microphone_permission")
	registerLibFunc(&shimRequestCameraPermission, libHandle, "shim_request_camera_permission")
	registerLibFunc(&shimRequestMicrophonePermission, libHandle, "shim_request_microphone_permission")

	return nil
}

func registerLibFunc(fptr any, handle uintptr, name string) {
	sym, err := dlsymLibrary(handle, name)
	if err != nil {
		panic(err)
	}
	purego.RegisterFunc(fptr, sym)
}
