// Code generated by go generate; DO NOT EDIT.

//go:build ffigo_cgo

package ffi

/*
#include <stdint.h>

// Function pointer storage
static void* fn_shim_video_encoder_create;
static void* fn_shim_video_encoder_encode;
static void* fn_shim_video_encoder_set_bitrate;
static void* fn_shim_video_encoder_set_framerate;
static void* fn_shim_video_encoder_request_keyframe;
static void* fn_shim_video_encoder_destroy;
static void* fn_shim_video_decoder_create;
static void* fn_shim_video_decoder_decode;
static void* fn_shim_video_decoder_destroy;
static void* fn_shim_audio_encoder_create;
static void* fn_shim_audio_encoder_encode;
static void* fn_shim_audio_encoder_set_bitrate;
static void* fn_shim_audio_encoder_destroy;
static void* fn_shim_audio_decoder_create;
static void* fn_shim_audio_decoder_decode;
static void* fn_shim_audio_decoder_destroy;
static void* fn_shim_packetizer_create;
static void* fn_shim_packetizer_packetize;
static void* fn_shim_packetizer_sequence_number;
static void* fn_shim_packetizer_destroy;
static void* fn_shim_depacketizer_create;
static void* fn_shim_depacketizer_push;
static void* fn_shim_depacketizer_pop;
static void* fn_shim_depacketizer_destroy;
static void* fn_shim_free_buffer;
static void* fn_shim_free_packets;
static void* fn_shim_libwebrtc_version;
static void* fn_shim_version;
static void* fn_shim_peer_connection_create;
static void* fn_shim_peer_connection_destroy;
static void* fn_shim_peer_connection_set_on_ice_candidate;
static void* fn_shim_peer_connection_set_on_connection_state_change;
static void* fn_shim_peer_connection_set_on_track;
static void* fn_shim_peer_connection_set_on_data_channel;
static void* fn_shim_peer_connection_create_offer;
static void* fn_shim_peer_connection_create_answer;
static void* fn_shim_peer_connection_set_local_description;
static void* fn_shim_peer_connection_set_remote_description;
static void* fn_shim_peer_connection_add_ice_candidate;
static void* fn_shim_peer_connection_signaling_state;
static void* fn_shim_peer_connection_ice_connection_state;
static void* fn_shim_peer_connection_ice_gathering_state;
static void* fn_shim_peer_connection_connection_state;
static void* fn_shim_peer_connection_add_track;
static void* fn_shim_peer_connection_remove_track;
static void* fn_shim_peer_connection_create_data_channel;
static void* fn_shim_peer_connection_close;
static void* fn_shim_rtp_sender_set_bitrate;
static void* fn_shim_rtp_sender_replace_track;
static void* fn_shim_rtp_sender_destroy;
static void* fn_shim_data_channel_set_on_message;
static void* fn_shim_data_channel_set_on_open;
static void* fn_shim_data_channel_set_on_close;
static void* fn_shim_data_channel_send;
static void* fn_shim_data_channel_label;
static void* fn_shim_data_channel_ready_state;
static void* fn_shim_data_channel_close;
static void* fn_shim_data_channel_destroy;
static void* fn_shim_video_track_source_create;
static void* fn_shim_video_track_source_push_frame;
static void* fn_shim_peer_connection_add_video_track_from_source;
static void* fn_shim_video_track_source_destroy;
static void* fn_shim_audio_track_source_create;
static void* fn_shim_audio_track_source_push_frame;
static void* fn_shim_peer_connection_add_audio_track_from_source;
static void* fn_shim_audio_track_source_destroy;
static void* fn_shim_track_set_video_sink;
static void* fn_shim_track_set_audio_sink;
static void* fn_shim_track_remove_video_sink;
static void* fn_shim_track_remove_audio_sink;
static void* fn_shim_track_kind;
static void* fn_shim_track_id;
static void* fn_shim_rtp_sender_get_parameters;
static void* fn_shim_rtp_sender_set_parameters;
static void* fn_shim_rtp_sender_get_track;
static void* fn_shim_rtp_sender_get_stats;
static void* fn_shim_rtp_sender_set_on_rtcp_feedback;
static void* fn_shim_rtp_sender_set_layer_active;
static void* fn_shim_rtp_sender_set_layer_bitrate;
static void* fn_shim_rtp_sender_get_active_layers;
static void* fn_shim_rtp_receiver_get_track;
static void* fn_shim_rtp_receiver_get_stats;
static void* fn_shim_rtp_receiver_set_jitter_buffer_min_delay;
static void* fn_shim_transceiver_get_direction;
static void* fn_shim_transceiver_set_direction;
static void* fn_shim_transceiver_get_current_direction;
static void* fn_shim_transceiver_stop;
static void* fn_shim_transceiver_mid;
static void* fn_shim_transceiver_get_sender;
static void* fn_shim_transceiver_get_receiver;
static void* fn_shim_transceiver_set_codec_preferences;
static void* fn_shim_transceiver_get_codec_preferences;
static void* fn_shim_peer_connection_add_transceiver;
static void* fn_shim_peer_connection_get_senders;
static void* fn_shim_peer_connection_get_receivers;
static void* fn_shim_peer_connection_get_transceivers;
static void* fn_shim_peer_connection_restart_ice;
static void* fn_shim_peer_connection_get_stats;
static void* fn_shim_peer_connection_set_on_signaling_state_change;
static void* fn_shim_peer_connection_set_on_ice_connection_state_change;
static void* fn_shim_peer_connection_set_on_ice_gathering_state_change;
static void* fn_shim_peer_connection_set_on_negotiation_needed;
static void* fn_shim_rtp_sender_set_scalability_mode;
static void* fn_shim_rtp_sender_get_scalability_mode;
static void* fn_shim_get_supported_video_codecs;
static void* fn_shim_get_supported_audio_codecs;
static void* fn_shim_is_codec_supported;
static void* fn_shim_rtp_sender_get_negotiated_codecs;
static void* fn_shim_rtp_sender_set_preferred_codec;
static void* fn_shim_peer_connection_set_on_bandwidth_estimate;
static void* fn_shim_peer_connection_get_bandwidth_estimate;
static void* fn_shim_enumerate_devices;
static void* fn_shim_video_capture_create;
static void* fn_shim_video_capture_start;
static void* fn_shim_video_capture_stop;
static void* fn_shim_video_capture_destroy;
static void* fn_shim_audio_capture_create;
static void* fn_shim_audio_capture_start;
static void* fn_shim_audio_capture_stop;
static void* fn_shim_audio_capture_destroy;
static void* fn_shim_enumerate_screens;
static void* fn_shim_screen_capture_create;
static void* fn_shim_screen_capture_start;
static void* fn_shim_screen_capture_stop;
static void* fn_shim_screen_capture_destroy;
static void* fn_shim_check_camera_permission;
static void* fn_shim_check_microphone_permission;
static void* fn_shim_request_camera_permission;
static void* fn_shim_request_microphone_permission;

// Setters (called from Go after dlsym)
void set_fn_shim_video_encoder_create(void* fn) { fn_shim_video_encoder_create = fn; }
void set_fn_shim_video_encoder_encode(void* fn) { fn_shim_video_encoder_encode = fn; }
void set_fn_shim_video_encoder_set_bitrate(void* fn) { fn_shim_video_encoder_set_bitrate = fn; }
void set_fn_shim_video_encoder_set_framerate(void* fn) { fn_shim_video_encoder_set_framerate = fn; }
void set_fn_shim_video_encoder_request_keyframe(void* fn) { fn_shim_video_encoder_request_keyframe = fn; }
void set_fn_shim_video_encoder_destroy(void* fn) { fn_shim_video_encoder_destroy = fn; }
void set_fn_shim_video_decoder_create(void* fn) { fn_shim_video_decoder_create = fn; }
void set_fn_shim_video_decoder_decode(void* fn) { fn_shim_video_decoder_decode = fn; }
void set_fn_shim_video_decoder_destroy(void* fn) { fn_shim_video_decoder_destroy = fn; }
void set_fn_shim_audio_encoder_create(void* fn) { fn_shim_audio_encoder_create = fn; }
void set_fn_shim_audio_encoder_encode(void* fn) { fn_shim_audio_encoder_encode = fn; }
void set_fn_shim_audio_encoder_set_bitrate(void* fn) { fn_shim_audio_encoder_set_bitrate = fn; }
void set_fn_shim_audio_encoder_destroy(void* fn) { fn_shim_audio_encoder_destroy = fn; }
void set_fn_shim_audio_decoder_create(void* fn) { fn_shim_audio_decoder_create = fn; }
void set_fn_shim_audio_decoder_decode(void* fn) { fn_shim_audio_decoder_decode = fn; }
void set_fn_shim_audio_decoder_destroy(void* fn) { fn_shim_audio_decoder_destroy = fn; }
void set_fn_shim_packetizer_create(void* fn) { fn_shim_packetizer_create = fn; }
void set_fn_shim_packetizer_packetize(void* fn) { fn_shim_packetizer_packetize = fn; }
void set_fn_shim_packetizer_sequence_number(void* fn) { fn_shim_packetizer_sequence_number = fn; }
void set_fn_shim_packetizer_destroy(void* fn) { fn_shim_packetizer_destroy = fn; }
void set_fn_shim_depacketizer_create(void* fn) { fn_shim_depacketizer_create = fn; }
void set_fn_shim_depacketizer_push(void* fn) { fn_shim_depacketizer_push = fn; }
void set_fn_shim_depacketizer_pop(void* fn) { fn_shim_depacketizer_pop = fn; }
void set_fn_shim_depacketizer_destroy(void* fn) { fn_shim_depacketizer_destroy = fn; }
void set_fn_shim_free_buffer(void* fn) { fn_shim_free_buffer = fn; }
void set_fn_shim_free_packets(void* fn) { fn_shim_free_packets = fn; }
void set_fn_shim_libwebrtc_version(void* fn) { fn_shim_libwebrtc_version = fn; }
void set_fn_shim_version(void* fn) { fn_shim_version = fn; }
void set_fn_shim_peer_connection_create(void* fn) { fn_shim_peer_connection_create = fn; }
void set_fn_shim_peer_connection_destroy(void* fn) { fn_shim_peer_connection_destroy = fn; }
void set_fn_shim_peer_connection_set_on_ice_candidate(void* fn) { fn_shim_peer_connection_set_on_ice_candidate = fn; }
void set_fn_shim_peer_connection_set_on_connection_state_change(void* fn) { fn_shim_peer_connection_set_on_connection_state_change = fn; }
void set_fn_shim_peer_connection_set_on_track(void* fn) { fn_shim_peer_connection_set_on_track = fn; }
void set_fn_shim_peer_connection_set_on_data_channel(void* fn) { fn_shim_peer_connection_set_on_data_channel = fn; }
void set_fn_shim_peer_connection_create_offer(void* fn) { fn_shim_peer_connection_create_offer = fn; }
void set_fn_shim_peer_connection_create_answer(void* fn) { fn_shim_peer_connection_create_answer = fn; }
void set_fn_shim_peer_connection_set_local_description(void* fn) { fn_shim_peer_connection_set_local_description = fn; }
void set_fn_shim_peer_connection_set_remote_description(void* fn) { fn_shim_peer_connection_set_remote_description = fn; }
void set_fn_shim_peer_connection_add_ice_candidate(void* fn) { fn_shim_peer_connection_add_ice_candidate = fn; }
void set_fn_shim_peer_connection_signaling_state(void* fn) { fn_shim_peer_connection_signaling_state = fn; }
void set_fn_shim_peer_connection_ice_connection_state(void* fn) { fn_shim_peer_connection_ice_connection_state = fn; }
void set_fn_shim_peer_connection_ice_gathering_state(void* fn) { fn_shim_peer_connection_ice_gathering_state = fn; }
void set_fn_shim_peer_connection_connection_state(void* fn) { fn_shim_peer_connection_connection_state = fn; }
void set_fn_shim_peer_connection_add_track(void* fn) { fn_shim_peer_connection_add_track = fn; }
void set_fn_shim_peer_connection_remove_track(void* fn) { fn_shim_peer_connection_remove_track = fn; }
void set_fn_shim_peer_connection_create_data_channel(void* fn) { fn_shim_peer_connection_create_data_channel = fn; }
void set_fn_shim_peer_connection_close(void* fn) { fn_shim_peer_connection_close = fn; }
void set_fn_shim_rtp_sender_set_bitrate(void* fn) { fn_shim_rtp_sender_set_bitrate = fn; }
void set_fn_shim_rtp_sender_replace_track(void* fn) { fn_shim_rtp_sender_replace_track = fn; }
void set_fn_shim_rtp_sender_destroy(void* fn) { fn_shim_rtp_sender_destroy = fn; }
void set_fn_shim_data_channel_set_on_message(void* fn) { fn_shim_data_channel_set_on_message = fn; }
void set_fn_shim_data_channel_set_on_open(void* fn) { fn_shim_data_channel_set_on_open = fn; }
void set_fn_shim_data_channel_set_on_close(void* fn) { fn_shim_data_channel_set_on_close = fn; }
void set_fn_shim_data_channel_send(void* fn) { fn_shim_data_channel_send = fn; }
void set_fn_shim_data_channel_label(void* fn) { fn_shim_data_channel_label = fn; }
void set_fn_shim_data_channel_ready_state(void* fn) { fn_shim_data_channel_ready_state = fn; }
void set_fn_shim_data_channel_close(void* fn) { fn_shim_data_channel_close = fn; }
void set_fn_shim_data_channel_destroy(void* fn) { fn_shim_data_channel_destroy = fn; }
void set_fn_shim_video_track_source_create(void* fn) { fn_shim_video_track_source_create = fn; }
void set_fn_shim_video_track_source_push_frame(void* fn) { fn_shim_video_track_source_push_frame = fn; }
void set_fn_shim_peer_connection_add_video_track_from_source(void* fn) { fn_shim_peer_connection_add_video_track_from_source = fn; }
void set_fn_shim_video_track_source_destroy(void* fn) { fn_shim_video_track_source_destroy = fn; }
void set_fn_shim_audio_track_source_create(void* fn) { fn_shim_audio_track_source_create = fn; }
void set_fn_shim_audio_track_source_push_frame(void* fn) { fn_shim_audio_track_source_push_frame = fn; }
void set_fn_shim_peer_connection_add_audio_track_from_source(void* fn) { fn_shim_peer_connection_add_audio_track_from_source = fn; }
void set_fn_shim_audio_track_source_destroy(void* fn) { fn_shim_audio_track_source_destroy = fn; }
void set_fn_shim_track_set_video_sink(void* fn) { fn_shim_track_set_video_sink = fn; }
void set_fn_shim_track_set_audio_sink(void* fn) { fn_shim_track_set_audio_sink = fn; }
void set_fn_shim_track_remove_video_sink(void* fn) { fn_shim_track_remove_video_sink = fn; }
void set_fn_shim_track_remove_audio_sink(void* fn) { fn_shim_track_remove_audio_sink = fn; }
void set_fn_shim_track_kind(void* fn) { fn_shim_track_kind = fn; }
void set_fn_shim_track_id(void* fn) { fn_shim_track_id = fn; }
void set_fn_shim_rtp_sender_get_parameters(void* fn) { fn_shim_rtp_sender_get_parameters = fn; }
void set_fn_shim_rtp_sender_set_parameters(void* fn) { fn_shim_rtp_sender_set_parameters = fn; }
void set_fn_shim_rtp_sender_get_track(void* fn) { fn_shim_rtp_sender_get_track = fn; }
void set_fn_shim_rtp_sender_get_stats(void* fn) { fn_shim_rtp_sender_get_stats = fn; }
void set_fn_shim_rtp_sender_set_on_rtcp_feedback(void* fn) { fn_shim_rtp_sender_set_on_rtcp_feedback = fn; }
void set_fn_shim_rtp_sender_set_layer_active(void* fn) { fn_shim_rtp_sender_set_layer_active = fn; }
void set_fn_shim_rtp_sender_set_layer_bitrate(void* fn) { fn_shim_rtp_sender_set_layer_bitrate = fn; }
void set_fn_shim_rtp_sender_get_active_layers(void* fn) { fn_shim_rtp_sender_get_active_layers = fn; }
void set_fn_shim_rtp_receiver_get_track(void* fn) { fn_shim_rtp_receiver_get_track = fn; }
void set_fn_shim_rtp_receiver_get_stats(void* fn) { fn_shim_rtp_receiver_get_stats = fn; }
void set_fn_shim_rtp_receiver_set_jitter_buffer_min_delay(void* fn) { fn_shim_rtp_receiver_set_jitter_buffer_min_delay = fn; }
void set_fn_shim_transceiver_get_direction(void* fn) { fn_shim_transceiver_get_direction = fn; }
void set_fn_shim_transceiver_set_direction(void* fn) { fn_shim_transceiver_set_direction = fn; }
void set_fn_shim_transceiver_get_current_direction(void* fn) { fn_shim_transceiver_get_current_direction = fn; }
void set_fn_shim_transceiver_stop(void* fn) { fn_shim_transceiver_stop = fn; }
void set_fn_shim_transceiver_mid(void* fn) { fn_shim_transceiver_mid = fn; }
void set_fn_shim_transceiver_get_sender(void* fn) { fn_shim_transceiver_get_sender = fn; }
void set_fn_shim_transceiver_get_receiver(void* fn) { fn_shim_transceiver_get_receiver = fn; }
void set_fn_shim_transceiver_set_codec_preferences(void* fn) { fn_shim_transceiver_set_codec_preferences = fn; }
void set_fn_shim_transceiver_get_codec_preferences(void* fn) { fn_shim_transceiver_get_codec_preferences = fn; }
void set_fn_shim_peer_connection_add_transceiver(void* fn) { fn_shim_peer_connection_add_transceiver = fn; }
void set_fn_shim_peer_connection_get_senders(void* fn) { fn_shim_peer_connection_get_senders = fn; }
void set_fn_shim_peer_connection_get_receivers(void* fn) { fn_shim_peer_connection_get_receivers = fn; }
void set_fn_shim_peer_connection_get_transceivers(void* fn) { fn_shim_peer_connection_get_transceivers = fn; }
void set_fn_shim_peer_connection_restart_ice(void* fn) { fn_shim_peer_connection_restart_ice = fn; }
void set_fn_shim_peer_connection_get_stats(void* fn) { fn_shim_peer_connection_get_stats = fn; }
void set_fn_shim_peer_connection_set_on_signaling_state_change(void* fn) { fn_shim_peer_connection_set_on_signaling_state_change = fn; }
void set_fn_shim_peer_connection_set_on_ice_connection_state_change(void* fn) { fn_shim_peer_connection_set_on_ice_connection_state_change = fn; }
void set_fn_shim_peer_connection_set_on_ice_gathering_state_change(void* fn) { fn_shim_peer_connection_set_on_ice_gathering_state_change = fn; }
void set_fn_shim_peer_connection_set_on_negotiation_needed(void* fn) { fn_shim_peer_connection_set_on_negotiation_needed = fn; }
void set_fn_shim_rtp_sender_set_scalability_mode(void* fn) { fn_shim_rtp_sender_set_scalability_mode = fn; }
void set_fn_shim_rtp_sender_get_scalability_mode(void* fn) { fn_shim_rtp_sender_get_scalability_mode = fn; }
void set_fn_shim_get_supported_video_codecs(void* fn) { fn_shim_get_supported_video_codecs = fn; }
void set_fn_shim_get_supported_audio_codecs(void* fn) { fn_shim_get_supported_audio_codecs = fn; }
void set_fn_shim_is_codec_supported(void* fn) { fn_shim_is_codec_supported = fn; }
void set_fn_shim_rtp_sender_get_negotiated_codecs(void* fn) { fn_shim_rtp_sender_get_negotiated_codecs = fn; }
void set_fn_shim_rtp_sender_set_preferred_codec(void* fn) { fn_shim_rtp_sender_set_preferred_codec = fn; }
void set_fn_shim_peer_connection_set_on_bandwidth_estimate(void* fn) { fn_shim_peer_connection_set_on_bandwidth_estimate = fn; }
void set_fn_shim_peer_connection_get_bandwidth_estimate(void* fn) { fn_shim_peer_connection_get_bandwidth_estimate = fn; }
void set_fn_shim_enumerate_devices(void* fn) { fn_shim_enumerate_devices = fn; }
void set_fn_shim_video_capture_create(void* fn) { fn_shim_video_capture_create = fn; }
void set_fn_shim_video_capture_start(void* fn) { fn_shim_video_capture_start = fn; }
void set_fn_shim_video_capture_stop(void* fn) { fn_shim_video_capture_stop = fn; }
void set_fn_shim_video_capture_destroy(void* fn) { fn_shim_video_capture_destroy = fn; }
void set_fn_shim_audio_capture_create(void* fn) { fn_shim_audio_capture_create = fn; }
void set_fn_shim_audio_capture_start(void* fn) { fn_shim_audio_capture_start = fn; }
void set_fn_shim_audio_capture_stop(void* fn) { fn_shim_audio_capture_stop = fn; }
void set_fn_shim_audio_capture_destroy(void* fn) { fn_shim_audio_capture_destroy = fn; }
void set_fn_shim_enumerate_screens(void* fn) { fn_shim_enumerate_screens = fn; }
void set_fn_shim_screen_capture_create(void* fn) { fn_shim_screen_capture_create = fn; }
void set_fn_shim_screen_capture_start(void* fn) { fn_shim_screen_capture_start = fn; }
void set_fn_shim_screen_capture_stop(void* fn) { fn_shim_screen_capture_stop = fn; }
void set_fn_shim_screen_capture_destroy(void* fn) { fn_shim_screen_capture_destroy = fn; }
void set_fn_shim_check_camera_permission(void* fn) { fn_shim_check_camera_permission = fn; }
void set_fn_shim_check_microphone_permission(void* fn) { fn_shim_check_microphone_permission = fn; }
void set_fn_shim_request_camera_permission(void* fn) { fn_shim_request_camera_permission = fn; }
void set_fn_shim_request_microphone_permission(void* fn) { fn_shim_request_microphone_permission = fn; }

// Trampoline functions
uintptr_t call_shim_video_encoder_create(int32_t codec, uintptr_t configPtr, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_encoder_create)(codec, configPtr, errorOut);
}
int32_t call_shim_video_encoder_encode(uintptr_t encoder, uintptr_t yPlane, uintptr_t uPlane, uintptr_t vPlane, int32_t yStride, int32_t uStride, int32_t vStride, uint32_t timestamp, int32_t forceKeyframe, uintptr_t outData, int32_t dstBufferSize, uintptr_t outSize, uintptr_t outIsKeyframe, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, int32_t, int32_t, int32_t, uint32_t, int32_t, uintptr_t, int32_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_encoder_encode)(encoder, yPlane, uPlane, vPlane, yStride, uStride, vStride, timestamp, forceKeyframe, outData, dstBufferSize, outSize, outIsKeyframe, errorOut);
}
int32_t call_shim_video_encoder_set_bitrate(uintptr_t encoder, uint32_t bitrate) {
    typedef int32_t (*fn_t)(uintptr_t, uint32_t);
    return ((fn_t)fn_shim_video_encoder_set_bitrate)(encoder, bitrate);
}
int32_t call_shim_video_encoder_set_framerate(uintptr_t encoder, float framerate) {
    typedef int32_t (*fn_t)(uintptr_t, float);
    return ((fn_t)fn_shim_video_encoder_set_framerate)(encoder, framerate);
}
int32_t call_shim_video_encoder_request_keyframe(uintptr_t encoder) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_encoder_request_keyframe)(encoder);
}
void call_shim_video_encoder_destroy(uintptr_t encoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_encoder_destroy)(encoder);
}
uintptr_t call_shim_video_decoder_create(int32_t codec, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(int32_t, uintptr_t);
    return ((fn_t)fn_shim_video_decoder_create)(codec, errorOut);
}
int32_t call_shim_video_decoder_decode(uintptr_t decoder, uintptr_t data, int32_t size, uint32_t timestamp, int32_t isKeyframe, uintptr_t outY, uintptr_t outU, uintptr_t outV, uintptr_t outW, uintptr_t outH, uintptr_t outYStride, uintptr_t outUStride, uintptr_t outVStride, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uint32_t, int32_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_decoder_decode)(decoder, data, size, timestamp, isKeyframe, outY, outU, outV, outW, outH, outYStride, outUStride, outVStride, errorOut);
}
void call_shim_video_decoder_destroy(uintptr_t decoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_decoder_destroy)(decoder);
}
uintptr_t call_shim_audio_encoder_create(uintptr_t configPtr, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_encoder_create)(configPtr, errorOut);
}
int32_t call_shim_audio_encoder_encode(uintptr_t encoder, uintptr_t samples, int32_t numSamples, uintptr_t outData, uintptr_t outSize) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_encoder_encode)(encoder, samples, numSamples, outData, outSize);
}
int32_t call_shim_audio_encoder_set_bitrate(uintptr_t encoder, uint32_t bitrate) {
    typedef int32_t (*fn_t)(uintptr_t, uint32_t);
    return ((fn_t)fn_shim_audio_encoder_set_bitrate)(encoder, bitrate);
}
void call_shim_audio_encoder_destroy(uintptr_t encoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_encoder_destroy)(encoder);
}
uintptr_t call_shim_audio_decoder_create(int32_t sampleRate, int32_t channels, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(int32_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_audio_decoder_create)(sampleRate, channels, errorOut);
}
int32_t call_shim_audio_decoder_decode(uintptr_t decoder, uintptr_t data, int32_t size, uintptr_t outSamples, uintptr_t outNumSamples, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_decoder_decode)(decoder, data, size, outSamples, outNumSamples, errorOut);
}
void call_shim_audio_decoder_destroy(uintptr_t decoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_decoder_destroy)(decoder);
}
uintptr_t call_shim_packetizer_create(uintptr_t configPtr) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_packetizer_create)(configPtr);
}
int32_t call_shim_packetizer_packetize(uintptr_t packetizer, uintptr_t data, int32_t size, uint32_t timestamp, int32_t isKeyframe, uintptr_t dst, uintptr_t offsets, uintptr_t sizes, int32_t maxPackets, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uint32_t, int32_t, uintptr_t, uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_packetizer_packetize)(packetizer, data, size, timestamp, isKeyframe, dst, offsets, sizes, maxPackets, outCount);
}
uint16_t call_shim_packetizer_sequence_number(uintptr_t packetizer) {
    typedef uint16_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_packetizer_sequence_number)(packetizer);
}
void call_shim_packetizer_destroy(uintptr_t packetizer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_packetizer_destroy)(packetizer);
}
uintptr_t call_shim_depacketizer_create(int32_t codec) {
    typedef uintptr_t (*fn_t)(int32_t);
    return ((fn_t)fn_shim_depacketizer_create)(codec);
}
int32_t call_shim_depacketizer_push(uintptr_t depacketizer, uintptr_t data, int32_t size) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t);
    return ((fn_t)fn_shim_depacketizer_push)(depacketizer, data, size);
}
int32_t call_shim_depacketizer_pop(uintptr_t depacketizer, uintptr_t outData, uintptr_t outSize, uintptr_t outTimestamp, uintptr_t outIsKeyframe) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_depacketizer_pop)(depacketizer, outData, outSize, outTimestamp, outIsKeyframe);
}
void call_shim_depacketizer_destroy(uintptr_t depacketizer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_depacketizer_destroy)(depacketizer);
}
void call_shim_free_buffer(uintptr_t buffer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_free_buffer)(buffer);
}
void call_shim_free_packets(uintptr_t packets, uintptr_t sizes, int32_t count) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, int32_t);
    ((fn_t)fn_shim_free_packets)(packets, sizes, count);
}
uintptr_t call_shim_libwebrtc_version() {
    typedef uintptr_t (*fn_t)();
    return ((fn_t)fn_shim_libwebrtc_version)();
}
uintptr_t call_shim_version() {
    typedef uintptr_t (*fn_t)();
    return ((fn_t)fn_shim_version)();
}
uintptr_t call_shim_peer_connection_create(uintptr_t configPtr, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create)(configPtr, errorOut);
}
void call_shim_peer_connection_destroy(uintptr_t pc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_destroy)(pc);
}
void call_shim_peer_connection_set_on_ice_candidate(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_candidate)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_connection_state_change(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_connection_state_change)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_track(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_track)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_data_channel(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_data_channel)(pc, callback, ctx);
}
int32_t call_shim_peer_connection_create_offer(uintptr_t pc, uintptr_t sdpOut, int32_t sdpOutSize, uintptr_t outSdpLen, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_offer)(pc, sdpOut, sdpOutSize, outSdpLen, errorOut);
}
int32_t call_shim_peer_connection_create_answer(uintptr_t pc, uintptr_t sdpOut, int32_t sdpOutSize, uintptr_t outSdpLen, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_answer)(pc, sdpOut, sdpOutSize, outSdpLen, errorOut);
}
int32_t call_shim_peer_connection_set_local_description(uintptr_t pc, int32_t sdpType, uintptr_t sdp, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_set_local_description)(pc, sdpType, sdp, errorOut);
}
int32_t call_shim_peer_connection_set_remote_description(uintptr_t pc, int32_t sdpType, uintptr_t sdp, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_set_remote_description)(pc, sdpType, sdp, errorOut);
}
int32_t call_shim_peer_connection_add_ice_candidate(uintptr_t pc, uintptr_t candidate, uintptr_t sdpMid, int32_t sdpMLineIndex, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_ice_candidate)(pc, candidate, sdpMid, sdpMLineIndex, errorOut);
}
int32_t call_shim_peer_connection_signaling_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_signaling_state)(pc);
}
int32_t call_shim_peer_connection_ice_connection_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_ice_connection_state)(pc);
}
int32_t call_shim_peer_connection_ice_gathering_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_ice_gathering_state)(pc);
}
int32_t call_shim_peer_connection_connection_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_connection_state)(pc);
}
uintptr_t call_shim_peer_connection_add_track(uintptr_t pc, int32_t codec, uintptr_t trackID, uintptr_t streamID, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_track)(pc, codec, trackID, streamID, errorOut);
}
int32_t call_shim_peer_connection_remove_track(uintptr_t pc, uintptr_t sender, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_remove_track)(pc, sender, errorOut);
}
uintptr_t call_shim_peer_connection_create_data_channel(uintptr_t pc, uintptr_t label, int32_t ordered, int32_t maxRetransmits, uintptr_t protocol, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, uintptr_t, int32_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_data_channel)(pc, label, ordered, maxRetransmits, protocol, errorOut);
}
void call_shim_peer_connection_close(uintptr_t pc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_close)(pc);
}
int32_t call_shim_rtp_sender_set_bitrate(uintptr_t sender, uint32_t bitrate, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uint32_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_bitrate)(sender, bitrate, errorOut);
}
int32_t call_shim_rtp_sender_replace_track(uintptr_t sender, uintptr_t track) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_replace_track)(sender, track);
}
void call_shim_rtp_sender_destroy(uintptr_t sender) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_rtp_sender_destroy)(sender);
}
void call_shim_data_channel_set_on_message(uintptr_t dc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_message)(dc, callback, ctx);
}
void call_shim_data_channel_set_on_open(uintptr_t dc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_open)(dc, callback, ctx);
}
void call_shim_data_channel_set_on_close(uintptr_t dc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_close)(dc, callback, ctx);
}
int32_t call_shim_data_channel_send(uintptr_t dc, uintptr_t data, int32_t size, int32_t isBinary, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_data_channel_send)(dc, data, size, isBinary, errorOut);
}
uintptr_t call_shim_data_channel_label(uintptr_t dc) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_data_channel_label)(dc);
}
int32_t call_shim_data_channel_ready_state(uintptr_t dc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_data_channel_ready_state)(dc);
}
void call_shim_data_channel_close(uintptr_t dc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_close)(dc);
}
void call_shim_data_channel_destroy(uintptr_t dc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_destroy)(dc);
}
uintptr_t call_shim_video_track_source_create(uintptr_t pc, int32_t width, int32_t height) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, int32_t);
    return ((fn_t)fn_shim_video_track_source_create)(pc, width, height);
}
int32_t call_shim_video_track_source_push_frame(uintptr_t source, uintptr_t yPlane, uintptr_t uPlane, uintptr_t vPlane, int32_t yStride, int32_t uStride, int32_t vStride, int64_t timestampUs) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, int32_t, int32_t, int32_t, int64_t);
    return ((fn_t)fn_shim_video_track_source_push_frame)(source, yPlane, uPlane, vPlane, yStride, uStride, vStride, timestampUs);
}
uintptr_t call_shim_peer_connection_add_video_track_from_source(uintptr_t pc, uintptr_t source, uintptr_t trackID, uintptr_t streamID, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_video_track_from_source)(pc, source, trackID, streamID, errorOut);
}
void call_shim_video_track_source_destroy(uintptr_t source) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_track_source_destroy)(source);
}
uintptr_t call_shim_audio_track_source_create(uintptr_t pc, int32_t sampleRate, int32_t channels) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, int32_t);
    return ((fn_t)fn_shim_audio_track_source_create)(pc, sampleRate, channels);
}
int32_t call_shim_audio_track_source_push_frame(uintptr_t source, uintptr_t samples, int32_t numSamples, int64_t timestampUs) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, int64_t);
    return ((fn_t)fn_shim_audio_track_source_push_frame)(source, samples, numSamples, timestampUs);
}
uintptr_t call_shim_peer_connection_add_audio_track_from_source(uintptr_t pc, uintptr_t source, uintptr_t trackID, uintptr_t streamID, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_audio_track_from_source)(pc, source, trackID, streamID, errorOut);
}
void call_shim_audio_track_source_destroy(uintptr_t source) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_track_source_destroy)(source);
}
int32_t call_shim_track_set_video_sink(uintptr_t track, uintptr_t callback, uintptr_t ctx) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_track_set_video_sink)(track, callback, ctx);
}
int32_t call_shim_track_set_audio_sink(uintptr_t track, uintptr_t callback, uintptr_t ctx) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_track_set_audio_sink)(track, callback, ctx);
}
void call_shim_track_remove_video_sink(uintptr_t track) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_track_remove_video_sink)(track);
}
void call_shim_track_remove_audio_sink(uintptr_t track) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_track_remove_audio_sink)(track);
}
uintptr_t call_shim_track_kind(uintptr_t track) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_kind)(track);
}
uintptr_t call_shim_track_id(uintptr_t track) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_id)(track);
}
int32_t call_shim_rtp_sender_get_parameters(uintptr_t sender, uintptr_t outParams, uintptr_t encodings, int32_t maxEncodings) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, int32_t);
    return ((fn_t)fn_shim_rtp_sender_get_parameters)(sender, outParams, encodings, maxEncodings);
}
int32_t call_shim_rtp_sender_set_parameters(uintptr_t sender, uintptr_t params, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_parameters)(sender, params, errorOut);
}
uintptr_t call_shim_rtp_sender_get_track(uintptr_t sender) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_track)(sender);
}
int32_t call_shim_rtp_sender_get_stats(uintptr_t sender, uintptr_t outStats) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_stats)(sender, outStats);
}
void call_shim_rtp_sender_set_on_rtcp_feedback(uintptr_t sender, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_rtp_sender_set_on_rtcp_feedback)(sender, callback, ctx);
}
int32_t call_shim_rtp_sender_set_layer_active(uintptr_t sender, uintptr_t rid, int32_t active, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_layer_active)(sender, rid, active, errorOut);
}
int32_t call_shim_rtp_sender_set_layer_bitrate(uintptr_t sender, uintptr_t rid, uint32_t maxBitrate, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uint32_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_layer_bitrate)(sender, rid, maxBitrate, errorOut);
}
int32_t call_shim_rtp_sender_get_active_layers(uintptr_t sender, uintptr_t outSpatial, uintptr_t outTemporal) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_active_layers)(sender, outSpatial, outTemporal);
}
uintptr_t call_shim_rtp_receiver_get_track(uintptr_t receiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_receiver_get_track)(receiver);
}
int32_t call_shim_rtp_receiver_get_stats(uintptr_t receiver, uintptr_t outStats) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_receiver_get_stats)(receiver, outStats);
}
int32_t call_shim_rtp_receiver_set_jitter_buffer_min_delay(uintptr_t receiver, int32_t minDelayMs) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t);
    return ((fn_t)fn_shim_rtp_receiver_set_jitter_buffer_min_delay)(receiver, minDelayMs);
}
int32_t call_shim_transceiver_get_direction(uintptr_t transceiver) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_direction)(transceiver);
}
int32_t call_shim_transceiver_set_direction(uintptr_t transceiver, int32_t direction, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_transceiver_set_direction)(transceiver, direction, errorOut);
}
int32_t call_shim_transceiver_get_current_direction(uintptr_t transceiver) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_current_direction)(transceiver);
}
int32_t call_shim_transceiver_stop(uintptr_t transceiver, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_transceiver_stop)(transceiver, errorOut);
}
uintptr_t call_shim_transceiver_mid(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_mid)(transceiver);
}
uintptr_t call_shim_transceiver_get_sender(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_sender)(transceiver);
}
uintptr_t call_shim_transceiver_get_receiver(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_receiver)(transceiver);
}
int32_t call_shim_transceiver_set_codec_preferences(uintptr_t transceiver, uintptr_t codecs, int32_t count, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_transceiver_set_codec_preferences)(transceiver, codecs, count, errorOut);
}
int32_t call_shim_transceiver_get_codec_preferences(uintptr_t transceiver, uintptr_t codecs, int32_t maxCodecs, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_codec_preferences)(transceiver, codecs, maxCodecs, outCount);
}
uintptr_t call_shim_peer_connection_add_transceiver(uintptr_t pc, int32_t kind, int32_t direction, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_transceiver)(pc, kind, direction, errorOut);
}
int32_t call_shim_peer_connection_get_senders(uintptr_t pc, uintptr_t senders, int32_t maxSenders, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_senders)(pc, senders, maxSenders, outCount);
}
int32_t call_shim_peer_connection_get_receivers(uintptr_t pc, uintptr_t receivers, int32_t maxReceivers, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_receivers)(pc, receivers, maxReceivers, outCount);
}
int32_t call_shim_peer_connection_get_transceivers(uintptr_t pc, uintptr_t transceivers, int32_t maxTransceivers, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_transceivers)(pc, transceivers, maxTransceivers, outCount);
}
int32_t call_shim_peer_connection_restart_ice(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_restart_ice)(pc);
}
int32_t call_shim_peer_connection_get_stats(uintptr_t pc, uintptr_t outStats) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_stats)(pc, outStats);
}
void call_shim_peer_connection_set_on_signaling_state_change(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_signaling_state_change)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_ice_connection_state_change(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_connection_state_change)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_ice_gathering_state_change(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_gathering_state_change)(pc, callback, ctx);
}
void call_shim_peer_connection_set_on_negotiation_needed(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_negotiation_needed)(pc, callback, ctx);
}
int32_t call_shim_rtp_sender_set_scalability_mode(uintptr_t sender, uintptr_t mode, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_scalability_mode)(sender, mode, errorOut);
}
int32_t call_shim_rtp_sender_get_scalability_mode(uintptr_t sender, uintptr_t modeOut, int32_t modeOutSize) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t);
    return ((fn_t)fn_shim_rtp_sender_get_scalability_mode)(sender, modeOut, modeOutSize);
}
int32_t call_shim_get_supported_video_codecs(uintptr_t codecs, int32_t maxCodecs, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_get_supported_video_codecs)(codecs, maxCodecs, outCount);
}
int32_t call_shim_get_supported_audio_codecs(uintptr_t codecs, int32_t maxCodecs, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_get_supported_audio_codecs)(codecs, maxCodecs, outCount);
}
int32_t call_shim_is_codec_supported(uintptr_t mimeType) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_is_codec_supported)(mimeType);
}
int32_t call_shim_rtp_sender_get_negotiated_codecs(uintptr_t sender, uintptr_t codecs, int32_t maxCodecs, uintptr_t outCount) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_negotiated_codecs)(sender, codecs, maxCodecs, outCount);
}
int32_t call_shim_rtp_sender_set_preferred_codec(uintptr_t sender, uintptr_t mimeType, int32_t payloadType, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_preferred_codec)(sender, mimeType, payloadType, errorOut);
}
void call_shim_peer_connection_set_on_bandwidth_estimate(uintptr_t pc, uintptr_t callback, uintptr_t ctx) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_bandwidth_estimate)(pc, callback, ctx);
}
int32_t call_shim_peer_connection_get_bandwidth_estimate(uintptr_t pc, uintptr_t outEstimate) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_bandwidth_estimate)(pc, outEstimate);
}
int32_t call_shim_enumerate_devices(uintptr_t devices, int32_t maxDevices, uintptr_t outCount, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_enumerate_devices)(devices, maxDevices, outCount, errorOut);
}
uintptr_t call_shim_video_capture_create(uintptr_t deviceID, int32_t width, int32_t height, int32_t fps, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, int32_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_video_capture_create)(deviceID, width, height, fps, errorOut);
}
int32_t call_shim_video_capture_start(uintptr_t capturePtr, uintptr_t callback, uintptr_t ctx, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_capture_start)(capturePtr, callback, ctx, errorOut);
}
void call_shim_video_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_capture_stop)(capturePtr);
}
void call_shim_video_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_capture_destroy)(capturePtr);
}
uintptr_t call_shim_audio_capture_create(uintptr_t deviceID, int32_t sampleRate, int32_t channels, uintptr_t errorOut) {
    typedef uintptr_t (*fn_t)(uintptr_t, int32_t, int32_t, uintptr_t);
    return ((fn_t)fn_shim_audio_capture_create)(deviceID, sampleRate, channels, errorOut);
}
int32_t call_shim_audio_capture_start(uintptr_t capturePtr, uintptr_t callback, uintptr_t ctx, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_capture_start)(capturePtr, callback, ctx, errorOut);
}
void call_shim_audio_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_capture_stop)(capturePtr);
}
void call_shim_audio_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_capture_destroy)(capturePtr);
}
int32_t call_shim_enumerate_screens(uintptr_t screens, int32_t maxScreens, uintptr_t outCount, uintptr_t errorOut) {
    typedef int32_t (*fn_t)(uintptr_t, int32_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_enumerate_screens)(screens, maxScreens, outCount, errorOut);
}
uintptr_t call_shim_screen_capture_create(int64_t id, int32_t isWindow, int32_t fps) {
    typedef uintptr_t (*fn_t)(int64_t, int32_t, int32_t);
    return ((fn_t)fn_shim_screen_capture_create)(id, isWindow, fps);
}
int32_t call_shim_screen_capture_start(uintptr_t capturePtr, uintptr_t callback, uintptr_t ctx) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_screen_capture_start)(capturePtr, callback, ctx);
}
void call_shim_screen_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_screen_capture_stop)(capturePtr);
}
void call_shim_screen_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_screen_capture_destroy)(capturePtr);
}
int32_t call_shim_check_camera_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_check_camera_permission)();
}
int32_t call_shim_check_microphone_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_check_microphone_permission)();
}
int32_t call_shim_request_camera_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_request_camera_permission)();
}
int32_t call_shim_request_microphone_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_request_microphone_permission)();
}
*/
import "C"
import "unsafe"

func registerFunctions() error {
	// VideoEncoder
	C.set_fn_shim_video_encoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_create")))
	C.set_fn_shim_video_encoder_encode(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_encode")))
	C.set_fn_shim_video_encoder_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_set_bitrate")))
	C.set_fn_shim_video_encoder_set_framerate(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_set_framerate")))
	C.set_fn_shim_video_encoder_request_keyframe(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_request_keyframe")))
	C.set_fn_shim_video_encoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_destroy")))

	// VideoDecoder
	C.set_fn_shim_video_decoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_create")))
	C.set_fn_shim_video_decoder_decode(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_decode")))
	C.set_fn_shim_video_decoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_destroy")))

	// AudioEncoder
	C.set_fn_shim_audio_encoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_create")))
	C.set_fn_shim_audio_encoder_encode(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_encode")))
	C.set_fn_shim_audio_encoder_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_set_bitrate")))
	C.set_fn_shim_audio_encoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_destroy")))

	// AudioDecoder
	C.set_fn_shim_audio_decoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_create")))
	C.set_fn_shim_audio_decoder_decode(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_decode")))
	C.set_fn_shim_audio_decoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_destroy")))

	// Packetizer
	C.set_fn_shim_packetizer_create(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_create")))
	C.set_fn_shim_packetizer_packetize(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_packetize")))
	C.set_fn_shim_packetizer_sequence_number(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_sequence_number")))
	C.set_fn_shim_packetizer_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_destroy")))

	// Depacketizer
	C.set_fn_shim_depacketizer_create(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_create")))
	C.set_fn_shim_depacketizer_push(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_push")))
	C.set_fn_shim_depacketizer_pop(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_pop")))
	C.set_fn_shim_depacketizer_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_destroy")))

	// Memory
	C.set_fn_shim_free_buffer(unsafe.Pointer(mustDlsym(libHandle, "shim_free_buffer")))
	C.set_fn_shim_free_packets(unsafe.Pointer(mustDlsym(libHandle, "shim_free_packets")))

	// Version
	C.set_fn_shim_libwebrtc_version(unsafe.Pointer(mustDlsym(libHandle, "shim_libwebrtc_version")))
	C.set_fn_shim_version(unsafe.Pointer(mustDlsym(libHandle, "shim_version")))

	// PeerConnection
	C.set_fn_shim_peer_connection_create(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create")))
	C.set_fn_shim_peer_connection_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_destroy")))
	C.set_fn_shim_peer_connection_set_on_ice_candidate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_candidate")))
	C.set_fn_shim_peer_connection_set_on_connection_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_connection_state_change")))
	C.set_fn_shim_peer_connection_set_on_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_track")))
	C.set_fn_shim_peer_connection_set_on_data_channel(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_data_channel")))
	C.set_fn_shim_peer_connection_create_offer(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_offer")))
	C.set_fn_shim_peer_connection_create_answer(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_answer")))
	C.set_fn_shim_peer_connection_set_local_description(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_local_description")))
	C.set_fn_shim_peer_connection_set_remote_description(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_remote_description")))
	C.set_fn_shim_peer_connection_add_ice_candidate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_ice_candidate")))
	C.set_fn_shim_peer_connection_signaling_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_signaling_state")))
	C.set_fn_shim_peer_connection_ice_connection_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_ice_connection_state")))
	C.set_fn_shim_peer_connection_ice_gathering_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_ice_gathering_state")))
	C.set_fn_shim_peer_connection_connection_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_connection_state")))
	C.set_fn_shim_peer_connection_add_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_track")))
	C.set_fn_shim_peer_connection_remove_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_remove_track")))
	C.set_fn_shim_peer_connection_create_data_channel(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_data_channel")))
	C.set_fn_shim_peer_connection_close(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_close")))

	// PeerConnectionExtended
	C.set_fn_shim_peer_connection_add_transceiver(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_transceiver")))
	C.set_fn_shim_peer_connection_get_senders(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_senders")))
	C.set_fn_shim_peer_connection_get_receivers(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_receivers")))
	C.set_fn_shim_peer_connection_get_transceivers(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_transceivers")))
	C.set_fn_shim_peer_connection_restart_ice(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_restart_ice")))
	C.set_fn_shim_peer_connection_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_stats")))
	C.set_fn_shim_peer_connection_set_on_signaling_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_signaling_state_change")))
	C.set_fn_shim_peer_connection_set_on_ice_connection_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_connection_state_change")))
	C.set_fn_shim_peer_connection_set_on_ice_gathering_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_gathering_state_change")))
	C.set_fn_shim_peer_connection_set_on_negotiation_needed(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_negotiation_needed")))

	// RTPSender
	C.set_fn_shim_rtp_sender_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_bitrate")))
	C.set_fn_shim_rtp_sender_replace_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_replace_track")))
	C.set_fn_shim_rtp_sender_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_destroy")))
	C.set_fn_shim_rtp_sender_get_parameters(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_parameters")))
	C.set_fn_shim_rtp_sender_set_parameters(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_parameters")))
	C.set_fn_shim_rtp_sender_get_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_track")))
	C.set_fn_shim_rtp_sender_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_stats")))
	C.set_fn_shim_rtp_sender_set_on_rtcp_feedback(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_on_rtcp_feedback")))
	C.set_fn_shim_rtp_sender_set_layer_active(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_layer_active")))
	C.set_fn_shim_rtp_sender_set_layer_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_layer_bitrate")))
	C.set_fn_shim_rtp_sender_get_active_layers(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_active_layers")))

	// RTPReceiver
	C.set_fn_shim_rtp_receiver_get_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_get_track")))
	C.set_fn_shim_rtp_receiver_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_get_stats")))
	C.set_fn_shim_rtp_receiver_set_jitter_buffer_min_delay(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_set_jitter_buffer_min_delay")))

	// RTPTransceiver
	C.set_fn_shim_transceiver_get_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_direction")))
	C.set_fn_shim_transceiver_set_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_set_direction")))
	C.set_fn_shim_transceiver_get_current_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_current_direction")))
	C.set_fn_shim_transceiver_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_stop")))
	C.set_fn_shim_transceiver_mid(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_mid")))
	C.set_fn_shim_transceiver_get_sender(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_sender")))
	C.set_fn_shim_transceiver_get_receiver(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_receiver")))
	C.set_fn_shim_transceiver_set_codec_preferences(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_set_codec_preferences")))
	C.set_fn_shim_transceiver_get_codec_preferences(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_codec_preferences")))

	// DataChannel
	C.set_fn_shim_data_channel_set_on_message(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_message")))
	C.set_fn_shim_data_channel_set_on_open(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_open")))
	C.set_fn_shim_data_channel_set_on_close(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_close")))
	C.set_fn_shim_data_channel_send(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_send")))
	C.set_fn_shim_data_channel_label(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_label")))
	C.set_fn_shim_data_channel_ready_state(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_ready_state")))
	C.set_fn_shim_data_channel_close(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_close")))
	C.set_fn_shim_data_channel_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_destroy")))

	// VideoTrackSource
	C.set_fn_shim_video_track_source_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_create")))
	C.set_fn_shim_video_track_source_push_frame(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_push_frame")))
	C.set_fn_shim_peer_connection_add_video_track_from_source(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_video_track_from_source")))
	C.set_fn_shim_video_track_source_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_destroy")))

	// AudioTrackSource
	C.set_fn_shim_audio_track_source_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_create")))
	C.set_fn_shim_audio_track_source_push_frame(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_push_frame")))
	C.set_fn_shim_peer_connection_add_audio_track_from_source(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_audio_track_from_source")))
	C.set_fn_shim_audio_track_source_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_destroy")))

	// RemoteTrack
	C.set_fn_shim_track_set_video_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_set_video_sink")))
	C.set_fn_shim_track_set_audio_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_set_audio_sink")))
	C.set_fn_shim_track_remove_video_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_remove_video_sink")))
	C.set_fn_shim_track_remove_audio_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_remove_audio_sink")))
	C.set_fn_shim_track_kind(unsafe.Pointer(mustDlsym(libHandle, "shim_track_kind")))
	C.set_fn_shim_track_id(unsafe.Pointer(mustDlsym(libHandle, "shim_track_id")))

	// ScalabilityMode
	C.set_fn_shim_rtp_sender_set_scalability_mode(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_scalability_mode")))
	C.set_fn_shim_rtp_sender_get_scalability_mode(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_scalability_mode")))

	// CodecCapabilities
	C.set_fn_shim_get_supported_video_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_get_supported_video_codecs")))
	C.set_fn_shim_get_supported_audio_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_get_supported_audio_codecs")))
	C.set_fn_shim_is_codec_supported(unsafe.Pointer(mustDlsym(libHandle, "shim_is_codec_supported")))

	// RTPSenderCodec
	C.set_fn_shim_rtp_sender_get_negotiated_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_negotiated_codecs")))
	C.set_fn_shim_rtp_sender_set_preferred_codec(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_preferred_codec")))

	// BandwidthEstimation
	C.set_fn_shim_peer_connection_set_on_bandwidth_estimate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_bandwidth_estimate")))
	C.set_fn_shim_peer_connection_get_bandwidth_estimate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_bandwidth_estimate")))

	// DeviceCapture
	C.set_fn_shim_enumerate_devices(unsafe.Pointer(mustDlsym(libHandle, "shim_enumerate_devices")))
	C.set_fn_shim_video_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_create")))
	C.set_fn_shim_video_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_start")))
	C.set_fn_shim_video_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_stop")))
	C.set_fn_shim_video_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_destroy")))
	C.set_fn_shim_audio_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_create")))
	C.set_fn_shim_audio_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_start")))
	C.set_fn_shim_audio_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_stop")))
	C.set_fn_shim_audio_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_destroy")))

	// ScreenCapture
	C.set_fn_shim_enumerate_screens(unsafe.Pointer(mustDlsym(libHandle, "shim_enumerate_screens")))
	C.set_fn_shim_screen_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_create")))
	C.set_fn_shim_screen_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_start")))
	C.set_fn_shim_screen_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_stop")))
	C.set_fn_shim_screen_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_destroy")))

	// Permissions
	C.set_fn_shim_check_camera_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_check_camera_permission")))
	C.set_fn_shim_check_microphone_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_check_microphone_permission")))
	C.set_fn_shim_request_camera_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_request_camera_permission")))
	C.set_fn_shim_request_microphone_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_request_microphone_permission")))

	// Assign Go wrapper functions
	// VideoEncoder
	shimVideoEncoderCreate = func(codec int32, configPtr uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_video_encoder_create(C.int32_t(codec), C.uintptr_t(configPtr), C.uintptr_t(errorOut)))
	}
	shimVideoEncoderEncode = func(encoder uintptr, yPlane uintptr, uPlane uintptr, vPlane uintptr, yStride int32, uStride int32, vStride int32, timestamp uint32, forceKeyframe int32, outData uintptr, dstBufferSize int32, outSize uintptr, outIsKeyframe uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_video_encoder_encode(C.uintptr_t(encoder), C.uintptr_t(yPlane), C.uintptr_t(uPlane), C.uintptr_t(vPlane), C.int32_t(yStride), C.int32_t(uStride), C.int32_t(vStride), C.uint32_t(timestamp), C.int32_t(forceKeyframe), C.uintptr_t(outData), C.int32_t(dstBufferSize), C.uintptr_t(outSize), C.uintptr_t(outIsKeyframe), C.uintptr_t(errorOut)))
	}
	shimVideoEncoderSetBitrate = func(encoder uintptr, bitrate uint32) int32 {
		return int32(C.call_shim_video_encoder_set_bitrate(C.uintptr_t(encoder), C.uint32_t(bitrate)))
	}
	shimVideoEncoderSetFramerate = func(encoder uintptr, framerate float32) int32 {
		return int32(C.call_shim_video_encoder_set_framerate(C.uintptr_t(encoder), C.float(framerate)))
	}
	shimVideoEncoderRequestKeyframe = func(encoder uintptr) int32 {
		return int32(C.call_shim_video_encoder_request_keyframe(C.uintptr_t(encoder)))
	}
	shimVideoEncoderDestroy = func(encoder uintptr) {
		C.call_shim_video_encoder_destroy(C.uintptr_t(encoder))
	}

	// VideoDecoder
	shimVideoDecoderCreate = func(codec int32, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_video_decoder_create(C.int32_t(codec), C.uintptr_t(errorOut)))
	}
	shimVideoDecoderDecode = func(decoder uintptr, data uintptr, size int32, timestamp uint32, isKeyframe int32, outY uintptr, outU uintptr, outV uintptr, outW uintptr, outH uintptr, outYStride uintptr, outUStride uintptr, outVStride uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_video_decoder_decode(C.uintptr_t(decoder), C.uintptr_t(data), C.int32_t(size), C.uint32_t(timestamp), C.int32_t(isKeyframe), C.uintptr_t(outY), C.uintptr_t(outU), C.uintptr_t(outV), C.uintptr_t(outW), C.uintptr_t(outH), C.uintptr_t(outYStride), C.uintptr_t(outUStride), C.uintptr_t(outVStride), C.uintptr_t(errorOut)))
	}
	shimVideoDecoderDestroy = func(decoder uintptr) {
		C.call_shim_video_decoder_destroy(C.uintptr_t(decoder))
	}

	// AudioEncoder
	shimAudioEncoderCreate = func(configPtr uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_audio_encoder_create(C.uintptr_t(configPtr), C.uintptr_t(errorOut)))
	}
	shimAudioEncoderEncode = func(encoder uintptr, samples uintptr, numSamples int32, outData uintptr, outSize uintptr) int32 {
		return int32(C.call_shim_audio_encoder_encode(C.uintptr_t(encoder), C.uintptr_t(samples), C.int32_t(numSamples), C.uintptr_t(outData), C.uintptr_t(outSize)))
	}
	shimAudioEncoderSetBitrate = func(encoder uintptr, bitrate uint32) int32 {
		return int32(C.call_shim_audio_encoder_set_bitrate(C.uintptr_t(encoder), C.uint32_t(bitrate)))
	}
	shimAudioEncoderDestroy = func(encoder uintptr) {
		C.call_shim_audio_encoder_destroy(C.uintptr_t(encoder))
	}

	// AudioDecoder
	shimAudioDecoderCreate = func(sampleRate int32, channels int32, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_audio_decoder_create(C.int32_t(sampleRate), C.int32_t(channels), C.uintptr_t(errorOut)))
	}
	shimAudioDecoderDecode = func(decoder uintptr, data uintptr, size int32, outSamples uintptr, outNumSamples uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_audio_decoder_decode(C.uintptr_t(decoder), C.uintptr_t(data), C.int32_t(size), C.uintptr_t(outSamples), C.uintptr_t(outNumSamples), C.uintptr_t(errorOut)))
	}
	shimAudioDecoderDestroy = func(decoder uintptr) {
		C.call_shim_audio_decoder_destroy(C.uintptr_t(decoder))
	}

	// Packetizer
	shimPacketizerCreate = func(configPtr uintptr) uintptr {
		return uintptr(C.call_shim_packetizer_create(C.uintptr_t(configPtr)))
	}
	shimPacketizerPacketize = func(packetizer uintptr, data uintptr, size int32, timestamp uint32, isKeyframe int32, dst uintptr, offsets uintptr, sizes uintptr, maxPackets int32, outCount uintptr) int32 {
		return int32(C.call_shim_packetizer_packetize(C.uintptr_t(packetizer), C.uintptr_t(data), C.int32_t(size), C.uint32_t(timestamp), C.int32_t(isKeyframe), C.uintptr_t(dst), C.uintptr_t(offsets), C.uintptr_t(sizes), C.int32_t(maxPackets), C.uintptr_t(outCount)))
	}
	shimPacketizerSeqNum = func(packetizer uintptr) uint16 {
		return uint16(C.call_shim_packetizer_sequence_number(C.uintptr_t(packetizer)))
	}
	shimPacketizerDestroy = func(packetizer uintptr) {
		C.call_shim_packetizer_destroy(C.uintptr_t(packetizer))
	}

	// Depacketizer
	shimDepacketizerCreate = func(codec int32) uintptr {
		return uintptr(C.call_shim_depacketizer_create(C.int32_t(codec)))
	}
	shimDepacketizerPush = func(depacketizer uintptr, data uintptr, size int32) int32 {
		return int32(C.call_shim_depacketizer_push(C.uintptr_t(depacketizer), C.uintptr_t(data), C.int32_t(size)))
	}
	shimDepacketizerPop = func(depacketizer uintptr, outData uintptr, outSize uintptr, outTimestamp uintptr, outIsKeyframe uintptr) int32 {
		return int32(C.call_shim_depacketizer_pop(C.uintptr_t(depacketizer), C.uintptr_t(outData), C.uintptr_t(outSize), C.uintptr_t(outTimestamp), C.uintptr_t(outIsKeyframe)))
	}
	shimDepacketizerDestroy = func(depacketizer uintptr) {
		C.call_shim_depacketizer_destroy(C.uintptr_t(depacketizer))
	}

	// Memory
	shimFreeBuffer = func(buffer uintptr) {
		C.call_shim_free_buffer(C.uintptr_t(buffer))
	}
	shimFreePackets = func(packets uintptr, sizes uintptr, count int32) {
		C.call_shim_free_packets(C.uintptr_t(packets), C.uintptr_t(sizes), C.int32_t(count))
	}

	// Version
	shimLibwebrtcVersion = func() uintptr {
		return uintptr(C.call_shim_libwebrtc_version())
	}
	shimVersion = func() uintptr {
		return uintptr(C.call_shim_version())
	}

	// PeerConnection
	shimPeerConnectionCreate = func(configPtr uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_create(C.uintptr_t(configPtr), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionDestroy = func(pc uintptr) {
		C.call_shim_peer_connection_destroy(C.uintptr_t(pc))
	}
	shimPeerConnectionSetOnICECandidate = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_ice_candidate(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnConnectionStateChange = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_connection_state_change(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnTrack = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_track(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnDataChannel = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_data_channel(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionCreateOffer = func(pc uintptr, sdpOut uintptr, sdpOutSize int32, outSdpLen uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_create_offer(C.uintptr_t(pc), C.uintptr_t(sdpOut), C.int32_t(sdpOutSize), C.uintptr_t(outSdpLen), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionCreateAnswer = func(pc uintptr, sdpOut uintptr, sdpOutSize int32, outSdpLen uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_create_answer(C.uintptr_t(pc), C.uintptr_t(sdpOut), C.int32_t(sdpOutSize), C.uintptr_t(outSdpLen), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionSetLocalDescription = func(pc uintptr, sdpType int32, sdp uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_set_local_description(C.uintptr_t(pc), C.int32_t(sdpType), C.uintptr_t(sdp), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionSetRemoteDescription = func(pc uintptr, sdpType int32, sdp uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_set_remote_description(C.uintptr_t(pc), C.int32_t(sdpType), C.uintptr_t(sdp), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionAddICECandidate = func(pc uintptr, candidate uintptr, sdpMid uintptr, sdpMLineIndex int32, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_add_ice_candidate(C.uintptr_t(pc), C.uintptr_t(candidate), C.uintptr_t(sdpMid), C.int32_t(sdpMLineIndex), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionSignalingState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_signaling_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionICEConnectionState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_ice_connection_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionICEGatheringState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_ice_gathering_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionConnectionState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_connection_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionAddTrack = func(pc uintptr, codec int32, trackID uintptr, streamID uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_track(C.uintptr_t(pc), C.int32_t(codec), C.uintptr_t(trackID), C.uintptr_t(streamID), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionRemoveTrack = func(pc uintptr, sender uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_peer_connection_remove_track(C.uintptr_t(pc), C.uintptr_t(sender), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionCreateDataChannel = func(pc uintptr, label uintptr, ordered int32, maxRetransmits int32, protocol uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_create_data_channel(C.uintptr_t(pc), C.uintptr_t(label), C.int32_t(ordered), C.int32_t(maxRetransmits), C.uintptr_t(protocol), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionClose = func(pc uintptr) {
		C.call_shim_peer_connection_close(C.uintptr_t(pc))
	}

	// PeerConnectionExtended
	shimPeerConnectionAddTransceiver = func(pc uintptr, kind int32, direction int32, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_transceiver(C.uintptr_t(pc), C.int32_t(kind), C.int32_t(direction), C.uintptr_t(errorOut)))
	}
	shimPeerConnectionGetSenders = func(pc uintptr, senders uintptr, maxSenders int32, outCount uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_senders(C.uintptr_t(pc), C.uintptr_t(senders), C.int32_t(maxSenders), C.uintptr_t(outCount)))
	}
	shimPeerConnectionGetReceivers = func(pc uintptr, receivers uintptr, maxReceivers int32, outCount uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_receivers(C.uintptr_t(pc), C.uintptr_t(receivers), C.int32_t(maxReceivers), C.uintptr_t(outCount)))
	}
	shimPeerConnectionGetTransceivers = func(pc uintptr, transceivers uintptr, maxTransceivers int32, outCount uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_transceivers(C.uintptr_t(pc), C.uintptr_t(transceivers), C.int32_t(maxTransceivers), C.uintptr_t(outCount)))
	}
	shimPeerConnectionRestartICE = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_restart_ice(C.uintptr_t(pc)))
	}
	shimPeerConnectionGetStats = func(pc uintptr, outStats uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_stats(C.uintptr_t(pc), C.uintptr_t(outStats)))
	}
	shimPeerConnectionSetOnSignalingStateChange = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_signaling_state_change(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnICEConnectionStateChange = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_ice_connection_state_change(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnICEGatheringStateChange = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_ice_gathering_state_change(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionSetOnNegotiationNeeded = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_negotiation_needed(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}

	// RTPSender
	shimRTPSenderSetBitrate = func(sender uintptr, bitrate uint32, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_bitrate(C.uintptr_t(sender), C.uint32_t(bitrate), C.uintptr_t(errorOut)))
	}
	shimRTPSenderReplaceTrack = func(sender uintptr, track uintptr) int32 {
		return int32(C.call_shim_rtp_sender_replace_track(C.uintptr_t(sender), C.uintptr_t(track)))
	}
	shimRTPSenderDestroy = func(sender uintptr) {
		C.call_shim_rtp_sender_destroy(C.uintptr_t(sender))
	}
	shimRTPSenderGetParameters = func(sender uintptr, outParams uintptr, encodings uintptr, maxEncodings int32) int32 {
		return int32(C.call_shim_rtp_sender_get_parameters(C.uintptr_t(sender), C.uintptr_t(outParams), C.uintptr_t(encodings), C.int32_t(maxEncodings)))
	}
	shimRTPSenderSetParameters = func(sender uintptr, params uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_parameters(C.uintptr_t(sender), C.uintptr_t(params), C.uintptr_t(errorOut)))
	}
	shimRTPSenderGetTrack = func(sender uintptr) uintptr {
		return uintptr(C.call_shim_rtp_sender_get_track(C.uintptr_t(sender)))
	}
	shimRTPSenderGetStats = func(sender uintptr, outStats uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_stats(C.uintptr_t(sender), C.uintptr_t(outStats)))
	}
	shimRTPSenderSetOnRTCPFeedback = func(sender uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_rtp_sender_set_on_rtcp_feedback(C.uintptr_t(sender), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimRTPSenderSetLayerActive = func(sender uintptr, rid uintptr, active int32, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_layer_active(C.uintptr_t(sender), C.uintptr_t(rid), C.int32_t(active), C.uintptr_t(errorOut)))
	}
	shimRTPSenderSetLayerBitrate = func(sender uintptr, rid uintptr, maxBitrate uint32, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_layer_bitrate(C.uintptr_t(sender), C.uintptr_t(rid), C.uint32_t(maxBitrate), C.uintptr_t(errorOut)))
	}
	shimRTPSenderGetActiveLayers = func(sender uintptr, outSpatial uintptr, outTemporal uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_active_layers(C.uintptr_t(sender), C.uintptr_t(outSpatial), C.uintptr_t(outTemporal)))
	}

	// RTPReceiver
	shimRTPReceiverGetTrack = func(receiver uintptr) uintptr {
		return uintptr(C.call_shim_rtp_receiver_get_track(C.uintptr_t(receiver)))
	}
	shimRTPReceiverGetStats = func(receiver uintptr, outStats uintptr) int32 {
		return int32(C.call_shim_rtp_receiver_get_stats(C.uintptr_t(receiver), C.uintptr_t(outStats)))
	}
	shimRTPReceiverSetJitterBufferMinDelay = func(receiver uintptr, minDelayMs int32) int32 {
		return int32(C.call_shim_rtp_receiver_set_jitter_buffer_min_delay(C.uintptr_t(receiver), C.int32_t(minDelayMs)))
	}

	// RTPTransceiver
	shimTransceiverGetDirection = func(transceiver uintptr) int32 {
		return int32(C.call_shim_transceiver_get_direction(C.uintptr_t(transceiver)))
	}
	shimTransceiverSetDirection = func(transceiver uintptr, direction int32, errorOut uintptr) int32 {
		return int32(C.call_shim_transceiver_set_direction(C.uintptr_t(transceiver), C.int32_t(direction), C.uintptr_t(errorOut)))
	}
	shimTransceiverGetCurrentDirection = func(transceiver uintptr) int32 {
		return int32(C.call_shim_transceiver_get_current_direction(C.uintptr_t(transceiver)))
	}
	shimTransceiverStop = func(transceiver uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_transceiver_stop(C.uintptr_t(transceiver), C.uintptr_t(errorOut)))
	}
	shimTransceiverMid = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_mid(C.uintptr_t(transceiver)))
	}
	shimTransceiverGetSender = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_get_sender(C.uintptr_t(transceiver)))
	}
	shimTransceiverGetReceiver = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_get_receiver(C.uintptr_t(transceiver)))
	}
	shimTransceiverSetCodecPreferences = func(transceiver uintptr, codecs uintptr, count int32, errorOut uintptr) int32 {
		return int32(C.call_shim_transceiver_set_codec_preferences(C.uintptr_t(transceiver), C.uintptr_t(codecs), C.int32_t(count), C.uintptr_t(errorOut)))
	}
	shimTransceiverGetCodecPreferences = func(transceiver uintptr, codecs uintptr, maxCodecs int32, outCount uintptr) int32 {
		return int32(C.call_shim_transceiver_get_codec_preferences(C.uintptr_t(transceiver), C.uintptr_t(codecs), C.int32_t(maxCodecs), C.uintptr_t(outCount)))
	}

	// DataChannel
	shimDataChannelSetOnMessage = func(dc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_data_channel_set_on_message(C.uintptr_t(dc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimDataChannelSetOnOpen = func(dc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_data_channel_set_on_open(C.uintptr_t(dc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimDataChannelSetOnClose = func(dc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_data_channel_set_on_close(C.uintptr_t(dc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimDataChannelSend = func(dc uintptr, data uintptr, size int32, isBinary int32, errorOut uintptr) int32 {
		return int32(C.call_shim_data_channel_send(C.uintptr_t(dc), C.uintptr_t(data), C.int32_t(size), C.int32_t(isBinary), C.uintptr_t(errorOut)))
	}
	shimDataChannelLabel = func(dc uintptr) uintptr {
		return uintptr(C.call_shim_data_channel_label(C.uintptr_t(dc)))
	}
	shimDataChannelReadyState = func(dc uintptr) int32 {
		return int32(C.call_shim_data_channel_ready_state(C.uintptr_t(dc)))
	}
	shimDataChannelClose = func(dc uintptr) {
		C.call_shim_data_channel_close(C.uintptr_t(dc))
	}
	shimDataChannelDestroy = func(dc uintptr) {
		C.call_shim_data_channel_destroy(C.uintptr_t(dc))
	}

	// VideoTrackSource
	shimVideoTrackSourceCreate = func(pc uintptr, width int32, height int32) uintptr {
		return uintptr(C.call_shim_video_track_source_create(C.uintptr_t(pc), C.int32_t(width), C.int32_t(height)))
	}
	shimVideoTrackSourcePushFrame = func(source uintptr, yPlane uintptr, uPlane uintptr, vPlane uintptr, yStride int32, uStride int32, vStride int32, timestampUs int64) int32 {
		return int32(C.call_shim_video_track_source_push_frame(C.uintptr_t(source), C.uintptr_t(yPlane), C.uintptr_t(uPlane), C.uintptr_t(vPlane), C.int32_t(yStride), C.int32_t(uStride), C.int32_t(vStride), C.int64_t(timestampUs)))
	}
	shimPeerConnectionAddVideoTrackFromSource = func(pc uintptr, source uintptr, trackID uintptr, streamID uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_video_track_from_source(C.uintptr_t(pc), C.uintptr_t(source), C.uintptr_t(trackID), C.uintptr_t(streamID), C.uintptr_t(errorOut)))
	}
	shimVideoTrackSourceDestroy = func(source uintptr) {
		C.call_shim_video_track_source_destroy(C.uintptr_t(source))
	}

	// AudioTrackSource
	shimAudioTrackSourceCreate = func(pc uintptr, sampleRate int32, channels int32) uintptr {
		return uintptr(C.call_shim_audio_track_source_create(C.uintptr_t(pc), C.int32_t(sampleRate), C.int32_t(channels)))
	}
	shimAudioTrackSourcePushFrame = func(source uintptr, samples uintptr, numSamples int32, timestampUs int64) int32 {
		return int32(C.call_shim_audio_track_source_push_frame(C.uintptr_t(source), C.uintptr_t(samples), C.int32_t(numSamples), C.int64_t(timestampUs)))
	}
	shimPeerConnectionAddAudioTrackFromSource = func(pc uintptr, source uintptr, trackID uintptr, streamID uintptr, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_audio_track_from_source(C.uintptr_t(pc), C.uintptr_t(source), C.uintptr_t(trackID), C.uintptr_t(streamID), C.uintptr_t(errorOut)))
	}
	shimAudioTrackSourceDestroy = func(source uintptr) {
		C.call_shim_audio_track_source_destroy(C.uintptr_t(source))
	}

	// RemoteTrack
	shimTrackSetVideoSink = func(track uintptr, callback uintptr, ctx uintptr) int32 {
		return int32(C.call_shim_track_set_video_sink(C.uintptr_t(track), C.uintptr_t(callback), C.uintptr_t(ctx)))
	}
	shimTrackSetAudioSink = func(track uintptr, callback uintptr, ctx uintptr) int32 {
		return int32(C.call_shim_track_set_audio_sink(C.uintptr_t(track), C.uintptr_t(callback), C.uintptr_t(ctx)))
	}
	shimTrackRemoveVideoSink = func(track uintptr) {
		C.call_shim_track_remove_video_sink(C.uintptr_t(track))
	}
	shimTrackRemoveAudioSink = func(track uintptr) {
		C.call_shim_track_remove_audio_sink(C.uintptr_t(track))
	}
	shimTrackKind = func(track uintptr) uintptr {
		return uintptr(C.call_shim_track_kind(C.uintptr_t(track)))
	}
	shimTrackID = func(track uintptr) uintptr {
		return uintptr(C.call_shim_track_id(C.uintptr_t(track)))
	}

	// ScalabilityMode
	shimRTPSenderSetScalabilityMode = func(sender uintptr, mode uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_scalability_mode(C.uintptr_t(sender), C.uintptr_t(mode), C.uintptr_t(errorOut)))
	}
	shimRTPSenderGetScalabilityMode = func(sender uintptr, modeOut uintptr, modeOutSize int32) int32 {
		return int32(C.call_shim_rtp_sender_get_scalability_mode(C.uintptr_t(sender), C.uintptr_t(modeOut), C.int32_t(modeOutSize)))
	}

	// CodecCapabilities
	shimGetSupportedVideoCodecs = func(codecs uintptr, maxCodecs int32, outCount uintptr) int32 {
		return int32(C.call_shim_get_supported_video_codecs(C.uintptr_t(codecs), C.int32_t(maxCodecs), C.uintptr_t(outCount)))
	}
	shimGetSupportedAudioCodecs = func(codecs uintptr, maxCodecs int32, outCount uintptr) int32 {
		return int32(C.call_shim_get_supported_audio_codecs(C.uintptr_t(codecs), C.int32_t(maxCodecs), C.uintptr_t(outCount)))
	}
	shimIsCodecSupported = func(mimeType uintptr) int32 {
		return int32(C.call_shim_is_codec_supported(C.uintptr_t(mimeType)))
	}

	// RTPSenderCodec
	shimRTPSenderGetNegotiatedCodecs = func(sender uintptr, codecs uintptr, maxCodecs int32, outCount uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_negotiated_codecs(C.uintptr_t(sender), C.uintptr_t(codecs), C.int32_t(maxCodecs), C.uintptr_t(outCount)))
	}
	shimRTPSenderSetPreferredCodec = func(sender uintptr, mimeType uintptr, payloadType int32, errorOut uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_preferred_codec(C.uintptr_t(sender), C.uintptr_t(mimeType), C.int32_t(payloadType), C.uintptr_t(errorOut)))
	}

	// BandwidthEstimation
	shimPeerConnectionSetOnBandwidthEstimate = func(pc uintptr, callback uintptr, ctx uintptr) {
		C.call_shim_peer_connection_set_on_bandwidth_estimate(C.uintptr_t(pc), C.uintptr_t(callback), C.uintptr_t(ctx))
	}
	shimPeerConnectionGetBandwidthEstimate = func(pc uintptr, outEstimate uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_bandwidth_estimate(C.uintptr_t(pc), C.uintptr_t(outEstimate)))
	}

	// DeviceCapture
	shimEnumerateDevices = func(devices uintptr, maxDevices int32, outCount uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_enumerate_devices(C.uintptr_t(devices), C.int32_t(maxDevices), C.uintptr_t(outCount), C.uintptr_t(errorOut)))
	}
	shimVideoCaptureCreate = func(deviceID uintptr, width int32, height int32, fps int32, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_video_capture_create(C.uintptr_t(deviceID), C.int32_t(width), C.int32_t(height), C.int32_t(fps), C.uintptr_t(errorOut)))
	}
	shimVideoCaptureStart = func(capturePtr uintptr, callback uintptr, ctx uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_video_capture_start(C.uintptr_t(capturePtr), C.uintptr_t(callback), C.uintptr_t(ctx), C.uintptr_t(errorOut)))
	}
	shimVideoCaptureStop = func(capturePtr uintptr) {
		C.call_shim_video_capture_stop(C.uintptr_t(capturePtr))
	}
	shimVideoCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_video_capture_destroy(C.uintptr_t(capturePtr))
	}
	shimAudioCaptureCreate = func(deviceID uintptr, sampleRate int32, channels int32, errorOut uintptr) uintptr {
		return uintptr(C.call_shim_audio_capture_create(C.uintptr_t(deviceID), C.int32_t(sampleRate), C.int32_t(channels), C.uintptr_t(errorOut)))
	}
	shimAudioCaptureStart = func(capturePtr uintptr, callback uintptr, ctx uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_audio_capture_start(C.uintptr_t(capturePtr), C.uintptr_t(callback), C.uintptr_t(ctx), C.uintptr_t(errorOut)))
	}
	shimAudioCaptureStop = func(capturePtr uintptr) {
		C.call_shim_audio_capture_stop(C.uintptr_t(capturePtr))
	}
	shimAudioCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_audio_capture_destroy(C.uintptr_t(capturePtr))
	}

	// ScreenCapture
	shimEnumerateScreens = func(screens uintptr, maxScreens int32, outCount uintptr, errorOut uintptr) int32 {
		return int32(C.call_shim_enumerate_screens(C.uintptr_t(screens), C.int32_t(maxScreens), C.uintptr_t(outCount), C.uintptr_t(errorOut)))
	}
	shimScreenCaptureCreate = func(id int64, isWindow int32, fps int32) uintptr {
		return uintptr(C.call_shim_screen_capture_create(C.int64_t(id), C.int32_t(isWindow), C.int32_t(fps)))
	}
	shimScreenCaptureStart = func(capturePtr uintptr, callback uintptr, ctx uintptr) int32 {
		return int32(C.call_shim_screen_capture_start(C.uintptr_t(capturePtr), C.uintptr_t(callback), C.uintptr_t(ctx)))
	}
	shimScreenCaptureStop = func(capturePtr uintptr) {
		C.call_shim_screen_capture_stop(C.uintptr_t(capturePtr))
	}
	shimScreenCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_screen_capture_destroy(C.uintptr_t(capturePtr))
	}

	// Permissions
	shimCheckCameraPermission = func() int32 {
		return int32(C.call_shim_check_camera_permission())
	}
	shimCheckMicrophonePermission = func() int32 {
		return int32(C.call_shim_check_microphone_permission())
	}
	shimRequestCameraPermission = func() int32 {
		return int32(C.call_shim_request_camera_permission())
	}
	shimRequestMicrophonePermission = func() int32 {
		return int32(C.call_shim_request_microphone_permission())
	}

	return nil
}

func mustDlsym(handle uintptr, name string) uintptr {
	sym, err := dlsymLibrary(handle, name)
	if err != nil {
		panic(err)
	}
	return sym
}
