// Code generated by go generate; DO NOT EDIT.

package ffi

// Function pointers - populated by registerFunctions()
// NOTE: All int/uint types are explicitly sized to match C ABI
var (
	// VideoEncoder
	shimVideoEncoderCreate          func(params uintptr) uintptr
	shimVideoEncoderEncode          func(encoder uintptr, params uintptr) int32
	shimVideoEncoderSetBitrate      func(params uintptr) int32
	shimVideoEncoderSetFramerate    func(params uintptr) int32
	shimVideoEncoderRequestKeyframe func(encoder uintptr) int32
	shimVideoEncoderDestroy         func(encoder uintptr)

	// VideoDecoder
	shimVideoDecoderCreate  func(params uintptr) uintptr
	shimVideoDecoderDecode  func(decoder uintptr, params uintptr) int32
	shimVideoDecoderDestroy func(decoder uintptr)

	// AudioEncoder
	shimAudioEncoderCreate     func(params uintptr) uintptr
	shimAudioEncoderEncode     func(encoder uintptr, params uintptr) int32
	shimAudioEncoderSetBitrate func(params uintptr) int32
	shimAudioEncoderDestroy    func(encoder uintptr)

	// AudioDecoder
	shimAudioDecoderCreate  func(params uintptr) uintptr
	shimAudioDecoderDecode  func(decoder uintptr, params uintptr) int32
	shimAudioDecoderDestroy func(decoder uintptr)

	// Packetizer
	shimPacketizerCreate    func(configPtr uintptr) uintptr
	shimPacketizerPacketize func(params uintptr) int32
	shimPacketizerSeqNum    func(packetizer uintptr) uint16
	shimPacketizerDestroy   func(packetizer uintptr)

	// Depacketizer
	shimDepacketizerCreate  func(codec int32) uintptr
	shimDepacketizerPush    func(params uintptr) int32
	shimDepacketizerPop     func(params uintptr) int32
	shimDepacketizerDestroy func(depacketizer uintptr)

	// Memory
	shimFreeBuffer  func(buffer uintptr)
	shimFreePackets func(packets uintptr, sizes uintptr, count int32)

	// Version
	shimLibwebrtcVersion func() uintptr
	shimVersion          func() uintptr

	// PeerConnection
	shimPeerConnectionCreate                     func(params uintptr) uintptr
	shimPeerConnectionDestroy                    func(pc uintptr)
	shimPeerConnectionSetOnICECandidate          func(params uintptr)
	shimPeerConnectionSetOnConnectionStateChange func(params uintptr)
	shimPeerConnectionSetOnTrack                 func(params uintptr)
	shimPeerConnectionSetOnDataChannel           func(params uintptr)
	shimPeerConnectionCreateOffer                func(params uintptr) int32
	shimPeerConnectionCreateAnswer               func(params uintptr) int32
	shimPeerConnectionSetLocalDescription        func(params uintptr) int32
	shimPeerConnectionSetRemoteDescription       func(params uintptr) int32
	shimPeerConnectionAddICECandidate            func(params uintptr) int32
	shimPeerConnectionSignalingState             func(pc uintptr) int32
	shimPeerConnectionICEConnectionState         func(pc uintptr) int32
	shimPeerConnectionICEGatheringState          func(pc uintptr) int32
	shimPeerConnectionConnectionState            func(pc uintptr) int32
	shimPeerConnectionAddTrack                   func(params uintptr) uintptr
	shimPeerConnectionRemoveTrack                func(params uintptr) int32
	shimPeerConnectionCreateDataChannel          func(params uintptr) uintptr
	shimPeerConnectionClose                      func(pc uintptr)

	// PeerConnectionExtended
	shimPeerConnectionAddTransceiver                func(params uintptr) uintptr
	shimPeerConnectionGetSenders                    func(params uintptr) int32
	shimPeerConnectionGetReceivers                  func(params uintptr) int32
	shimPeerConnectionGetTransceivers               func(params uintptr) int32
	shimPeerConnectionRestartICE                    func(pc uintptr) int32
	shimPeerConnectionGetStats                      func(params uintptr) int32
	shimPeerConnectionSetOnSignalingStateChange     func(params uintptr)
	shimPeerConnectionSetOnICEConnectionStateChange func(params uintptr)
	shimPeerConnectionSetOnICEGatheringStateChange  func(params uintptr)
	shimPeerConnectionSetOnNegotiationNeeded        func(params uintptr)

	// RTPSender
	shimRTPSenderSetBitrate        func(params uintptr) int32
	shimRTPSenderReplaceTrack      func(params uintptr) int32
	shimRTPSenderDestroy           func(sender uintptr)
	shimRTPSenderGetParameters     func(params uintptr) int32
	shimRTPSenderSetParameters     func(params uintptr) int32
	shimRTPSenderGetTrack          func(sender uintptr) uintptr
	shimRTPSenderGetStats          func(params uintptr) int32
	shimRTPSenderSetOnRTCPFeedback func(params uintptr)
	shimRTPSenderSetLayerActive    func(params uintptr) int32
	shimRTPSenderSetLayerBitrate   func(params uintptr) int32
	shimRTPSenderGetActiveLayers   func(params uintptr) int32

	// RTPReceiver
	shimRTPReceiverGetTrack                func(receiver uintptr) uintptr
	shimRTPReceiverGetStats                func(params uintptr) int32
	shimRTPReceiverSetJitterBufferMinDelay func(params uintptr) int32

	// RTPTransceiver
	shimTransceiverGetDirection        func(transceiver uintptr) int32
	shimTransceiverSetDirection        func(params uintptr) int32
	shimTransceiverGetCurrentDirection func(transceiver uintptr) int32
	shimTransceiverStop                func(params uintptr) int32
	shimTransceiverMid                 func(transceiver uintptr) uintptr
	shimTransceiverGetSender           func(transceiver uintptr) uintptr
	shimTransceiverGetReceiver         func(transceiver uintptr) uintptr
	shimTransceiverSetCodecPreferences func(params uintptr) int32
	shimTransceiverGetCodecPreferences func(params uintptr) int32

	// DataChannel
	shimDataChannelSetOnMessage func(params uintptr)
	shimDataChannelSetOnOpen    func(params uintptr)
	shimDataChannelSetOnClose   func(params uintptr)
	shimDataChannelSend         func(params uintptr) int32
	shimDataChannelLabel        func(dc uintptr) uintptr
	shimDataChannelReadyState   func(dc uintptr) int32
	shimDataChannelClose        func(dc uintptr)
	shimDataChannelDestroy      func(dc uintptr)

	// VideoTrackSource
	shimVideoTrackSourceCreate                func(params uintptr) uintptr
	shimVideoTrackSourcePushFrame             func(params uintptr) int32
	shimPeerConnectionAddVideoTrackFromSource func(params uintptr) uintptr
	shimVideoTrackSourceDestroy               func(source uintptr)

	// AudioTrackSource
	shimAudioTrackSourceCreate                func(params uintptr) uintptr
	shimAudioTrackSourcePushFrame             func(params uintptr) int32
	shimPeerConnectionAddAudioTrackFromSource func(params uintptr) uintptr
	shimAudioTrackSourceDestroy               func(source uintptr)

	// RemoteTrack
	shimTrackSetVideoSink    func(params uintptr) int32
	shimTrackSetAudioSink    func(params uintptr) int32
	shimTrackRemoveVideoSink func(track uintptr)
	shimTrackRemoveAudioSink func(track uintptr)
	shimTrackKind            func(track uintptr) uintptr
	shimTrackID              func(track uintptr) uintptr

	// ScalabilityMode
	shimRTPSenderSetScalabilityMode func(params uintptr) int32
	shimRTPSenderGetScalabilityMode func(params uintptr) int32

	// CodecCapabilities
	shimGetSupportedVideoCodecs func(params uintptr) int32
	shimGetSupportedAudioCodecs func(params uintptr) int32
	shimIsCodecSupported        func(mimeType uintptr) int32

	// RTPSenderCodec
	shimRTPSenderGetNegotiatedCodecs func(params uintptr) int32
	shimRTPSenderSetPreferredCodec   func(params uintptr) int32

	// BandwidthEstimation
	shimPeerConnectionSetOnBandwidthEstimate func(params uintptr)
	shimPeerConnectionGetBandwidthEstimate   func(params uintptr) int32

	// DeviceCapture
	shimEnumerateDevices    func(params uintptr) int32
	shimVideoCaptureCreate  func(params uintptr) uintptr
	shimVideoCaptureStart   func(params uintptr) int32
	shimVideoCaptureStop    func(capturePtr uintptr)
	shimVideoCaptureDestroy func(capturePtr uintptr)
	shimAudioCaptureCreate  func(params uintptr) uintptr
	shimAudioCaptureStart   func(params uintptr) int32
	shimAudioCaptureStop    func(capturePtr uintptr)
	shimAudioCaptureDestroy func(capturePtr uintptr)

	// ScreenCapture
	shimEnumerateScreens     func(params uintptr) int32
	shimScreenCaptureCreate  func(params uintptr) uintptr
	shimScreenCaptureStart   func(params uintptr) int32
	shimScreenCaptureStop    func(capturePtr uintptr)
	shimScreenCaptureDestroy func(capturePtr uintptr)

	// Permissions
	shimCheckCameraPermission       func() int32
	shimCheckMicrophonePermission   func() int32
	shimRequestCameraPermission     func() int32
	shimRequestMicrophonePermission func() int32
)
