// Code generated by go generate; DO NOT EDIT.

//go:build ffigo_cgo

package ffi

/*
#include <stdint.h>

// Function pointer storage
static void* fn_shim_video_encoder_create;
static void* fn_shim_video_encoder_encode;
static void* fn_shim_video_encoder_set_bitrate;
static void* fn_shim_video_encoder_set_framerate;
static void* fn_shim_video_encoder_request_keyframe;
static void* fn_shim_video_encoder_destroy;
static void* fn_shim_video_decoder_create;
static void* fn_shim_video_decoder_decode;
static void* fn_shim_video_decoder_destroy;
static void* fn_shim_audio_encoder_create;
static void* fn_shim_audio_encoder_encode;
static void* fn_shim_audio_encoder_set_bitrate;
static void* fn_shim_audio_encoder_destroy;
static void* fn_shim_audio_decoder_create;
static void* fn_shim_audio_decoder_decode;
static void* fn_shim_audio_decoder_destroy;
static void* fn_shim_packetizer_create;
static void* fn_shim_packetizer_packetize;
static void* fn_shim_packetizer_sequence_number;
static void* fn_shim_packetizer_destroy;
static void* fn_shim_depacketizer_create;
static void* fn_shim_depacketizer_push;
static void* fn_shim_depacketizer_pop;
static void* fn_shim_depacketizer_destroy;
static void* fn_shim_free_buffer;
static void* fn_shim_free_packets;
static void* fn_shim_libwebrtc_version;
static void* fn_shim_version;
static void* fn_shim_peer_connection_create;
static void* fn_shim_peer_connection_destroy;
static void* fn_shim_peer_connection_set_on_ice_candidate;
static void* fn_shim_peer_connection_set_on_connection_state_change;
static void* fn_shim_peer_connection_set_on_track;
static void* fn_shim_peer_connection_set_on_data_channel;
static void* fn_shim_peer_connection_create_offer;
static void* fn_shim_peer_connection_create_answer;
static void* fn_shim_peer_connection_set_local_description;
static void* fn_shim_peer_connection_set_remote_description;
static void* fn_shim_peer_connection_add_ice_candidate;
static void* fn_shim_peer_connection_signaling_state;
static void* fn_shim_peer_connection_ice_connection_state;
static void* fn_shim_peer_connection_ice_gathering_state;
static void* fn_shim_peer_connection_connection_state;
static void* fn_shim_peer_connection_add_track;
static void* fn_shim_peer_connection_remove_track;
static void* fn_shim_peer_connection_create_data_channel;
static void* fn_shim_peer_connection_close;
static void* fn_shim_rtp_sender_set_bitrate;
static void* fn_shim_rtp_sender_replace_track;
static void* fn_shim_rtp_sender_destroy;
static void* fn_shim_data_channel_set_on_message;
static void* fn_shim_data_channel_set_on_open;
static void* fn_shim_data_channel_set_on_close;
static void* fn_shim_data_channel_send;
static void* fn_shim_data_channel_label;
static void* fn_shim_data_channel_ready_state;
static void* fn_shim_data_channel_close;
static void* fn_shim_data_channel_destroy;
static void* fn_shim_video_track_source_create;
static void* fn_shim_video_track_source_push_frame;
static void* fn_shim_peer_connection_add_video_track_from_source;
static void* fn_shim_video_track_source_destroy;
static void* fn_shim_audio_track_source_create;
static void* fn_shim_audio_track_source_push_frame;
static void* fn_shim_peer_connection_add_audio_track_from_source;
static void* fn_shim_audio_track_source_destroy;
static void* fn_shim_track_set_video_sink;
static void* fn_shim_track_set_audio_sink;
static void* fn_shim_track_remove_video_sink;
static void* fn_shim_track_remove_audio_sink;
static void* fn_shim_track_kind;
static void* fn_shim_track_id;
static void* fn_shim_rtp_sender_get_parameters;
static void* fn_shim_rtp_sender_set_parameters;
static void* fn_shim_rtp_sender_get_track;
static void* fn_shim_rtp_sender_get_stats;
static void* fn_shim_rtp_sender_set_on_rtcp_feedback;
static void* fn_shim_rtp_sender_set_layer_active;
static void* fn_shim_rtp_sender_set_layer_bitrate;
static void* fn_shim_rtp_sender_get_active_layers;
static void* fn_shim_rtp_receiver_get_track;
static void* fn_shim_rtp_receiver_get_stats;
static void* fn_shim_rtp_receiver_set_jitter_buffer_min_delay;
static void* fn_shim_transceiver_get_direction;
static void* fn_shim_transceiver_set_direction;
static void* fn_shim_transceiver_get_current_direction;
static void* fn_shim_transceiver_stop;
static void* fn_shim_transceiver_mid;
static void* fn_shim_transceiver_get_sender;
static void* fn_shim_transceiver_get_receiver;
static void* fn_shim_transceiver_set_codec_preferences;
static void* fn_shim_transceiver_get_codec_preferences;
static void* fn_shim_peer_connection_add_transceiver;
static void* fn_shim_peer_connection_get_senders;
static void* fn_shim_peer_connection_get_receivers;
static void* fn_shim_peer_connection_get_transceivers;
static void* fn_shim_peer_connection_restart_ice;
static void* fn_shim_peer_connection_get_stats;
static void* fn_shim_peer_connection_set_on_signaling_state_change;
static void* fn_shim_peer_connection_set_on_ice_connection_state_change;
static void* fn_shim_peer_connection_set_on_ice_gathering_state_change;
static void* fn_shim_peer_connection_set_on_negotiation_needed;
static void* fn_shim_rtp_sender_set_scalability_mode;
static void* fn_shim_rtp_sender_get_scalability_mode;
static void* fn_shim_get_supported_video_codecs;
static void* fn_shim_get_supported_audio_codecs;
static void* fn_shim_is_codec_supported;
static void* fn_shim_rtp_sender_get_negotiated_codecs;
static void* fn_shim_rtp_sender_set_preferred_codec;
static void* fn_shim_peer_connection_set_on_bandwidth_estimate;
static void* fn_shim_peer_connection_get_bandwidth_estimate;
static void* fn_shim_enumerate_devices;
static void* fn_shim_video_capture_create;
static void* fn_shim_video_capture_start;
static void* fn_shim_video_capture_stop;
static void* fn_shim_video_capture_destroy;
static void* fn_shim_audio_capture_create;
static void* fn_shim_audio_capture_start;
static void* fn_shim_audio_capture_stop;
static void* fn_shim_audio_capture_destroy;
static void* fn_shim_enumerate_screens;
static void* fn_shim_screen_capture_create;
static void* fn_shim_screen_capture_start;
static void* fn_shim_screen_capture_stop;
static void* fn_shim_screen_capture_destroy;
static void* fn_shim_check_camera_permission;
static void* fn_shim_check_microphone_permission;
static void* fn_shim_request_camera_permission;
static void* fn_shim_request_microphone_permission;

// Setters (called from Go after dlsym)
void set_fn_shim_video_encoder_create(void* fn) { fn_shim_video_encoder_create = fn; }
void set_fn_shim_video_encoder_encode(void* fn) { fn_shim_video_encoder_encode = fn; }
void set_fn_shim_video_encoder_set_bitrate(void* fn) { fn_shim_video_encoder_set_bitrate = fn; }
void set_fn_shim_video_encoder_set_framerate(void* fn) { fn_shim_video_encoder_set_framerate = fn; }
void set_fn_shim_video_encoder_request_keyframe(void* fn) { fn_shim_video_encoder_request_keyframe = fn; }
void set_fn_shim_video_encoder_destroy(void* fn) { fn_shim_video_encoder_destroy = fn; }
void set_fn_shim_video_decoder_create(void* fn) { fn_shim_video_decoder_create = fn; }
void set_fn_shim_video_decoder_decode(void* fn) { fn_shim_video_decoder_decode = fn; }
void set_fn_shim_video_decoder_destroy(void* fn) { fn_shim_video_decoder_destroy = fn; }
void set_fn_shim_audio_encoder_create(void* fn) { fn_shim_audio_encoder_create = fn; }
void set_fn_shim_audio_encoder_encode(void* fn) { fn_shim_audio_encoder_encode = fn; }
void set_fn_shim_audio_encoder_set_bitrate(void* fn) { fn_shim_audio_encoder_set_bitrate = fn; }
void set_fn_shim_audio_encoder_destroy(void* fn) { fn_shim_audio_encoder_destroy = fn; }
void set_fn_shim_audio_decoder_create(void* fn) { fn_shim_audio_decoder_create = fn; }
void set_fn_shim_audio_decoder_decode(void* fn) { fn_shim_audio_decoder_decode = fn; }
void set_fn_shim_audio_decoder_destroy(void* fn) { fn_shim_audio_decoder_destroy = fn; }
void set_fn_shim_packetizer_create(void* fn) { fn_shim_packetizer_create = fn; }
void set_fn_shim_packetizer_packetize(void* fn) { fn_shim_packetizer_packetize = fn; }
void set_fn_shim_packetizer_sequence_number(void* fn) { fn_shim_packetizer_sequence_number = fn; }
void set_fn_shim_packetizer_destroy(void* fn) { fn_shim_packetizer_destroy = fn; }
void set_fn_shim_depacketizer_create(void* fn) { fn_shim_depacketizer_create = fn; }
void set_fn_shim_depacketizer_push(void* fn) { fn_shim_depacketizer_push = fn; }
void set_fn_shim_depacketizer_pop(void* fn) { fn_shim_depacketizer_pop = fn; }
void set_fn_shim_depacketizer_destroy(void* fn) { fn_shim_depacketizer_destroy = fn; }
void set_fn_shim_free_buffer(void* fn) { fn_shim_free_buffer = fn; }
void set_fn_shim_free_packets(void* fn) { fn_shim_free_packets = fn; }
void set_fn_shim_libwebrtc_version(void* fn) { fn_shim_libwebrtc_version = fn; }
void set_fn_shim_version(void* fn) { fn_shim_version = fn; }
void set_fn_shim_peer_connection_create(void* fn) { fn_shim_peer_connection_create = fn; }
void set_fn_shim_peer_connection_destroy(void* fn) { fn_shim_peer_connection_destroy = fn; }
void set_fn_shim_peer_connection_set_on_ice_candidate(void* fn) { fn_shim_peer_connection_set_on_ice_candidate = fn; }
void set_fn_shim_peer_connection_set_on_connection_state_change(void* fn) { fn_shim_peer_connection_set_on_connection_state_change = fn; }
void set_fn_shim_peer_connection_set_on_track(void* fn) { fn_shim_peer_connection_set_on_track = fn; }
void set_fn_shim_peer_connection_set_on_data_channel(void* fn) { fn_shim_peer_connection_set_on_data_channel = fn; }
void set_fn_shim_peer_connection_create_offer(void* fn) { fn_shim_peer_connection_create_offer = fn; }
void set_fn_shim_peer_connection_create_answer(void* fn) { fn_shim_peer_connection_create_answer = fn; }
void set_fn_shim_peer_connection_set_local_description(void* fn) { fn_shim_peer_connection_set_local_description = fn; }
void set_fn_shim_peer_connection_set_remote_description(void* fn) { fn_shim_peer_connection_set_remote_description = fn; }
void set_fn_shim_peer_connection_add_ice_candidate(void* fn) { fn_shim_peer_connection_add_ice_candidate = fn; }
void set_fn_shim_peer_connection_signaling_state(void* fn) { fn_shim_peer_connection_signaling_state = fn; }
void set_fn_shim_peer_connection_ice_connection_state(void* fn) { fn_shim_peer_connection_ice_connection_state = fn; }
void set_fn_shim_peer_connection_ice_gathering_state(void* fn) { fn_shim_peer_connection_ice_gathering_state = fn; }
void set_fn_shim_peer_connection_connection_state(void* fn) { fn_shim_peer_connection_connection_state = fn; }
void set_fn_shim_peer_connection_add_track(void* fn) { fn_shim_peer_connection_add_track = fn; }
void set_fn_shim_peer_connection_remove_track(void* fn) { fn_shim_peer_connection_remove_track = fn; }
void set_fn_shim_peer_connection_create_data_channel(void* fn) { fn_shim_peer_connection_create_data_channel = fn; }
void set_fn_shim_peer_connection_close(void* fn) { fn_shim_peer_connection_close = fn; }
void set_fn_shim_rtp_sender_set_bitrate(void* fn) { fn_shim_rtp_sender_set_bitrate = fn; }
void set_fn_shim_rtp_sender_replace_track(void* fn) { fn_shim_rtp_sender_replace_track = fn; }
void set_fn_shim_rtp_sender_destroy(void* fn) { fn_shim_rtp_sender_destroy = fn; }
void set_fn_shim_data_channel_set_on_message(void* fn) { fn_shim_data_channel_set_on_message = fn; }
void set_fn_shim_data_channel_set_on_open(void* fn) { fn_shim_data_channel_set_on_open = fn; }
void set_fn_shim_data_channel_set_on_close(void* fn) { fn_shim_data_channel_set_on_close = fn; }
void set_fn_shim_data_channel_send(void* fn) { fn_shim_data_channel_send = fn; }
void set_fn_shim_data_channel_label(void* fn) { fn_shim_data_channel_label = fn; }
void set_fn_shim_data_channel_ready_state(void* fn) { fn_shim_data_channel_ready_state = fn; }
void set_fn_shim_data_channel_close(void* fn) { fn_shim_data_channel_close = fn; }
void set_fn_shim_data_channel_destroy(void* fn) { fn_shim_data_channel_destroy = fn; }
void set_fn_shim_video_track_source_create(void* fn) { fn_shim_video_track_source_create = fn; }
void set_fn_shim_video_track_source_push_frame(void* fn) { fn_shim_video_track_source_push_frame = fn; }
void set_fn_shim_peer_connection_add_video_track_from_source(void* fn) { fn_shim_peer_connection_add_video_track_from_source = fn; }
void set_fn_shim_video_track_source_destroy(void* fn) { fn_shim_video_track_source_destroy = fn; }
void set_fn_shim_audio_track_source_create(void* fn) { fn_shim_audio_track_source_create = fn; }
void set_fn_shim_audio_track_source_push_frame(void* fn) { fn_shim_audio_track_source_push_frame = fn; }
void set_fn_shim_peer_connection_add_audio_track_from_source(void* fn) { fn_shim_peer_connection_add_audio_track_from_source = fn; }
void set_fn_shim_audio_track_source_destroy(void* fn) { fn_shim_audio_track_source_destroy = fn; }
void set_fn_shim_track_set_video_sink(void* fn) { fn_shim_track_set_video_sink = fn; }
void set_fn_shim_track_set_audio_sink(void* fn) { fn_shim_track_set_audio_sink = fn; }
void set_fn_shim_track_remove_video_sink(void* fn) { fn_shim_track_remove_video_sink = fn; }
void set_fn_shim_track_remove_audio_sink(void* fn) { fn_shim_track_remove_audio_sink = fn; }
void set_fn_shim_track_kind(void* fn) { fn_shim_track_kind = fn; }
void set_fn_shim_track_id(void* fn) { fn_shim_track_id = fn; }
void set_fn_shim_rtp_sender_get_parameters(void* fn) { fn_shim_rtp_sender_get_parameters = fn; }
void set_fn_shim_rtp_sender_set_parameters(void* fn) { fn_shim_rtp_sender_set_parameters = fn; }
void set_fn_shim_rtp_sender_get_track(void* fn) { fn_shim_rtp_sender_get_track = fn; }
void set_fn_shim_rtp_sender_get_stats(void* fn) { fn_shim_rtp_sender_get_stats = fn; }
void set_fn_shim_rtp_sender_set_on_rtcp_feedback(void* fn) { fn_shim_rtp_sender_set_on_rtcp_feedback = fn; }
void set_fn_shim_rtp_sender_set_layer_active(void* fn) { fn_shim_rtp_sender_set_layer_active = fn; }
void set_fn_shim_rtp_sender_set_layer_bitrate(void* fn) { fn_shim_rtp_sender_set_layer_bitrate = fn; }
void set_fn_shim_rtp_sender_get_active_layers(void* fn) { fn_shim_rtp_sender_get_active_layers = fn; }
void set_fn_shim_rtp_receiver_get_track(void* fn) { fn_shim_rtp_receiver_get_track = fn; }
void set_fn_shim_rtp_receiver_get_stats(void* fn) { fn_shim_rtp_receiver_get_stats = fn; }
void set_fn_shim_rtp_receiver_set_jitter_buffer_min_delay(void* fn) { fn_shim_rtp_receiver_set_jitter_buffer_min_delay = fn; }
void set_fn_shim_transceiver_get_direction(void* fn) { fn_shim_transceiver_get_direction = fn; }
void set_fn_shim_transceiver_set_direction(void* fn) { fn_shim_transceiver_set_direction = fn; }
void set_fn_shim_transceiver_get_current_direction(void* fn) { fn_shim_transceiver_get_current_direction = fn; }
void set_fn_shim_transceiver_stop(void* fn) { fn_shim_transceiver_stop = fn; }
void set_fn_shim_transceiver_mid(void* fn) { fn_shim_transceiver_mid = fn; }
void set_fn_shim_transceiver_get_sender(void* fn) { fn_shim_transceiver_get_sender = fn; }
void set_fn_shim_transceiver_get_receiver(void* fn) { fn_shim_transceiver_get_receiver = fn; }
void set_fn_shim_transceiver_set_codec_preferences(void* fn) { fn_shim_transceiver_set_codec_preferences = fn; }
void set_fn_shim_transceiver_get_codec_preferences(void* fn) { fn_shim_transceiver_get_codec_preferences = fn; }
void set_fn_shim_peer_connection_add_transceiver(void* fn) { fn_shim_peer_connection_add_transceiver = fn; }
void set_fn_shim_peer_connection_get_senders(void* fn) { fn_shim_peer_connection_get_senders = fn; }
void set_fn_shim_peer_connection_get_receivers(void* fn) { fn_shim_peer_connection_get_receivers = fn; }
void set_fn_shim_peer_connection_get_transceivers(void* fn) { fn_shim_peer_connection_get_transceivers = fn; }
void set_fn_shim_peer_connection_restart_ice(void* fn) { fn_shim_peer_connection_restart_ice = fn; }
void set_fn_shim_peer_connection_get_stats(void* fn) { fn_shim_peer_connection_get_stats = fn; }
void set_fn_shim_peer_connection_set_on_signaling_state_change(void* fn) { fn_shim_peer_connection_set_on_signaling_state_change = fn; }
void set_fn_shim_peer_connection_set_on_ice_connection_state_change(void* fn) { fn_shim_peer_connection_set_on_ice_connection_state_change = fn; }
void set_fn_shim_peer_connection_set_on_ice_gathering_state_change(void* fn) { fn_shim_peer_connection_set_on_ice_gathering_state_change = fn; }
void set_fn_shim_peer_connection_set_on_negotiation_needed(void* fn) { fn_shim_peer_connection_set_on_negotiation_needed = fn; }
void set_fn_shim_rtp_sender_set_scalability_mode(void* fn) { fn_shim_rtp_sender_set_scalability_mode = fn; }
void set_fn_shim_rtp_sender_get_scalability_mode(void* fn) { fn_shim_rtp_sender_get_scalability_mode = fn; }
void set_fn_shim_get_supported_video_codecs(void* fn) { fn_shim_get_supported_video_codecs = fn; }
void set_fn_shim_get_supported_audio_codecs(void* fn) { fn_shim_get_supported_audio_codecs = fn; }
void set_fn_shim_is_codec_supported(void* fn) { fn_shim_is_codec_supported = fn; }
void set_fn_shim_rtp_sender_get_negotiated_codecs(void* fn) { fn_shim_rtp_sender_get_negotiated_codecs = fn; }
void set_fn_shim_rtp_sender_set_preferred_codec(void* fn) { fn_shim_rtp_sender_set_preferred_codec = fn; }
void set_fn_shim_peer_connection_set_on_bandwidth_estimate(void* fn) { fn_shim_peer_connection_set_on_bandwidth_estimate = fn; }
void set_fn_shim_peer_connection_get_bandwidth_estimate(void* fn) { fn_shim_peer_connection_get_bandwidth_estimate = fn; }
void set_fn_shim_enumerate_devices(void* fn) { fn_shim_enumerate_devices = fn; }
void set_fn_shim_video_capture_create(void* fn) { fn_shim_video_capture_create = fn; }
void set_fn_shim_video_capture_start(void* fn) { fn_shim_video_capture_start = fn; }
void set_fn_shim_video_capture_stop(void* fn) { fn_shim_video_capture_stop = fn; }
void set_fn_shim_video_capture_destroy(void* fn) { fn_shim_video_capture_destroy = fn; }
void set_fn_shim_audio_capture_create(void* fn) { fn_shim_audio_capture_create = fn; }
void set_fn_shim_audio_capture_start(void* fn) { fn_shim_audio_capture_start = fn; }
void set_fn_shim_audio_capture_stop(void* fn) { fn_shim_audio_capture_stop = fn; }
void set_fn_shim_audio_capture_destroy(void* fn) { fn_shim_audio_capture_destroy = fn; }
void set_fn_shim_enumerate_screens(void* fn) { fn_shim_enumerate_screens = fn; }
void set_fn_shim_screen_capture_create(void* fn) { fn_shim_screen_capture_create = fn; }
void set_fn_shim_screen_capture_start(void* fn) { fn_shim_screen_capture_start = fn; }
void set_fn_shim_screen_capture_stop(void* fn) { fn_shim_screen_capture_stop = fn; }
void set_fn_shim_screen_capture_destroy(void* fn) { fn_shim_screen_capture_destroy = fn; }
void set_fn_shim_check_camera_permission(void* fn) { fn_shim_check_camera_permission = fn; }
void set_fn_shim_check_microphone_permission(void* fn) { fn_shim_check_microphone_permission = fn; }
void set_fn_shim_request_camera_permission(void* fn) { fn_shim_request_camera_permission = fn; }
void set_fn_shim_request_microphone_permission(void* fn) { fn_shim_request_microphone_permission = fn; }

// Trampoline functions
uintptr_t call_shim_video_encoder_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_encoder_create)(params);
}
int32_t call_shim_video_encoder_encode(uintptr_t encoder, uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_encoder_encode)(encoder, params);
}
int32_t call_shim_video_encoder_set_bitrate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_encoder_set_bitrate)(params);
}
int32_t call_shim_video_encoder_set_framerate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_encoder_set_framerate)(params);
}
int32_t call_shim_video_encoder_request_keyframe(uintptr_t encoder) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_encoder_request_keyframe)(encoder);
}
void call_shim_video_encoder_destroy(uintptr_t encoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_encoder_destroy)(encoder);
}
uintptr_t call_shim_video_decoder_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_decoder_create)(params);
}
int32_t call_shim_video_decoder_decode(uintptr_t decoder, uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_video_decoder_decode)(decoder, params);
}
void call_shim_video_decoder_destroy(uintptr_t decoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_decoder_destroy)(decoder);
}
uintptr_t call_shim_audio_encoder_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_encoder_create)(params);
}
int32_t call_shim_audio_encoder_encode(uintptr_t encoder, uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_encoder_encode)(encoder, params);
}
int32_t call_shim_audio_encoder_set_bitrate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_encoder_set_bitrate)(params);
}
void call_shim_audio_encoder_destroy(uintptr_t encoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_encoder_destroy)(encoder);
}
uintptr_t call_shim_audio_decoder_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_decoder_create)(params);
}
int32_t call_shim_audio_decoder_decode(uintptr_t decoder, uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t, uintptr_t);
    return ((fn_t)fn_shim_audio_decoder_decode)(decoder, params);
}
void call_shim_audio_decoder_destroy(uintptr_t decoder) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_decoder_destroy)(decoder);
}
uintptr_t call_shim_packetizer_create(uintptr_t configPtr) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_packetizer_create)(configPtr);
}
int32_t call_shim_packetizer_packetize(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_packetizer_packetize)(params);
}
uint16_t call_shim_packetizer_sequence_number(uintptr_t packetizer) {
    typedef uint16_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_packetizer_sequence_number)(packetizer);
}
void call_shim_packetizer_destroy(uintptr_t packetizer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_packetizer_destroy)(packetizer);
}
uintptr_t call_shim_depacketizer_create(int32_t codec) {
    typedef uintptr_t (*fn_t)(int32_t);
    return ((fn_t)fn_shim_depacketizer_create)(codec);
}
int32_t call_shim_depacketizer_push(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_depacketizer_push)(params);
}
int32_t call_shim_depacketizer_pop(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_depacketizer_pop)(params);
}
void call_shim_depacketizer_destroy(uintptr_t depacketizer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_depacketizer_destroy)(depacketizer);
}
void call_shim_free_buffer(uintptr_t buffer) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_free_buffer)(buffer);
}
void call_shim_free_packets(uintptr_t packets, uintptr_t sizes, int32_t count) {
    typedef void (*fn_t)(uintptr_t, uintptr_t, int32_t);
    ((fn_t)fn_shim_free_packets)(packets, sizes, count);
}
uintptr_t call_shim_libwebrtc_version() {
    typedef uintptr_t (*fn_t)();
    return ((fn_t)fn_shim_libwebrtc_version)();
}
uintptr_t call_shim_version() {
    typedef uintptr_t (*fn_t)();
    return ((fn_t)fn_shim_version)();
}
uintptr_t call_shim_peer_connection_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create)(params);
}
void call_shim_peer_connection_destroy(uintptr_t pc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_destroy)(pc);
}
void call_shim_peer_connection_set_on_ice_candidate(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_candidate)(params);
}
void call_shim_peer_connection_set_on_connection_state_change(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_connection_state_change)(params);
}
void call_shim_peer_connection_set_on_track(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_track)(params);
}
void call_shim_peer_connection_set_on_data_channel(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_data_channel)(params);
}
int32_t call_shim_peer_connection_create_offer(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_offer)(params);
}
int32_t call_shim_peer_connection_create_answer(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_answer)(params);
}
int32_t call_shim_peer_connection_set_local_description(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_set_local_description)(params);
}
int32_t call_shim_peer_connection_set_remote_description(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_set_remote_description)(params);
}
int32_t call_shim_peer_connection_add_ice_candidate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_ice_candidate)(params);
}
int32_t call_shim_peer_connection_signaling_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_signaling_state)(pc);
}
int32_t call_shim_peer_connection_ice_connection_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_ice_connection_state)(pc);
}
int32_t call_shim_peer_connection_ice_gathering_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_ice_gathering_state)(pc);
}
int32_t call_shim_peer_connection_connection_state(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_connection_state)(pc);
}
uintptr_t call_shim_peer_connection_add_track(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_track)(params);
}
int32_t call_shim_peer_connection_remove_track(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_remove_track)(params);
}
uintptr_t call_shim_peer_connection_create_data_channel(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_create_data_channel)(params);
}
void call_shim_peer_connection_close(uintptr_t pc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_close)(pc);
}
int32_t call_shim_rtp_sender_set_bitrate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_bitrate)(params);
}
int32_t call_shim_rtp_sender_replace_track(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_replace_track)(params);
}
void call_shim_rtp_sender_destroy(uintptr_t sender) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_rtp_sender_destroy)(sender);
}
void call_shim_data_channel_set_on_message(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_message)(params);
}
void call_shim_data_channel_set_on_open(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_open)(params);
}
void call_shim_data_channel_set_on_close(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_set_on_close)(params);
}
int32_t call_shim_data_channel_send(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_data_channel_send)(params);
}
uintptr_t call_shim_data_channel_label(uintptr_t dc) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_data_channel_label)(dc);
}
int32_t call_shim_data_channel_ready_state(uintptr_t dc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_data_channel_ready_state)(dc);
}
void call_shim_data_channel_close(uintptr_t dc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_close)(dc);
}
void call_shim_data_channel_destroy(uintptr_t dc) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_data_channel_destroy)(dc);
}
uintptr_t call_shim_video_track_source_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_track_source_create)(params);
}
int32_t call_shim_video_track_source_push_frame(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_track_source_push_frame)(params);
}
uintptr_t call_shim_peer_connection_add_video_track_from_source(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_video_track_from_source)(params);
}
void call_shim_video_track_source_destroy(uintptr_t source) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_track_source_destroy)(source);
}
uintptr_t call_shim_audio_track_source_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_track_source_create)(params);
}
int32_t call_shim_audio_track_source_push_frame(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_track_source_push_frame)(params);
}
uintptr_t call_shim_peer_connection_add_audio_track_from_source(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_audio_track_from_source)(params);
}
void call_shim_audio_track_source_destroy(uintptr_t source) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_track_source_destroy)(source);
}
int32_t call_shim_track_set_video_sink(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_set_video_sink)(params);
}
int32_t call_shim_track_set_audio_sink(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_set_audio_sink)(params);
}
void call_shim_track_remove_video_sink(uintptr_t track) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_track_remove_video_sink)(track);
}
void call_shim_track_remove_audio_sink(uintptr_t track) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_track_remove_audio_sink)(track);
}
uintptr_t call_shim_track_kind(uintptr_t track) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_kind)(track);
}
uintptr_t call_shim_track_id(uintptr_t track) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_track_id)(track);
}
int32_t call_shim_rtp_sender_get_parameters(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_parameters)(params);
}
int32_t call_shim_rtp_sender_set_parameters(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_parameters)(params);
}
uintptr_t call_shim_rtp_sender_get_track(uintptr_t sender) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_track)(sender);
}
int32_t call_shim_rtp_sender_get_stats(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_stats)(params);
}
void call_shim_rtp_sender_set_on_rtcp_feedback(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_rtp_sender_set_on_rtcp_feedback)(params);
}
int32_t call_shim_rtp_sender_set_layer_active(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_layer_active)(params);
}
int32_t call_shim_rtp_sender_set_layer_bitrate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_layer_bitrate)(params);
}
int32_t call_shim_rtp_sender_get_active_layers(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_active_layers)(params);
}
uintptr_t call_shim_rtp_receiver_get_track(uintptr_t receiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_receiver_get_track)(receiver);
}
int32_t call_shim_rtp_receiver_get_stats(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_receiver_get_stats)(params);
}
int32_t call_shim_rtp_receiver_set_jitter_buffer_min_delay(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_receiver_set_jitter_buffer_min_delay)(params);
}
int32_t call_shim_transceiver_get_direction(uintptr_t transceiver) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_direction)(transceiver);
}
int32_t call_shim_transceiver_set_direction(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_set_direction)(params);
}
int32_t call_shim_transceiver_get_current_direction(uintptr_t transceiver) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_current_direction)(transceiver);
}
int32_t call_shim_transceiver_stop(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_stop)(params);
}
uintptr_t call_shim_transceiver_mid(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_mid)(transceiver);
}
uintptr_t call_shim_transceiver_get_sender(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_sender)(transceiver);
}
uintptr_t call_shim_transceiver_get_receiver(uintptr_t transceiver) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_receiver)(transceiver);
}
int32_t call_shim_transceiver_set_codec_preferences(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_set_codec_preferences)(params);
}
int32_t call_shim_transceiver_get_codec_preferences(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_transceiver_get_codec_preferences)(params);
}
uintptr_t call_shim_peer_connection_add_transceiver(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_add_transceiver)(params);
}
int32_t call_shim_peer_connection_get_senders(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_senders)(params);
}
int32_t call_shim_peer_connection_get_receivers(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_receivers)(params);
}
int32_t call_shim_peer_connection_get_transceivers(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_transceivers)(params);
}
int32_t call_shim_peer_connection_restart_ice(uintptr_t pc) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_restart_ice)(pc);
}
int32_t call_shim_peer_connection_get_stats(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_stats)(params);
}
void call_shim_peer_connection_set_on_signaling_state_change(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_signaling_state_change)(params);
}
void call_shim_peer_connection_set_on_ice_connection_state_change(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_connection_state_change)(params);
}
void call_shim_peer_connection_set_on_ice_gathering_state_change(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_ice_gathering_state_change)(params);
}
void call_shim_peer_connection_set_on_negotiation_needed(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_negotiation_needed)(params);
}
int32_t call_shim_rtp_sender_set_scalability_mode(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_scalability_mode)(params);
}
int32_t call_shim_rtp_sender_get_scalability_mode(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_scalability_mode)(params);
}
int32_t call_shim_get_supported_video_codecs(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_get_supported_video_codecs)(params);
}
int32_t call_shim_get_supported_audio_codecs(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_get_supported_audio_codecs)(params);
}
int32_t call_shim_is_codec_supported(uintptr_t mimeType) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_is_codec_supported)(mimeType);
}
int32_t call_shim_rtp_sender_get_negotiated_codecs(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_get_negotiated_codecs)(params);
}
int32_t call_shim_rtp_sender_set_preferred_codec(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_rtp_sender_set_preferred_codec)(params);
}
void call_shim_peer_connection_set_on_bandwidth_estimate(uintptr_t params) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_peer_connection_set_on_bandwidth_estimate)(params);
}
int32_t call_shim_peer_connection_get_bandwidth_estimate(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_peer_connection_get_bandwidth_estimate)(params);
}
int32_t call_shim_enumerate_devices(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_enumerate_devices)(params);
}
uintptr_t call_shim_video_capture_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_capture_create)(params);
}
int32_t call_shim_video_capture_start(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_video_capture_start)(params);
}
void call_shim_video_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_capture_stop)(capturePtr);
}
void call_shim_video_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_video_capture_destroy)(capturePtr);
}
uintptr_t call_shim_audio_capture_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_capture_create)(params);
}
int32_t call_shim_audio_capture_start(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_audio_capture_start)(params);
}
void call_shim_audio_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_capture_stop)(capturePtr);
}
void call_shim_audio_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_audio_capture_destroy)(capturePtr);
}
int32_t call_shim_enumerate_screens(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_enumerate_screens)(params);
}
uintptr_t call_shim_screen_capture_create(uintptr_t params) {
    typedef uintptr_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_screen_capture_create)(params);
}
int32_t call_shim_screen_capture_start(uintptr_t params) {
    typedef int32_t (*fn_t)(uintptr_t);
    return ((fn_t)fn_shim_screen_capture_start)(params);
}
void call_shim_screen_capture_stop(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_screen_capture_stop)(capturePtr);
}
void call_shim_screen_capture_destroy(uintptr_t capturePtr) {
    typedef void (*fn_t)(uintptr_t);
    ((fn_t)fn_shim_screen_capture_destroy)(capturePtr);
}
int32_t call_shim_check_camera_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_check_camera_permission)();
}
int32_t call_shim_check_microphone_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_check_microphone_permission)();
}
int32_t call_shim_request_camera_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_request_camera_permission)();
}
int32_t call_shim_request_microphone_permission() {
    typedef int32_t (*fn_t)();
    return ((fn_t)fn_shim_request_microphone_permission)();
}
*/
import "C"
import "unsafe"

func registerFunctions() error {
	// VideoEncoder
	C.set_fn_shim_video_encoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_create")))
	C.set_fn_shim_video_encoder_encode(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_encode")))
	C.set_fn_shim_video_encoder_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_set_bitrate")))
	C.set_fn_shim_video_encoder_set_framerate(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_set_framerate")))
	C.set_fn_shim_video_encoder_request_keyframe(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_request_keyframe")))
	C.set_fn_shim_video_encoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_encoder_destroy")))

	// VideoDecoder
	C.set_fn_shim_video_decoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_create")))
	C.set_fn_shim_video_decoder_decode(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_decode")))
	C.set_fn_shim_video_decoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_decoder_destroy")))

	// AudioEncoder
	C.set_fn_shim_audio_encoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_create")))
	C.set_fn_shim_audio_encoder_encode(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_encode")))
	C.set_fn_shim_audio_encoder_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_set_bitrate")))
	C.set_fn_shim_audio_encoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_encoder_destroy")))

	// AudioDecoder
	C.set_fn_shim_audio_decoder_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_create")))
	C.set_fn_shim_audio_decoder_decode(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_decode")))
	C.set_fn_shim_audio_decoder_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_decoder_destroy")))

	// Packetizer
	C.set_fn_shim_packetizer_create(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_create")))
	C.set_fn_shim_packetizer_packetize(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_packetize")))
	C.set_fn_shim_packetizer_sequence_number(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_sequence_number")))
	C.set_fn_shim_packetizer_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_packetizer_destroy")))

	// Depacketizer
	C.set_fn_shim_depacketizer_create(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_create")))
	C.set_fn_shim_depacketizer_push(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_push")))
	C.set_fn_shim_depacketizer_pop(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_pop")))
	C.set_fn_shim_depacketizer_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_depacketizer_destroy")))

	// Memory
	C.set_fn_shim_free_buffer(unsafe.Pointer(mustDlsym(libHandle, "shim_free_buffer")))
	C.set_fn_shim_free_packets(unsafe.Pointer(mustDlsym(libHandle, "shim_free_packets")))

	// Version
	C.set_fn_shim_libwebrtc_version(unsafe.Pointer(mustDlsym(libHandle, "shim_libwebrtc_version")))
	C.set_fn_shim_version(unsafe.Pointer(mustDlsym(libHandle, "shim_version")))

	// PeerConnection
	C.set_fn_shim_peer_connection_create(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create")))
	C.set_fn_shim_peer_connection_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_destroy")))
	C.set_fn_shim_peer_connection_set_on_ice_candidate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_candidate")))
	C.set_fn_shim_peer_connection_set_on_connection_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_connection_state_change")))
	C.set_fn_shim_peer_connection_set_on_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_track")))
	C.set_fn_shim_peer_connection_set_on_data_channel(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_data_channel")))
	C.set_fn_shim_peer_connection_create_offer(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_offer")))
	C.set_fn_shim_peer_connection_create_answer(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_answer")))
	C.set_fn_shim_peer_connection_set_local_description(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_local_description")))
	C.set_fn_shim_peer_connection_set_remote_description(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_remote_description")))
	C.set_fn_shim_peer_connection_add_ice_candidate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_ice_candidate")))
	C.set_fn_shim_peer_connection_signaling_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_signaling_state")))
	C.set_fn_shim_peer_connection_ice_connection_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_ice_connection_state")))
	C.set_fn_shim_peer_connection_ice_gathering_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_ice_gathering_state")))
	C.set_fn_shim_peer_connection_connection_state(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_connection_state")))
	C.set_fn_shim_peer_connection_add_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_track")))
	C.set_fn_shim_peer_connection_remove_track(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_remove_track")))
	C.set_fn_shim_peer_connection_create_data_channel(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_create_data_channel")))
	C.set_fn_shim_peer_connection_close(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_close")))

	// PeerConnectionExtended
	C.set_fn_shim_peer_connection_add_transceiver(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_transceiver")))
	C.set_fn_shim_peer_connection_get_senders(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_senders")))
	C.set_fn_shim_peer_connection_get_receivers(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_receivers")))
	C.set_fn_shim_peer_connection_get_transceivers(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_transceivers")))
	C.set_fn_shim_peer_connection_restart_ice(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_restart_ice")))
	C.set_fn_shim_peer_connection_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_stats")))
	C.set_fn_shim_peer_connection_set_on_signaling_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_signaling_state_change")))
	C.set_fn_shim_peer_connection_set_on_ice_connection_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_connection_state_change")))
	C.set_fn_shim_peer_connection_set_on_ice_gathering_state_change(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_ice_gathering_state_change")))
	C.set_fn_shim_peer_connection_set_on_negotiation_needed(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_negotiation_needed")))

	// RTPSender
	C.set_fn_shim_rtp_sender_set_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_bitrate")))
	C.set_fn_shim_rtp_sender_replace_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_replace_track")))
	C.set_fn_shim_rtp_sender_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_destroy")))
	C.set_fn_shim_rtp_sender_get_parameters(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_parameters")))
	C.set_fn_shim_rtp_sender_set_parameters(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_parameters")))
	C.set_fn_shim_rtp_sender_get_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_track")))
	C.set_fn_shim_rtp_sender_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_stats")))
	C.set_fn_shim_rtp_sender_set_on_rtcp_feedback(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_on_rtcp_feedback")))
	C.set_fn_shim_rtp_sender_set_layer_active(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_layer_active")))
	C.set_fn_shim_rtp_sender_set_layer_bitrate(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_layer_bitrate")))
	C.set_fn_shim_rtp_sender_get_active_layers(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_active_layers")))

	// RTPReceiver
	C.set_fn_shim_rtp_receiver_get_track(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_get_track")))
	C.set_fn_shim_rtp_receiver_get_stats(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_get_stats")))
	C.set_fn_shim_rtp_receiver_set_jitter_buffer_min_delay(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_receiver_set_jitter_buffer_min_delay")))

	// RTPTransceiver
	C.set_fn_shim_transceiver_get_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_direction")))
	C.set_fn_shim_transceiver_set_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_set_direction")))
	C.set_fn_shim_transceiver_get_current_direction(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_current_direction")))
	C.set_fn_shim_transceiver_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_stop")))
	C.set_fn_shim_transceiver_mid(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_mid")))
	C.set_fn_shim_transceiver_get_sender(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_sender")))
	C.set_fn_shim_transceiver_get_receiver(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_receiver")))
	C.set_fn_shim_transceiver_set_codec_preferences(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_set_codec_preferences")))
	C.set_fn_shim_transceiver_get_codec_preferences(unsafe.Pointer(mustDlsym(libHandle, "shim_transceiver_get_codec_preferences")))

	// DataChannel
	C.set_fn_shim_data_channel_set_on_message(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_message")))
	C.set_fn_shim_data_channel_set_on_open(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_open")))
	C.set_fn_shim_data_channel_set_on_close(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_set_on_close")))
	C.set_fn_shim_data_channel_send(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_send")))
	C.set_fn_shim_data_channel_label(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_label")))
	C.set_fn_shim_data_channel_ready_state(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_ready_state")))
	C.set_fn_shim_data_channel_close(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_close")))
	C.set_fn_shim_data_channel_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_data_channel_destroy")))

	// VideoTrackSource
	C.set_fn_shim_video_track_source_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_create")))
	C.set_fn_shim_video_track_source_push_frame(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_push_frame")))
	C.set_fn_shim_peer_connection_add_video_track_from_source(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_video_track_from_source")))
	C.set_fn_shim_video_track_source_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_track_source_destroy")))

	// AudioTrackSource
	C.set_fn_shim_audio_track_source_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_create")))
	C.set_fn_shim_audio_track_source_push_frame(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_push_frame")))
	C.set_fn_shim_peer_connection_add_audio_track_from_source(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_add_audio_track_from_source")))
	C.set_fn_shim_audio_track_source_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_track_source_destroy")))

	// RemoteTrack
	C.set_fn_shim_track_set_video_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_set_video_sink")))
	C.set_fn_shim_track_set_audio_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_set_audio_sink")))
	C.set_fn_shim_track_remove_video_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_remove_video_sink")))
	C.set_fn_shim_track_remove_audio_sink(unsafe.Pointer(mustDlsym(libHandle, "shim_track_remove_audio_sink")))
	C.set_fn_shim_track_kind(unsafe.Pointer(mustDlsym(libHandle, "shim_track_kind")))
	C.set_fn_shim_track_id(unsafe.Pointer(mustDlsym(libHandle, "shim_track_id")))

	// ScalabilityMode
	C.set_fn_shim_rtp_sender_set_scalability_mode(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_scalability_mode")))
	C.set_fn_shim_rtp_sender_get_scalability_mode(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_scalability_mode")))

	// CodecCapabilities
	C.set_fn_shim_get_supported_video_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_get_supported_video_codecs")))
	C.set_fn_shim_get_supported_audio_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_get_supported_audio_codecs")))
	C.set_fn_shim_is_codec_supported(unsafe.Pointer(mustDlsym(libHandle, "shim_is_codec_supported")))

	// RTPSenderCodec
	C.set_fn_shim_rtp_sender_get_negotiated_codecs(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_get_negotiated_codecs")))
	C.set_fn_shim_rtp_sender_set_preferred_codec(unsafe.Pointer(mustDlsym(libHandle, "shim_rtp_sender_set_preferred_codec")))

	// BandwidthEstimation
	C.set_fn_shim_peer_connection_set_on_bandwidth_estimate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_set_on_bandwidth_estimate")))
	C.set_fn_shim_peer_connection_get_bandwidth_estimate(unsafe.Pointer(mustDlsym(libHandle, "shim_peer_connection_get_bandwidth_estimate")))

	// DeviceCapture
	C.set_fn_shim_enumerate_devices(unsafe.Pointer(mustDlsym(libHandle, "shim_enumerate_devices")))
	C.set_fn_shim_video_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_create")))
	C.set_fn_shim_video_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_start")))
	C.set_fn_shim_video_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_stop")))
	C.set_fn_shim_video_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_video_capture_destroy")))
	C.set_fn_shim_audio_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_create")))
	C.set_fn_shim_audio_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_start")))
	C.set_fn_shim_audio_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_stop")))
	C.set_fn_shim_audio_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_audio_capture_destroy")))

	// ScreenCapture
	C.set_fn_shim_enumerate_screens(unsafe.Pointer(mustDlsym(libHandle, "shim_enumerate_screens")))
	C.set_fn_shim_screen_capture_create(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_create")))
	C.set_fn_shim_screen_capture_start(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_start")))
	C.set_fn_shim_screen_capture_stop(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_stop")))
	C.set_fn_shim_screen_capture_destroy(unsafe.Pointer(mustDlsym(libHandle, "shim_screen_capture_destroy")))

	// Permissions
	C.set_fn_shim_check_camera_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_check_camera_permission")))
	C.set_fn_shim_check_microphone_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_check_microphone_permission")))
	C.set_fn_shim_request_camera_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_request_camera_permission")))
	C.set_fn_shim_request_microphone_permission(unsafe.Pointer(mustDlsym(libHandle, "shim_request_microphone_permission")))

	// Assign Go wrapper functions
	// VideoEncoder
	shimVideoEncoderCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_video_encoder_create(C.uintptr_t(params)))
	}
	shimVideoEncoderEncode = func(encoder uintptr, params uintptr) int32 {
		return int32(C.call_shim_video_encoder_encode(C.uintptr_t(encoder), C.uintptr_t(params)))
	}
	shimVideoEncoderSetBitrate = func(params uintptr) int32 {
		return int32(C.call_shim_video_encoder_set_bitrate(C.uintptr_t(params)))
	}
	shimVideoEncoderSetFramerate = func(params uintptr) int32 {
		return int32(C.call_shim_video_encoder_set_framerate(C.uintptr_t(params)))
	}
	shimVideoEncoderRequestKeyframe = func(encoder uintptr) int32 {
		return int32(C.call_shim_video_encoder_request_keyframe(C.uintptr_t(encoder)))
	}
	shimVideoEncoderDestroy = func(encoder uintptr) {
		C.call_shim_video_encoder_destroy(C.uintptr_t(encoder))
	}

	// VideoDecoder
	shimVideoDecoderCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_video_decoder_create(C.uintptr_t(params)))
	}
	shimVideoDecoderDecode = func(decoder uintptr, params uintptr) int32 {
		return int32(C.call_shim_video_decoder_decode(C.uintptr_t(decoder), C.uintptr_t(params)))
	}
	shimVideoDecoderDestroy = func(decoder uintptr) {
		C.call_shim_video_decoder_destroy(C.uintptr_t(decoder))
	}

	// AudioEncoder
	shimAudioEncoderCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_audio_encoder_create(C.uintptr_t(params)))
	}
	shimAudioEncoderEncode = func(encoder uintptr, params uintptr) int32 {
		return int32(C.call_shim_audio_encoder_encode(C.uintptr_t(encoder), C.uintptr_t(params)))
	}
	shimAudioEncoderSetBitrate = func(params uintptr) int32 {
		return int32(C.call_shim_audio_encoder_set_bitrate(C.uintptr_t(params)))
	}
	shimAudioEncoderDestroy = func(encoder uintptr) {
		C.call_shim_audio_encoder_destroy(C.uintptr_t(encoder))
	}

	// AudioDecoder
	shimAudioDecoderCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_audio_decoder_create(C.uintptr_t(params)))
	}
	shimAudioDecoderDecode = func(decoder uintptr, params uintptr) int32 {
		return int32(C.call_shim_audio_decoder_decode(C.uintptr_t(decoder), C.uintptr_t(params)))
	}
	shimAudioDecoderDestroy = func(decoder uintptr) {
		C.call_shim_audio_decoder_destroy(C.uintptr_t(decoder))
	}

	// Packetizer
	shimPacketizerCreate = func(configPtr uintptr) uintptr {
		return uintptr(C.call_shim_packetizer_create(C.uintptr_t(configPtr)))
	}
	shimPacketizerPacketize = func(params uintptr) int32 {
		return int32(C.call_shim_packetizer_packetize(C.uintptr_t(params)))
	}
	shimPacketizerSeqNum = func(packetizer uintptr) uint16 {
		return uint16(C.call_shim_packetizer_sequence_number(C.uintptr_t(packetizer)))
	}
	shimPacketizerDestroy = func(packetizer uintptr) {
		C.call_shim_packetizer_destroy(C.uintptr_t(packetizer))
	}

	// Depacketizer
	shimDepacketizerCreate = func(codec int32) uintptr {
		return uintptr(C.call_shim_depacketizer_create(C.int32_t(codec)))
	}
	shimDepacketizerPush = func(params uintptr) int32 {
		return int32(C.call_shim_depacketizer_push(C.uintptr_t(params)))
	}
	shimDepacketizerPop = func(params uintptr) int32 {
		return int32(C.call_shim_depacketizer_pop(C.uintptr_t(params)))
	}
	shimDepacketizerDestroy = func(depacketizer uintptr) {
		C.call_shim_depacketizer_destroy(C.uintptr_t(depacketizer))
	}

	// Memory
	shimFreeBuffer = func(buffer uintptr) {
		C.call_shim_free_buffer(C.uintptr_t(buffer))
	}
	shimFreePackets = func(packets uintptr, sizes uintptr, count int32) {
		C.call_shim_free_packets(C.uintptr_t(packets), C.uintptr_t(sizes), C.int32_t(count))
	}

	// Version
	shimLibwebrtcVersion = func() uintptr {
		return uintptr(C.call_shim_libwebrtc_version())
	}
	shimVersion = func() uintptr {
		return uintptr(C.call_shim_version())
	}

	// PeerConnection
	shimPeerConnectionCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_create(C.uintptr_t(params)))
	}
	shimPeerConnectionDestroy = func(pc uintptr) {
		C.call_shim_peer_connection_destroy(C.uintptr_t(pc))
	}
	shimPeerConnectionSetOnICECandidate = func(params uintptr) {
		C.call_shim_peer_connection_set_on_ice_candidate(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnConnectionStateChange = func(params uintptr) {
		C.call_shim_peer_connection_set_on_connection_state_change(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnTrack = func(params uintptr) {
		C.call_shim_peer_connection_set_on_track(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnDataChannel = func(params uintptr) {
		C.call_shim_peer_connection_set_on_data_channel(C.uintptr_t(params))
	}
	shimPeerConnectionCreateOffer = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_create_offer(C.uintptr_t(params)))
	}
	shimPeerConnectionCreateAnswer = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_create_answer(C.uintptr_t(params)))
	}
	shimPeerConnectionSetLocalDescription = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_set_local_description(C.uintptr_t(params)))
	}
	shimPeerConnectionSetRemoteDescription = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_set_remote_description(C.uintptr_t(params)))
	}
	shimPeerConnectionAddICECandidate = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_add_ice_candidate(C.uintptr_t(params)))
	}
	shimPeerConnectionSignalingState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_signaling_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionICEConnectionState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_ice_connection_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionICEGatheringState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_ice_gathering_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionConnectionState = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_connection_state(C.uintptr_t(pc)))
	}
	shimPeerConnectionAddTrack = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_track(C.uintptr_t(params)))
	}
	shimPeerConnectionRemoveTrack = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_remove_track(C.uintptr_t(params)))
	}
	shimPeerConnectionCreateDataChannel = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_create_data_channel(C.uintptr_t(params)))
	}
	shimPeerConnectionClose = func(pc uintptr) {
		C.call_shim_peer_connection_close(C.uintptr_t(pc))
	}

	// PeerConnectionExtended
	shimPeerConnectionAddTransceiver = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_transceiver(C.uintptr_t(params)))
	}
	shimPeerConnectionGetSenders = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_senders(C.uintptr_t(params)))
	}
	shimPeerConnectionGetReceivers = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_receivers(C.uintptr_t(params)))
	}
	shimPeerConnectionGetTransceivers = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_transceivers(C.uintptr_t(params)))
	}
	shimPeerConnectionRestartICE = func(pc uintptr) int32 {
		return int32(C.call_shim_peer_connection_restart_ice(C.uintptr_t(pc)))
	}
	shimPeerConnectionGetStats = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_stats(C.uintptr_t(params)))
	}
	shimPeerConnectionSetOnSignalingStateChange = func(params uintptr) {
		C.call_shim_peer_connection_set_on_signaling_state_change(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnICEConnectionStateChange = func(params uintptr) {
		C.call_shim_peer_connection_set_on_ice_connection_state_change(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnICEGatheringStateChange = func(params uintptr) {
		C.call_shim_peer_connection_set_on_ice_gathering_state_change(C.uintptr_t(params))
	}
	shimPeerConnectionSetOnNegotiationNeeded = func(params uintptr) {
		C.call_shim_peer_connection_set_on_negotiation_needed(C.uintptr_t(params))
	}

	// RTPSender
	shimRTPSenderSetBitrate = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_bitrate(C.uintptr_t(params)))
	}
	shimRTPSenderReplaceTrack = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_replace_track(C.uintptr_t(params)))
	}
	shimRTPSenderDestroy = func(sender uintptr) {
		C.call_shim_rtp_sender_destroy(C.uintptr_t(sender))
	}
	shimRTPSenderGetParameters = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_parameters(C.uintptr_t(params)))
	}
	shimRTPSenderSetParameters = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_parameters(C.uintptr_t(params)))
	}
	shimRTPSenderGetTrack = func(sender uintptr) uintptr {
		return uintptr(C.call_shim_rtp_sender_get_track(C.uintptr_t(sender)))
	}
	shimRTPSenderGetStats = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_stats(C.uintptr_t(params)))
	}
	shimRTPSenderSetOnRTCPFeedback = func(params uintptr) {
		C.call_shim_rtp_sender_set_on_rtcp_feedback(C.uintptr_t(params))
	}
	shimRTPSenderSetLayerActive = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_layer_active(C.uintptr_t(params)))
	}
	shimRTPSenderSetLayerBitrate = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_layer_bitrate(C.uintptr_t(params)))
	}
	shimRTPSenderGetActiveLayers = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_active_layers(C.uintptr_t(params)))
	}

	// RTPReceiver
	shimRTPReceiverGetTrack = func(receiver uintptr) uintptr {
		return uintptr(C.call_shim_rtp_receiver_get_track(C.uintptr_t(receiver)))
	}
	shimRTPReceiverGetStats = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_receiver_get_stats(C.uintptr_t(params)))
	}
	shimRTPReceiverSetJitterBufferMinDelay = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_receiver_set_jitter_buffer_min_delay(C.uintptr_t(params)))
	}

	// RTPTransceiver
	shimTransceiverGetDirection = func(transceiver uintptr) int32 {
		return int32(C.call_shim_transceiver_get_direction(C.uintptr_t(transceiver)))
	}
	shimTransceiverSetDirection = func(params uintptr) int32 {
		return int32(C.call_shim_transceiver_set_direction(C.uintptr_t(params)))
	}
	shimTransceiverGetCurrentDirection = func(transceiver uintptr) int32 {
		return int32(C.call_shim_transceiver_get_current_direction(C.uintptr_t(transceiver)))
	}
	shimTransceiverStop = func(params uintptr) int32 {
		return int32(C.call_shim_transceiver_stop(C.uintptr_t(params)))
	}
	shimTransceiverMid = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_mid(C.uintptr_t(transceiver)))
	}
	shimTransceiverGetSender = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_get_sender(C.uintptr_t(transceiver)))
	}
	shimTransceiverGetReceiver = func(transceiver uintptr) uintptr {
		return uintptr(C.call_shim_transceiver_get_receiver(C.uintptr_t(transceiver)))
	}
	shimTransceiverSetCodecPreferences = func(params uintptr) int32 {
		return int32(C.call_shim_transceiver_set_codec_preferences(C.uintptr_t(params)))
	}
	shimTransceiverGetCodecPreferences = func(params uintptr) int32 {
		return int32(C.call_shim_transceiver_get_codec_preferences(C.uintptr_t(params)))
	}

	// DataChannel
	shimDataChannelSetOnMessage = func(params uintptr) {
		C.call_shim_data_channel_set_on_message(C.uintptr_t(params))
	}
	shimDataChannelSetOnOpen = func(params uintptr) {
		C.call_shim_data_channel_set_on_open(C.uintptr_t(params))
	}
	shimDataChannelSetOnClose = func(params uintptr) {
		C.call_shim_data_channel_set_on_close(C.uintptr_t(params))
	}
	shimDataChannelSend = func(params uintptr) int32 {
		return int32(C.call_shim_data_channel_send(C.uintptr_t(params)))
	}
	shimDataChannelLabel = func(dc uintptr) uintptr {
		return uintptr(C.call_shim_data_channel_label(C.uintptr_t(dc)))
	}
	shimDataChannelReadyState = func(dc uintptr) int32 {
		return int32(C.call_shim_data_channel_ready_state(C.uintptr_t(dc)))
	}
	shimDataChannelClose = func(dc uintptr) {
		C.call_shim_data_channel_close(C.uintptr_t(dc))
	}
	shimDataChannelDestroy = func(dc uintptr) {
		C.call_shim_data_channel_destroy(C.uintptr_t(dc))
	}

	// VideoTrackSource
	shimVideoTrackSourceCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_video_track_source_create(C.uintptr_t(params)))
	}
	shimVideoTrackSourcePushFrame = func(params uintptr) int32 {
		return int32(C.call_shim_video_track_source_push_frame(C.uintptr_t(params)))
	}
	shimPeerConnectionAddVideoTrackFromSource = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_video_track_from_source(C.uintptr_t(params)))
	}
	shimVideoTrackSourceDestroy = func(source uintptr) {
		C.call_shim_video_track_source_destroy(C.uintptr_t(source))
	}

	// AudioTrackSource
	shimAudioTrackSourceCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_audio_track_source_create(C.uintptr_t(params)))
	}
	shimAudioTrackSourcePushFrame = func(params uintptr) int32 {
		return int32(C.call_shim_audio_track_source_push_frame(C.uintptr_t(params)))
	}
	shimPeerConnectionAddAudioTrackFromSource = func(params uintptr) uintptr {
		return uintptr(C.call_shim_peer_connection_add_audio_track_from_source(C.uintptr_t(params)))
	}
	shimAudioTrackSourceDestroy = func(source uintptr) {
		C.call_shim_audio_track_source_destroy(C.uintptr_t(source))
	}

	// RemoteTrack
	shimTrackSetVideoSink = func(params uintptr) int32 {
		return int32(C.call_shim_track_set_video_sink(C.uintptr_t(params)))
	}
	shimTrackSetAudioSink = func(params uintptr) int32 {
		return int32(C.call_shim_track_set_audio_sink(C.uintptr_t(params)))
	}
	shimTrackRemoveVideoSink = func(track uintptr) {
		C.call_shim_track_remove_video_sink(C.uintptr_t(track))
	}
	shimTrackRemoveAudioSink = func(track uintptr) {
		C.call_shim_track_remove_audio_sink(C.uintptr_t(track))
	}
	shimTrackKind = func(track uintptr) uintptr {
		return uintptr(C.call_shim_track_kind(C.uintptr_t(track)))
	}
	shimTrackID = func(track uintptr) uintptr {
		return uintptr(C.call_shim_track_id(C.uintptr_t(track)))
	}

	// ScalabilityMode
	shimRTPSenderSetScalabilityMode = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_scalability_mode(C.uintptr_t(params)))
	}
	shimRTPSenderGetScalabilityMode = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_scalability_mode(C.uintptr_t(params)))
	}

	// CodecCapabilities
	shimGetSupportedVideoCodecs = func(params uintptr) int32 {
		return int32(C.call_shim_get_supported_video_codecs(C.uintptr_t(params)))
	}
	shimGetSupportedAudioCodecs = func(params uintptr) int32 {
		return int32(C.call_shim_get_supported_audio_codecs(C.uintptr_t(params)))
	}
	shimIsCodecSupported = func(mimeType uintptr) int32 {
		return int32(C.call_shim_is_codec_supported(C.uintptr_t(mimeType)))
	}

	// RTPSenderCodec
	shimRTPSenderGetNegotiatedCodecs = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_get_negotiated_codecs(C.uintptr_t(params)))
	}
	shimRTPSenderSetPreferredCodec = func(params uintptr) int32 {
		return int32(C.call_shim_rtp_sender_set_preferred_codec(C.uintptr_t(params)))
	}

	// BandwidthEstimation
	shimPeerConnectionSetOnBandwidthEstimate = func(params uintptr) {
		C.call_shim_peer_connection_set_on_bandwidth_estimate(C.uintptr_t(params))
	}
	shimPeerConnectionGetBandwidthEstimate = func(params uintptr) int32 {
		return int32(C.call_shim_peer_connection_get_bandwidth_estimate(C.uintptr_t(params)))
	}

	// DeviceCapture
	shimEnumerateDevices = func(params uintptr) int32 {
		return int32(C.call_shim_enumerate_devices(C.uintptr_t(params)))
	}
	shimVideoCaptureCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_video_capture_create(C.uintptr_t(params)))
	}
	shimVideoCaptureStart = func(params uintptr) int32 {
		return int32(C.call_shim_video_capture_start(C.uintptr_t(params)))
	}
	shimVideoCaptureStop = func(capturePtr uintptr) {
		C.call_shim_video_capture_stop(C.uintptr_t(capturePtr))
	}
	shimVideoCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_video_capture_destroy(C.uintptr_t(capturePtr))
	}
	shimAudioCaptureCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_audio_capture_create(C.uintptr_t(params)))
	}
	shimAudioCaptureStart = func(params uintptr) int32 {
		return int32(C.call_shim_audio_capture_start(C.uintptr_t(params)))
	}
	shimAudioCaptureStop = func(capturePtr uintptr) {
		C.call_shim_audio_capture_stop(C.uintptr_t(capturePtr))
	}
	shimAudioCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_audio_capture_destroy(C.uintptr_t(capturePtr))
	}

	// ScreenCapture
	shimEnumerateScreens = func(params uintptr) int32 {
		return int32(C.call_shim_enumerate_screens(C.uintptr_t(params)))
	}
	shimScreenCaptureCreate = func(params uintptr) uintptr {
		return uintptr(C.call_shim_screen_capture_create(C.uintptr_t(params)))
	}
	shimScreenCaptureStart = func(params uintptr) int32 {
		return int32(C.call_shim_screen_capture_start(C.uintptr_t(params)))
	}
	shimScreenCaptureStop = func(capturePtr uintptr) {
		C.call_shim_screen_capture_stop(C.uintptr_t(capturePtr))
	}
	shimScreenCaptureDestroy = func(capturePtr uintptr) {
		C.call_shim_screen_capture_destroy(C.uintptr_t(capturePtr))
	}

	// Permissions
	shimCheckCameraPermission = func() int32 {
		return int32(C.call_shim_check_camera_permission())
	}
	shimCheckMicrophonePermission = func() int32 {
		return int32(C.call_shim_check_microphone_permission())
	}
	shimRequestCameraPermission = func() int32 {
		return int32(C.call_shim_request_camera_permission())
	}
	shimRequestMicrophonePermission = func() int32 {
		return int32(C.call_shim_request_microphone_permission())
	}

	return nil
}

func mustDlsym(handle uintptr, name string) uintptr {
	sym, err := dlsymLibrary(handle, name)
	if err != nil {
		panic(err)
	}
	return sym
}
