// Code generated by go generate; DO NOT EDIT.

//go:build ffigo_cgo

package ffi

import (
	"testing"
	"unsafe"
)

// TestShimStructLayoutCgo compares Go struct layouts against the C shim headers.
func TestShimStructLayoutCgo(t *testing.T) {
	t.Run("ShimAudioEncoderConfig", func(t *testing.T) {
		var goCfg AudioEncoderConfig
		layout := cShimAudioEncoderConfigLayout()
		checkSizeEqual(t, "ShimAudioEncoderConfig", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimAudioEncoderConfig.SampleRate", unsafe.Offsetof(goCfg.SampleRate), layout.offsets["SampleRate"])
		checkOffsetEqual(t, "ShimAudioEncoderConfig.Channels", unsafe.Offsetof(goCfg.Channels), layout.offsets["Channels"])
		checkOffsetEqual(t, "ShimAudioEncoderConfig.BitrateBps", unsafe.Offsetof(goCfg.BitrateBps), layout.offsets["BitrateBps"])
	})

	t.Run("ShimBandwidthEstimate", func(t *testing.T) {
		var goCfg BandwidthEstimate
		layout := cShimBandwidthEstimateLayout()
		checkSizeEqual(t, "ShimBandwidthEstimate", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimBandwidthEstimate.TimestampUs", unsafe.Offsetof(goCfg.TimestampUs), layout.offsets["TimestampUs"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.TargetBitrateBps", unsafe.Offsetof(goCfg.TargetBitrateBps), layout.offsets["TargetBitrateBps"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.AvailableSendBps", unsafe.Offsetof(goCfg.AvailableSendBps), layout.offsets["AvailableSendBps"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.AvailableRecvBps", unsafe.Offsetof(goCfg.AvailableRecvBps), layout.offsets["AvailableRecvBps"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.PacingRateBps", unsafe.Offsetof(goCfg.PacingRateBps), layout.offsets["PacingRateBps"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.CongestionWindow", unsafe.Offsetof(goCfg.CongestionWindow), layout.offsets["CongestionWindow"])
		checkOffsetEqual(t, "ShimBandwidthEstimate.LossRate", unsafe.Offsetof(goCfg.LossRate), layout.offsets["LossRate"])
	})

	t.Run("ShimCodecCapability", func(t *testing.T) {
		var goCfg CodecCapability
		layout := cShimCodecCapabilityLayout()
		checkSizeEqual(t, "ShimCodecCapability", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimCodecCapability.MimeType", unsafe.Offsetof(goCfg.MimeType), layout.offsets["MimeType"])
		checkOffsetEqual(t, "ShimCodecCapability.ClockRate", unsafe.Offsetof(goCfg.ClockRate), layout.offsets["ClockRate"])
		checkOffsetEqual(t, "ShimCodecCapability.Channels", unsafe.Offsetof(goCfg.Channels), layout.offsets["Channels"])
		checkOffsetEqual(t, "ShimCodecCapability.SDPFmtpLine", unsafe.Offsetof(goCfg.SDPFmtpLine), layout.offsets["SDPFmtpLine"])
		checkOffsetEqual(t, "ShimCodecCapability.PayloadType", unsafe.Offsetof(goCfg.PayloadType), layout.offsets["PayloadType"])
	})

	t.Run("ShimDeviceInfo", func(t *testing.T) {
		var goCfg shimDeviceInfo
		layout := cShimDeviceInfoLayout()
		checkSizeEqual(t, "ShimDeviceInfo", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimDeviceInfo.deviceID", unsafe.Offsetof(goCfg.deviceID), layout.offsets["deviceID"])
		checkOffsetEqual(t, "ShimDeviceInfo.label", unsafe.Offsetof(goCfg.label), layout.offsets["label"])
		checkOffsetEqual(t, "ShimDeviceInfo.kind", unsafe.Offsetof(goCfg.kind), layout.offsets["kind"])
	})

	t.Run("ShimErrorBuffer", func(t *testing.T) {
		var goCfg ShimErrorBuffer
		layout := cShimErrorBufferLayout()
		checkSizeEqual(t, "ShimErrorBuffer", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimErrorBuffer.Message", unsafe.Offsetof(goCfg.Message), layout.offsets["Message"])
	})

	t.Run("ShimICECandidate", func(t *testing.T) {
		var goCfg shimICECandidate
		layout := cShimICECandidateLayout()
		checkSizeEqual(t, "ShimICECandidate", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimICECandidate.Candidate", unsafe.Offsetof(goCfg.Candidate), layout.offsets["Candidate"])
		checkOffsetEqual(t, "ShimICECandidate.SDPMid", unsafe.Offsetof(goCfg.SDPMid), layout.offsets["SDPMid"])
		checkOffsetEqual(t, "ShimICECandidate.SDPMLineIndex", unsafe.Offsetof(goCfg.SDPMLineIndex), layout.offsets["SDPMLineIndex"])
	})

	t.Run("ShimICEServer", func(t *testing.T) {
		var goCfg ICEServerConfig
		layout := cShimICEServerLayout()
		checkSizeEqual(t, "ShimICEServer", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimICEServer.URLs", unsafe.Offsetof(goCfg.URLs), layout.offsets["URLs"])
		checkOffsetEqual(t, "ShimICEServer.URLCount", unsafe.Offsetof(goCfg.URLCount), layout.offsets["URLCount"])
		checkOffsetEqual(t, "ShimICEServer.Username", unsafe.Offsetof(goCfg.Username), layout.offsets["Username"])
		checkOffsetEqual(t, "ShimICEServer.Credential", unsafe.Offsetof(goCfg.Credential), layout.offsets["Credential"])
	})

	t.Run("ShimPacketizerConfig", func(t *testing.T) {
		var goCfg PacketizerConfig
		layout := cShimPacketizerConfigLayout()
		checkSizeEqual(t, "ShimPacketizerConfig", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimPacketizerConfig.Codec", unsafe.Offsetof(goCfg.Codec), layout.offsets["Codec"])
		checkOffsetEqual(t, "ShimPacketizerConfig.SSRC", unsafe.Offsetof(goCfg.SSRC), layout.offsets["SSRC"])
		checkOffsetEqual(t, "ShimPacketizerConfig.PayloadType", unsafe.Offsetof(goCfg.PayloadType), layout.offsets["PayloadType"])
		checkOffsetEqual(t, "ShimPacketizerConfig.MTU", unsafe.Offsetof(goCfg.MTU), layout.offsets["MTU"])
		checkOffsetEqual(t, "ShimPacketizerConfig.ClockRate", unsafe.Offsetof(goCfg.ClockRate), layout.offsets["ClockRate"])
	})

	t.Run("ShimPeerConnectionConfig", func(t *testing.T) {
		var goCfg PeerConnectionConfig
		layout := cShimPeerConnectionConfigLayout()
		checkSizeEqual(t, "ShimPeerConnectionConfig", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimPeerConnectionConfig.ICEServers", unsafe.Offsetof(goCfg.ICEServers), layout.offsets["ICEServers"])
		checkOffsetEqual(t, "ShimPeerConnectionConfig.ICEServerCount", unsafe.Offsetof(goCfg.ICEServerCount), layout.offsets["ICEServerCount"])
		checkOffsetEqual(t, "ShimPeerConnectionConfig.ICECandidatePoolSize", unsafe.Offsetof(goCfg.ICECandidatePoolSize), layout.offsets["ICECandidatePoolSize"])
		checkOffsetEqual(t, "ShimPeerConnectionConfig.BundlePolicy", unsafe.Offsetof(goCfg.BundlePolicy), layout.offsets["BundlePolicy"])
		checkOffsetEqual(t, "ShimPeerConnectionConfig.RTCPMuxPolicy", unsafe.Offsetof(goCfg.RTCPMuxPolicy), layout.offsets["RTCPMuxPolicy"])
		checkOffsetEqual(t, "ShimPeerConnectionConfig.SDPSemantics", unsafe.Offsetof(goCfg.SDPSemantics), layout.offsets["SDPSemantics"])
	})

	t.Run("ShimRTCStats", func(t *testing.T) {
		var goCfg RTCStats
		layout := cShimRTCStatsLayout()
		checkSizeEqual(t, "ShimRTCStats", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimRTCStats.TimestampUs", unsafe.Offsetof(goCfg.TimestampUs), layout.offsets["TimestampUs"])
		checkOffsetEqual(t, "ShimRTCStats.BytesSent", unsafe.Offsetof(goCfg.BytesSent), layout.offsets["BytesSent"])
		checkOffsetEqual(t, "ShimRTCStats.BytesReceived", unsafe.Offsetof(goCfg.BytesReceived), layout.offsets["BytesReceived"])
		checkOffsetEqual(t, "ShimRTCStats.PacketsSent", unsafe.Offsetof(goCfg.PacketsSent), layout.offsets["PacketsSent"])
		checkOffsetEqual(t, "ShimRTCStats.PacketsReceived", unsafe.Offsetof(goCfg.PacketsReceived), layout.offsets["PacketsReceived"])
		checkOffsetEqual(t, "ShimRTCStats.PacketsLost", unsafe.Offsetof(goCfg.PacketsLost), layout.offsets["PacketsLost"])
		checkOffsetEqual(t, "ShimRTCStats.RoundTripTimeMs", unsafe.Offsetof(goCfg.RoundTripTimeMs), layout.offsets["RoundTripTimeMs"])
		checkOffsetEqual(t, "ShimRTCStats.JitterMs", unsafe.Offsetof(goCfg.JitterMs), layout.offsets["JitterMs"])
		checkOffsetEqual(t, "ShimRTCStats.AvailableOutgoingBitrate", unsafe.Offsetof(goCfg.AvailableOutgoingBitrate), layout.offsets["AvailableOutgoingBitrate"])
		checkOffsetEqual(t, "ShimRTCStats.AvailableIncomingBitrate", unsafe.Offsetof(goCfg.AvailableIncomingBitrate), layout.offsets["AvailableIncomingBitrate"])
		checkOffsetEqual(t, "ShimRTCStats.CurrentRTTMs", unsafe.Offsetof(goCfg.CurrentRTTMs), layout.offsets["CurrentRTTMs"])
		checkOffsetEqual(t, "ShimRTCStats.TotalRTTMs", unsafe.Offsetof(goCfg.TotalRTTMs), layout.offsets["TotalRTTMs"])
		checkOffsetEqual(t, "ShimRTCStats.ResponsesReceived", unsafe.Offsetof(goCfg.ResponsesReceived), layout.offsets["ResponsesReceived"])
		checkOffsetEqual(t, "ShimRTCStats.FramesEncoded", unsafe.Offsetof(goCfg.FramesEncoded), layout.offsets["FramesEncoded"])
		checkOffsetEqual(t, "ShimRTCStats.FramesDecoded", unsafe.Offsetof(goCfg.FramesDecoded), layout.offsets["FramesDecoded"])
		checkOffsetEqual(t, "ShimRTCStats.FramesDropped", unsafe.Offsetof(goCfg.FramesDropped), layout.offsets["FramesDropped"])
		checkOffsetEqual(t, "ShimRTCStats.KeyFramesEncoded", unsafe.Offsetof(goCfg.KeyFramesEncoded), layout.offsets["KeyFramesEncoded"])
		checkOffsetEqual(t, "ShimRTCStats.KeyFramesDecoded", unsafe.Offsetof(goCfg.KeyFramesDecoded), layout.offsets["KeyFramesDecoded"])
		checkOffsetEqual(t, "ShimRTCStats.NACKCount", unsafe.Offsetof(goCfg.NACKCount), layout.offsets["NACKCount"])
		checkOffsetEqual(t, "ShimRTCStats.PLICount", unsafe.Offsetof(goCfg.PLICount), layout.offsets["PLICount"])
		checkOffsetEqual(t, "ShimRTCStats.FIRCount", unsafe.Offsetof(goCfg.FIRCount), layout.offsets["FIRCount"])
		checkOffsetEqual(t, "ShimRTCStats.QPSum", unsafe.Offsetof(goCfg.QPSum), layout.offsets["QPSum"])
		checkOffsetEqual(t, "ShimRTCStats.AudioLevel", unsafe.Offsetof(goCfg.AudioLevel), layout.offsets["AudioLevel"])
		checkOffsetEqual(t, "ShimRTCStats.TotalAudioEnergy", unsafe.Offsetof(goCfg.TotalAudioEnergy), layout.offsets["TotalAudioEnergy"])
		checkOffsetEqual(t, "ShimRTCStats.ConcealmentEvents", unsafe.Offsetof(goCfg.ConcealmentEvents), layout.offsets["ConcealmentEvents"])
		checkOffsetEqual(t, "ShimRTCStats.DataChannelsOpened", unsafe.Offsetof(goCfg.DataChannelsOpened), layout.offsets["DataChannelsOpened"])
		checkOffsetEqual(t, "ShimRTCStats.DataChannelsClosed", unsafe.Offsetof(goCfg.DataChannelsClosed), layout.offsets["DataChannelsClosed"])
		checkOffsetEqual(t, "ShimRTCStats.MessagesSent", unsafe.Offsetof(goCfg.MessagesSent), layout.offsets["MessagesSent"])
		checkOffsetEqual(t, "ShimRTCStats.MessagesReceived", unsafe.Offsetof(goCfg.MessagesReceived), layout.offsets["MessagesReceived"])
		checkOffsetEqual(t, "ShimRTCStats.BytesSentDataChannel", unsafe.Offsetof(goCfg.BytesSentDataChannel), layout.offsets["BytesSentDataChannel"])
		checkOffsetEqual(t, "ShimRTCStats.BytesReceivedDataChannel", unsafe.Offsetof(goCfg.BytesReceivedDataChannel), layout.offsets["BytesReceivedDataChannel"])
		checkOffsetEqual(t, "ShimRTCStats.QualityLimitationReason", unsafe.Offsetof(goCfg.QualityLimitationReason), layout.offsets["QualityLimitationReason"])
		checkOffsetEqual(t, "ShimRTCStats.QualityLimitationDurationMs", unsafe.Offsetof(goCfg.QualityLimitationDurationMs), layout.offsets["QualityLimitationDurationMs"])
		checkOffsetEqual(t, "ShimRTCStats.RemotePacketsLost", unsafe.Offsetof(goCfg.RemotePacketsLost), layout.offsets["RemotePacketsLost"])
		checkOffsetEqual(t, "ShimRTCStats.RemoteJitterMs", unsafe.Offsetof(goCfg.RemoteJitterMs), layout.offsets["RemoteJitterMs"])
		checkOffsetEqual(t, "ShimRTCStats.RemoteRoundTripTimeMs", unsafe.Offsetof(goCfg.RemoteRoundTripTimeMs), layout.offsets["RemoteRoundTripTimeMs"])
		checkOffsetEqual(t, "ShimRTCStats.JitterBufferDelayMs", unsafe.Offsetof(goCfg.JitterBufferDelayMs), layout.offsets["JitterBufferDelayMs"])
		checkOffsetEqual(t, "ShimRTCStats.JitterBufferTargetDelayMs", unsafe.Offsetof(goCfg.JitterBufferTargetDelayMs), layout.offsets["JitterBufferTargetDelayMs"])
		checkOffsetEqual(t, "ShimRTCStats.JitterBufferMinimumDelayMs", unsafe.Offsetof(goCfg.JitterBufferMinimumDelayMs), layout.offsets["JitterBufferMinimumDelayMs"])
		checkOffsetEqual(t, "ShimRTCStats.JitterBufferEmittedCount", unsafe.Offsetof(goCfg.JitterBufferEmittedCount), layout.offsets["JitterBufferEmittedCount"])
	})

	t.Run("ShimRTPEncodingParameters", func(t *testing.T) {
		var goCfg RTPEncodingParameters
		layout := cShimRTPEncodingParametersLayout()
		checkSizeEqual(t, "ShimRTPEncodingParameters", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimRTPEncodingParameters.RID", unsafe.Offsetof(goCfg.RID), layout.offsets["RID"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.MaxBitrateBps", unsafe.Offsetof(goCfg.MaxBitrateBps), layout.offsets["MaxBitrateBps"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.MinBitrateBps", unsafe.Offsetof(goCfg.MinBitrateBps), layout.offsets["MinBitrateBps"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.MaxFramerate", unsafe.Offsetof(goCfg.MaxFramerate), layout.offsets["MaxFramerate"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.ScaleResolutionDownBy", unsafe.Offsetof(goCfg.ScaleResolutionDownBy), layout.offsets["ScaleResolutionDownBy"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.Active", unsafe.Offsetof(goCfg.Active), layout.offsets["Active"])
		checkOffsetEqual(t, "ShimRTPEncodingParameters.ScalabilityMode", unsafe.Offsetof(goCfg.ScalabilityMode), layout.offsets["ScalabilityMode"])
	})

	t.Run("ShimRTPSendParameters", func(t *testing.T) {
		var goCfg RTPSendParameters
		layout := cShimRTPSendParametersLayout()
		checkSizeEqual(t, "ShimRTPSendParameters", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimRTPSendParameters.Encodings", unsafe.Offsetof(goCfg.Encodings), layout.offsets["Encodings"])
		checkOffsetEqual(t, "ShimRTPSendParameters.EncodingCount", unsafe.Offsetof(goCfg.EncodingCount), layout.offsets["EncodingCount"])
		checkOffsetEqual(t, "ShimRTPSendParameters.TransactionID", unsafe.Offsetof(goCfg.TransactionID), layout.offsets["TransactionID"])
	})

	t.Run("ShimScreenInfo", func(t *testing.T) {
		var goCfg shimScreenInfo
		layout := cShimScreenInfoLayout()
		checkSizeEqual(t, "ShimScreenInfo", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimScreenInfo.id", unsafe.Offsetof(goCfg.id), layout.offsets["id"])
		checkOffsetEqual(t, "ShimScreenInfo.title", unsafe.Offsetof(goCfg.title), layout.offsets["title"])
		checkOffsetEqual(t, "ShimScreenInfo.isWindow", unsafe.Offsetof(goCfg.isWindow), layout.offsets["isWindow"])
	})

	t.Run("ShimSessionDescription", func(t *testing.T) {
		var goCfg shimSessionDescription
		layout := cShimSessionDescriptionLayout()
		checkSizeEqual(t, "ShimSessionDescription", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimSessionDescription.Type", unsafe.Offsetof(goCfg.Type), layout.offsets["Type"])
		checkOffsetEqual(t, "ShimSessionDescription.SDP", unsafe.Offsetof(goCfg.SDP), layout.offsets["SDP"])
	})

	t.Run("ShimVideoEncoderConfig", func(t *testing.T) {
		var goCfg VideoEncoderConfig
		layout := cShimVideoEncoderConfigLayout()
		checkSizeEqual(t, "ShimVideoEncoderConfig", unsafe.Sizeof(goCfg), layout.size)
		checkOffsetEqual(t, "ShimVideoEncoderConfig.Width", unsafe.Offsetof(goCfg.Width), layout.offsets["Width"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.Height", unsafe.Offsetof(goCfg.Height), layout.offsets["Height"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.BitrateBps", unsafe.Offsetof(goCfg.BitrateBps), layout.offsets["BitrateBps"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.Framerate", unsafe.Offsetof(goCfg.Framerate), layout.offsets["Framerate"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.KeyframeInterval", unsafe.Offsetof(goCfg.KeyframeInterval), layout.offsets["KeyframeInterval"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.H264Profile", unsafe.Offsetof(goCfg.H264Profile), layout.offsets["H264Profile"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.VP9Profile", unsafe.Offsetof(goCfg.VP9Profile), layout.offsets["VP9Profile"])
		checkOffsetEqual(t, "ShimVideoEncoderConfig.PreferHW", unsafe.Offsetof(goCfg.PreferHW), layout.offsets["PreferHW"])
	})

}

func checkSizeEqual(t *testing.T, name string, goSize, cSize uintptr) {
	t.Helper()
	if goSize != cSize {
		t.Errorf("%s size = %d, want %d", name, goSize, cSize)
	}
}

func checkOffsetEqual(t *testing.T, name string, goOffset, cOffset uintptr) {
	t.Helper()
	if goOffset != cOffset {
		t.Errorf("%s offset = %d, want %d", name, goOffset, cOffset)
	}
}
