// Code generated by go generate; DO NOT EDIT.

//go:build ffigo_cgo

package ffi

/*
#cgo CFLAGS: -I${SRCDIR}/../../shim
#include "shim.h"
*/
import "C"

import "unsafe"

type cStructLayout struct {
	size    uintptr
	offsets map[string]uintptr
}

func cShimAudioCaptureCreateParamsLayout() cStructLayout {
	var cCfg C.ShimAudioCaptureCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DeviceID":   unsafe.Offsetof(cCfg.device_id),
			"SampleRate": unsafe.Offsetof(cCfg.sample_rate),
			"Channels":   unsafe.Offsetof(cCfg.channels),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioCaptureStartParamsLayout() cStructLayout {
	var cCfg C.ShimAudioCaptureStartParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Cap":      unsafe.Offsetof(cCfg.cap),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioDecoderCreateParamsLayout() cStructLayout {
	var cCfg C.ShimAudioDecoderCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"SampleRate": unsafe.Offsetof(cCfg.sample_rate),
			"Channels":   unsafe.Offsetof(cCfg.channels),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioDecoderDecodeParamsLayout() cStructLayout {
	var cCfg C.ShimAudioDecoderDecodeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Data":          unsafe.Offsetof(cCfg.data),
			"Size":          unsafe.Offsetof(cCfg.size),
			"DstSamples":    unsafe.Offsetof(cCfg.dst_samples),
			"OutNumSamples": unsafe.Offsetof(cCfg.out_num_samples),
			"ErrorOut":      unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioEncoderConfigLayout() cStructLayout {
	var cCfg C.ShimAudioEncoderConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"SampleRate": unsafe.Offsetof(cCfg.sample_rate),
			"Channels":   unsafe.Offsetof(cCfg.channels),
			"BitrateBps": unsafe.Offsetof(cCfg.bitrate_bps),
		},
	}
}

func cShimAudioEncoderCreateParamsLayout() cStructLayout {
	var cCfg C.ShimAudioEncoderCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Config":   unsafe.Offsetof(cCfg.config),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioEncoderEncodeParamsLayout() cStructLayout {
	var cCfg C.ShimAudioEncoderEncodeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Samples":    unsafe.Offsetof(cCfg.samples),
			"NumSamples": unsafe.Offsetof(cCfg.num_samples),
			"DstBuffer":  unsafe.Offsetof(cCfg.dst_buffer),
			"OutSize":    unsafe.Offsetof(cCfg.out_size),
		},
	}
}

func cShimAudioEncoderSetBitrateParamsLayout() cStructLayout {
	var cCfg C.ShimAudioEncoderSetBitrateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Encoder":    unsafe.Offsetof(cCfg.encoder),
			"BitrateBps": unsafe.Offsetof(cCfg.bitrate_bps),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimAudioTrackSourceCreateParamsLayout() cStructLayout {
	var cCfg C.ShimAudioTrackSourceCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":         unsafe.Offsetof(cCfg.pc),
			"SampleRate": unsafe.Offsetof(cCfg.sample_rate),
			"Channels":   unsafe.Offsetof(cCfg.channels),
		},
	}
}

func cShimAudioTrackSourcePushFrameParamsLayout() cStructLayout {
	var cCfg C.ShimAudioTrackSourcePushFrameParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Source":      unsafe.Offsetof(cCfg.source),
			"Samples":     unsafe.Offsetof(cCfg.samples),
			"NumSamples":  unsafe.Offsetof(cCfg.num_samples),
			"TimestampUs": unsafe.Offsetof(cCfg.timestamp_us),
		},
	}
}

func cShimBandwidthEstimateLayout() cStructLayout {
	var cCfg C.ShimBandwidthEstimate
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"TimestampUs":      unsafe.Offsetof(cCfg.timestamp_us),
			"TargetBitrateBps": unsafe.Offsetof(cCfg.target_bitrate_bps),
			"AvailableSendBps": unsafe.Offsetof(cCfg.available_send_bps),
			"AvailableRecvBps": unsafe.Offsetof(cCfg.available_recv_bps),
			"PacingRateBps":    unsafe.Offsetof(cCfg.pacing_rate_bps),
			"CongestionWindow": unsafe.Offsetof(cCfg.congestion_window),
			"LossRate":         unsafe.Offsetof(cCfg.loss_rate),
		},
	}
}

func cShimCodecCapabilityLayout() cStructLayout {
	var cCfg C.ShimCodecCapability
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"MimeType":    unsafe.Offsetof(cCfg.mime_type),
			"ClockRate":   unsafe.Offsetof(cCfg.clock_rate),
			"Channels":    unsafe.Offsetof(cCfg.channels),
			"SDPFmtpLine": unsafe.Offsetof(cCfg.sdp_fmtp_line),
			"PayloadType": unsafe.Offsetof(cCfg.payload_type),
		},
	}
}

func cShimDataChannelSendParamsLayout() cStructLayout {
	var cCfg C.ShimDataChannelSendParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DC":       unsafe.Offsetof(cCfg.dc),
			"Data":     unsafe.Offsetof(cCfg.data),
			"Size":     unsafe.Offsetof(cCfg.size),
			"IsBinary": unsafe.Offsetof(cCfg.is_binary),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimDataChannelSetOnCloseParamsLayout() cStructLayout {
	var cCfg C.ShimDataChannelSetOnCloseParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DC":       unsafe.Offsetof(cCfg.dc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimDataChannelSetOnMessageParamsLayout() cStructLayout {
	var cCfg C.ShimDataChannelSetOnMessageParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DC":       unsafe.Offsetof(cCfg.dc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimDataChannelSetOnOpenParamsLayout() cStructLayout {
	var cCfg C.ShimDataChannelSetOnOpenParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DC":       unsafe.Offsetof(cCfg.dc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimDepacketizerPopParamsLayout() cStructLayout {
	var cCfg C.ShimDepacketizerPopParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Depacketizer":  unsafe.Offsetof(cCfg.depacketizer),
			"DstBuffer":     unsafe.Offsetof(cCfg.dst_buffer),
			"OutSize":       unsafe.Offsetof(cCfg.out_size),
			"OutTimestamp":  unsafe.Offsetof(cCfg.out_timestamp),
			"OutIsKeyframe": unsafe.Offsetof(cCfg.out_is_keyframe),
		},
	}
}

func cShimDepacketizerPushParamsLayout() cStructLayout {
	var cCfg C.ShimDepacketizerPushParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Depacketizer": unsafe.Offsetof(cCfg.depacketizer),
			"Data":         unsafe.Offsetof(cCfg.data),
			"Size":         unsafe.Offsetof(cCfg.size),
		},
	}
}

func cShimDeviceInfoLayout() cStructLayout {
	var cCfg C.ShimDeviceInfo
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"deviceID": unsafe.Offsetof(cCfg.device_id),
			"label":    unsafe.Offsetof(cCfg.label),
			"kind":     unsafe.Offsetof(cCfg.kind),
		},
	}
}

func cShimEnumerateDevicesParamsLayout() cStructLayout {
	var cCfg C.ShimEnumerateDevicesParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Devices":    unsafe.Offsetof(cCfg.devices),
			"MaxDevices": unsafe.Offsetof(cCfg.max_devices),
			"OutCount":   unsafe.Offsetof(cCfg.out_count),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimEnumerateScreensParamsLayout() cStructLayout {
	var cCfg C.ShimEnumerateScreensParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Screens":    unsafe.Offsetof(cCfg.screens),
			"MaxScreens": unsafe.Offsetof(cCfg.max_screens),
			"OutCount":   unsafe.Offsetof(cCfg.out_count),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimErrorBufferLayout() cStructLayout {
	var cCfg C.ShimErrorBuffer
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Message": unsafe.Offsetof(cCfg.message),
		},
	}
}

func cShimGetSupportedAudioCodecsParamsLayout() cStructLayout {
	var cCfg C.ShimGetSupportedAudioCodecsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codecs":    unsafe.Offsetof(cCfg.codecs),
			"MaxCodecs": unsafe.Offsetof(cCfg.max_codecs),
			"OutCount":  unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimGetSupportedVideoCodecsParamsLayout() cStructLayout {
	var cCfg C.ShimGetSupportedVideoCodecsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codecs":    unsafe.Offsetof(cCfg.codecs),
			"MaxCodecs": unsafe.Offsetof(cCfg.max_codecs),
			"OutCount":  unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimICECandidateLayout() cStructLayout {
	var cCfg C.ShimICECandidate
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Candidate":     unsafe.Offsetof(cCfg.candidate),
			"SDPMid":        unsafe.Offsetof(cCfg.sdp_mid),
			"SDPMLineIndex": unsafe.Offsetof(cCfg.sdp_mline_index),
		},
	}
}

func cShimICEServerLayout() cStructLayout {
	var cCfg C.ShimICEServer
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"URLs":       unsafe.Offsetof(cCfg.urls),
			"URLCount":   unsafe.Offsetof(cCfg.url_count),
			"Username":   unsafe.Offsetof(cCfg.username),
			"Credential": unsafe.Offsetof(cCfg.credential),
		},
	}
}

func cShimPacketizerConfigLayout() cStructLayout {
	var cCfg C.ShimPacketizerConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codec":       unsafe.Offsetof(cCfg.codec),
			"SSRC":        unsafe.Offsetof(cCfg.ssrc),
			"PayloadType": unsafe.Offsetof(cCfg.payload_type),
			"MTU":         unsafe.Offsetof(cCfg.mtu),
			"ClockRate":   unsafe.Offsetof(cCfg.clock_rate),
		},
	}
}

func cShimPacketizerPacketizeParamsLayout() cStructLayout {
	var cCfg C.ShimPacketizerPacketizeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Packetizer": unsafe.Offsetof(cCfg.packetizer),
			"Data":       unsafe.Offsetof(cCfg.data),
			"Size":       unsafe.Offsetof(cCfg.size),
			"Timestamp":  unsafe.Offsetof(cCfg.timestamp),
			"IsKeyframe": unsafe.Offsetof(cCfg.is_keyframe),
			"DstBuffer":  unsafe.Offsetof(cCfg.dst_buffer),
			"DstOffsets": unsafe.Offsetof(cCfg.dst_offsets),
			"DstSizes":   unsafe.Offsetof(cCfg.dst_sizes),
			"MaxPackets": unsafe.Offsetof(cCfg.max_packets),
			"OutCount":   unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimPeerConnectionAddAudioTrackFromSourceParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionAddAudioTrackFromSourceParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Source":   unsafe.Offsetof(cCfg.source),
			"TrackID":  unsafe.Offsetof(cCfg.track_id),
			"StreamID": unsafe.Offsetof(cCfg.stream_id),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionAddICECandidateParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionAddICECandidateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":            unsafe.Offsetof(cCfg.pc),
			"Candidate":     unsafe.Offsetof(cCfg.candidate),
			"SDPMid":        unsafe.Offsetof(cCfg.sdp_mid),
			"SDPMLineIndex": unsafe.Offsetof(cCfg.sdp_mline_index),
			"ErrorOut":      unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionAddTrackParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionAddTrackParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Codec":    unsafe.Offsetof(cCfg.codec),
			"TrackID":  unsafe.Offsetof(cCfg.track_id),
			"StreamID": unsafe.Offsetof(cCfg.stream_id),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionAddTransceiverParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionAddTransceiverParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":        unsafe.Offsetof(cCfg.pc),
			"Kind":      unsafe.Offsetof(cCfg.kind),
			"Direction": unsafe.Offsetof(cCfg.direction),
			"ErrorOut":  unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionAddVideoTrackFromSourceParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionAddVideoTrackFromSourceParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Source":   unsafe.Offsetof(cCfg.source),
			"TrackID":  unsafe.Offsetof(cCfg.track_id),
			"StreamID": unsafe.Offsetof(cCfg.stream_id),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionConfigLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"ICEServers":           unsafe.Offsetof(cCfg.ice_servers),
			"ICEServerCount":       unsafe.Offsetof(cCfg.ice_server_count),
			"ICECandidatePoolSize": unsafe.Offsetof(cCfg.ice_candidate_pool_size),
			"BundlePolicy":         unsafe.Offsetof(cCfg.bundle_policy),
			"RTCPMuxPolicy":        unsafe.Offsetof(cCfg.rtcp_mux_policy),
			"SDPSemantics":         unsafe.Offsetof(cCfg.sdp_semantics),
		},
	}
}

func cShimPeerConnectionCreateAnswerParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionCreateAnswerParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":         unsafe.Offsetof(cCfg.pc),
			"SDPOut":     unsafe.Offsetof(cCfg.sdp_out),
			"SDPOutSize": unsafe.Offsetof(cCfg.sdp_out_size),
			"OutSDPLen":  unsafe.Offsetof(cCfg.out_sdp_len),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionCreateDataChannelParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionCreateDataChannelParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":             unsafe.Offsetof(cCfg.pc),
			"Label":          unsafe.Offsetof(cCfg.label),
			"Ordered":        unsafe.Offsetof(cCfg.ordered),
			"MaxRetransmits": unsafe.Offsetof(cCfg.max_retransmits),
			"Protocol":       unsafe.Offsetof(cCfg.protocol),
			"ErrorOut":       unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionCreateOfferParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionCreateOfferParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":         unsafe.Offsetof(cCfg.pc),
			"SDPOut":     unsafe.Offsetof(cCfg.sdp_out),
			"SDPOutSize": unsafe.Offsetof(cCfg.sdp_out_size),
			"OutSDPLen":  unsafe.Offsetof(cCfg.out_sdp_len),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionCreateParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Config":   unsafe.Offsetof(cCfg.config),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionGetBandwidthEstimateParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionGetBandwidthEstimateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":          unsafe.Offsetof(cCfg.pc),
			"OutEstimate": unsafe.Offsetof(cCfg.out_estimate),
		},
	}
}

func cShimPeerConnectionGetReceiversParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionGetReceiversParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":           unsafe.Offsetof(cCfg.pc),
			"Receivers":    unsafe.Offsetof(cCfg.receivers),
			"MaxReceivers": unsafe.Offsetof(cCfg.max_receivers),
			"OutCount":     unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimPeerConnectionGetSendersParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionGetSendersParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":         unsafe.Offsetof(cCfg.pc),
			"Senders":    unsafe.Offsetof(cCfg.senders),
			"MaxSenders": unsafe.Offsetof(cCfg.max_senders),
			"OutCount":   unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimPeerConnectionGetStatsParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionGetStatsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"OutStats": unsafe.Offsetof(cCfg.out_stats),
		},
	}
}

func cShimPeerConnectionGetTransceiversParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionGetTransceiversParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":              unsafe.Offsetof(cCfg.pc),
			"Transceivers":    unsafe.Offsetof(cCfg.transceivers),
			"MaxTransceivers": unsafe.Offsetof(cCfg.max_transceivers),
			"OutCount":        unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimPeerConnectionRemoveTrackParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionRemoveTrackParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionSetLocalDescriptionParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetLocalDescriptionParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Type":     unsafe.Offsetof(cCfg._type),
			"SDP":      unsafe.Offsetof(cCfg.sdp),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimPeerConnectionSetOnBandwidthEstimateParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnBandwidthEstimateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnConnectionStateChangeParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnConnectionStateChangeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnDataChannelParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnDataChannelParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnICECandidateParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnICECandidateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnICEConnectionStateChangeParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnICEConnectionStateChangeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnICEGatheringStateChangeParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnICEGatheringStateChangeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnNegotiationNeededParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnNegotiationNeededParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnSignalingStateChangeParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnSignalingStateChangeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetOnTrackParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetOnTrackParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimPeerConnectionSetRemoteDescriptionParamsLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionSetRemoteDescriptionParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":       unsafe.Offsetof(cCfg.pc),
			"Type":     unsafe.Offsetof(cCfg._type),
			"SDP":      unsafe.Offsetof(cCfg.sdp),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTCStatsLayout() cStructLayout {
	var cCfg C.ShimRTCStats
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"TimestampUs":                 unsafe.Offsetof(cCfg.timestamp_us),
			"BytesSent":                   unsafe.Offsetof(cCfg.bytes_sent),
			"BytesReceived":               unsafe.Offsetof(cCfg.bytes_received),
			"PacketsSent":                 unsafe.Offsetof(cCfg.packets_sent),
			"PacketsReceived":             unsafe.Offsetof(cCfg.packets_received),
			"PacketsLost":                 unsafe.Offsetof(cCfg.packets_lost),
			"RoundTripTimeMs":             unsafe.Offsetof(cCfg.round_trip_time_ms),
			"JitterMs":                    unsafe.Offsetof(cCfg.jitter_ms),
			"AvailableOutgoingBitrate":    unsafe.Offsetof(cCfg.available_outgoing_bitrate),
			"AvailableIncomingBitrate":    unsafe.Offsetof(cCfg.available_incoming_bitrate),
			"CurrentRTTMs":                unsafe.Offsetof(cCfg.current_rtt_ms),
			"TotalRTTMs":                  unsafe.Offsetof(cCfg.total_rtt_ms),
			"ResponsesReceived":           unsafe.Offsetof(cCfg.responses_received),
			"FramesEncoded":               unsafe.Offsetof(cCfg.frames_encoded),
			"FramesDecoded":               unsafe.Offsetof(cCfg.frames_decoded),
			"FramesDropped":               unsafe.Offsetof(cCfg.frames_dropped),
			"KeyFramesEncoded":            unsafe.Offsetof(cCfg.key_frames_encoded),
			"KeyFramesDecoded":            unsafe.Offsetof(cCfg.key_frames_decoded),
			"NACKCount":                   unsafe.Offsetof(cCfg.nack_count),
			"PLICount":                    unsafe.Offsetof(cCfg.pli_count),
			"FIRCount":                    unsafe.Offsetof(cCfg.fir_count),
			"QPSum":                       unsafe.Offsetof(cCfg.qp_sum),
			"AudioLevel":                  unsafe.Offsetof(cCfg.audio_level),
			"TotalAudioEnergy":            unsafe.Offsetof(cCfg.total_audio_energy),
			"ConcealmentEvents":           unsafe.Offsetof(cCfg.concealment_events),
			"DataChannelsOpened":          unsafe.Offsetof(cCfg.data_channels_opened),
			"DataChannelsClosed":          unsafe.Offsetof(cCfg.data_channels_closed),
			"MessagesSent":                unsafe.Offsetof(cCfg.messages_sent),
			"MessagesReceived":            unsafe.Offsetof(cCfg.messages_received),
			"BytesSentDataChannel":        unsafe.Offsetof(cCfg.bytes_sent_data_channel),
			"BytesReceivedDataChannel":    unsafe.Offsetof(cCfg.bytes_received_data_channel),
			"QualityLimitationReason":     unsafe.Offsetof(cCfg.quality_limitation_reason),
			"QualityLimitationDurationMs": unsafe.Offsetof(cCfg.quality_limitation_duration_ms),
			"RemotePacketsLost":           unsafe.Offsetof(cCfg.remote_packets_lost),
			"RemoteJitterMs":              unsafe.Offsetof(cCfg.remote_jitter_ms),
			"RemoteRoundTripTimeMs":       unsafe.Offsetof(cCfg.remote_round_trip_time_ms),
			"JitterBufferDelayMs":         unsafe.Offsetof(cCfg.jitter_buffer_delay_ms),
			"JitterBufferTargetDelayMs":   unsafe.Offsetof(cCfg.jitter_buffer_target_delay_ms),
			"JitterBufferMinimumDelayMs":  unsafe.Offsetof(cCfg.jitter_buffer_minimum_delay_ms),
			"JitterBufferEmittedCount":    unsafe.Offsetof(cCfg.jitter_buffer_emitted_count),
		},
	}
}

func cShimRTPEncodingParametersLayout() cStructLayout {
	var cCfg C.ShimRTPEncodingParameters
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"RID":                   unsafe.Offsetof(cCfg.rid),
			"MaxBitrateBps":         unsafe.Offsetof(cCfg.max_bitrate_bps),
			"MinBitrateBps":         unsafe.Offsetof(cCfg.min_bitrate_bps),
			"MaxFramerate":          unsafe.Offsetof(cCfg.max_framerate),
			"ScaleResolutionDownBy": unsafe.Offsetof(cCfg.scale_resolution_down_by),
			"Active":                unsafe.Offsetof(cCfg.active),
			"ScalabilityMode":       unsafe.Offsetof(cCfg.scalability_mode),
		},
	}
}

func cShimRTPReceiverGetStatsParamsLayout() cStructLayout {
	var cCfg C.ShimRTPReceiverGetStatsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Receiver": unsafe.Offsetof(cCfg.receiver),
			"OutStats": unsafe.Offsetof(cCfg.out_stats),
		},
	}
}

func cShimRTPReceiverSetJitterBufferMinDelayParamsLayout() cStructLayout {
	var cCfg C.ShimRTPReceiverSetJitterBufferMinDelayParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Receiver":   unsafe.Offsetof(cCfg.receiver),
			"MinDelayMs": unsafe.Offsetof(cCfg.min_delay_ms),
		},
	}
}

func cShimRTPSendParametersLayout() cStructLayout {
	var cCfg C.ShimRTPSendParameters
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Encodings":     unsafe.Offsetof(cCfg.encodings),
			"EncodingCount": unsafe.Offsetof(cCfg.encoding_count),
			"TransactionID": unsafe.Offsetof(cCfg.transaction_id),
		},
	}
}

func cShimRTPSenderGetActiveLayersParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderGetActiveLayersParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":      unsafe.Offsetof(cCfg.sender),
			"OutSpatial":  unsafe.Offsetof(cCfg.out_spatial),
			"OutTemporal": unsafe.Offsetof(cCfg.out_temporal),
		},
	}
}

func cShimRTPSenderGetNegotiatedCodecsParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderGetNegotiatedCodecsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":    unsafe.Offsetof(cCfg.sender),
			"Codecs":    unsafe.Offsetof(cCfg.codecs),
			"MaxCodecs": unsafe.Offsetof(cCfg.max_codecs),
			"OutCount":  unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimRTPSenderGetParametersParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderGetParametersParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":       unsafe.Offsetof(cCfg.sender),
			"Encodings":    unsafe.Offsetof(cCfg.encodings),
			"MaxEncodings": unsafe.Offsetof(cCfg.max_encodings),
			"OutParams":    unsafe.Offsetof(cCfg.out_params),
		},
	}
}

func cShimRTPSenderGetScalabilityModeParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderGetScalabilityModeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":      unsafe.Offsetof(cCfg.sender),
			"ModeOut":     unsafe.Offsetof(cCfg.mode_out),
			"ModeOutSize": unsafe.Offsetof(cCfg.mode_out_size),
		},
	}
}

func cShimRTPSenderGetStatsParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderGetStatsParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"OutStats": unsafe.Offsetof(cCfg.out_stats),
		},
	}
}

func cShimRTPSenderReplaceTrackParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderReplaceTrackParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender": unsafe.Offsetof(cCfg.sender),
			"Track":  unsafe.Offsetof(cCfg.track),
		},
	}
}

func cShimRTPSenderSetBitrateParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetBitrateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"Bitrate":  unsafe.Offsetof(cCfg.bitrate),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTPSenderSetLayerActiveParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetLayerActiveParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"RID":      unsafe.Offsetof(cCfg.rid),
			"Active":   unsafe.Offsetof(cCfg.active),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTPSenderSetLayerBitrateParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetLayerBitrateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":        unsafe.Offsetof(cCfg.sender),
			"RID":           unsafe.Offsetof(cCfg.rid),
			"MaxBitrateBps": unsafe.Offsetof(cCfg.max_bitrate_bps),
			"ErrorOut":      unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTPSenderSetOnRTCPFeedbackParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetOnRTCPFeedbackParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimRTPSenderSetParametersParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetParametersParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":   unsafe.Offsetof(cCfg.sender),
			"Params":   unsafe.Offsetof(cCfg.params),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTPSenderSetPreferredCodecParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetPreferredCodecParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":      unsafe.Offsetof(cCfg.sender),
			"MimeType":    unsafe.Offsetof(cCfg.mime_type),
			"PayloadType": unsafe.Offsetof(cCfg.payload_type),
			"ErrorOut":    unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimRTPSenderSetScalabilityModeParamsLayout() cStructLayout {
	var cCfg C.ShimRTPSenderSetScalabilityModeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Sender":          unsafe.Offsetof(cCfg.sender),
			"ScalabilityMode": unsafe.Offsetof(cCfg.scalability_mode),
			"ErrorOut":        unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimScreenCaptureCreateParamsLayout() cStructLayout {
	var cCfg C.ShimScreenCaptureCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"ScreenOrWindowID": unsafe.Offsetof(cCfg.screen_or_window_id),
			"IsWindow":         unsafe.Offsetof(cCfg.is_window),
			"FPS":              unsafe.Offsetof(cCfg.fps),
			"ErrorOut":         unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimScreenCaptureStartParamsLayout() cStructLayout {
	var cCfg C.ShimScreenCaptureStartParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Cap":      unsafe.Offsetof(cCfg.cap),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimScreenInfoLayout() cStructLayout {
	var cCfg C.ShimScreenInfo
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"id":       unsafe.Offsetof(cCfg.id),
			"title":    unsafe.Offsetof(cCfg.title),
			"isWindow": unsafe.Offsetof(cCfg.is_window),
		},
	}
}

func cShimSessionDescriptionLayout() cStructLayout {
	var cCfg C.ShimSessionDescription
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Type": unsafe.Offsetof(cCfg._type),
			"SDP":  unsafe.Offsetof(cCfg.sdp),
		},
	}
}

func cShimTrackSetAudioSinkParamsLayout() cStructLayout {
	var cCfg C.ShimTrackSetAudioSinkParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Track":    unsafe.Offsetof(cCfg.track),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimTrackSetVideoSinkParamsLayout() cStructLayout {
	var cCfg C.ShimTrackSetVideoSinkParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Track":    unsafe.Offsetof(cCfg.track),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
		},
	}
}

func cShimTransceiverGetCodecPreferencesParamsLayout() cStructLayout {
	var cCfg C.ShimTransceiverGetCodecPreferencesParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Transceiver": unsafe.Offsetof(cCfg.transceiver),
			"Codecs":      unsafe.Offsetof(cCfg.codecs),
			"MaxCodecs":   unsafe.Offsetof(cCfg.max_codecs),
			"OutCount":    unsafe.Offsetof(cCfg.out_count),
		},
	}
}

func cShimTransceiverSetCodecPreferencesParamsLayout() cStructLayout {
	var cCfg C.ShimTransceiverSetCodecPreferencesParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Transceiver": unsafe.Offsetof(cCfg.transceiver),
			"Codecs":      unsafe.Offsetof(cCfg.codecs),
			"Count":       unsafe.Offsetof(cCfg.count),
			"ErrorOut":    unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimTransceiverSetDirectionParamsLayout() cStructLayout {
	var cCfg C.ShimTransceiverSetDirectionParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Transceiver": unsafe.Offsetof(cCfg.transceiver),
			"Direction":   unsafe.Offsetof(cCfg.direction),
			"ErrorOut":    unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimTransceiverStopParamsLayout() cStructLayout {
	var cCfg C.ShimTransceiverStopParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Transceiver": unsafe.Offsetof(cCfg.transceiver),
			"ErrorOut":    unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoCaptureCreateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoCaptureCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"DeviceID": unsafe.Offsetof(cCfg.device_id),
			"Width":    unsafe.Offsetof(cCfg.width),
			"Height":   unsafe.Offsetof(cCfg.height),
			"FPS":      unsafe.Offsetof(cCfg.fps),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoCaptureStartParamsLayout() cStructLayout {
	var cCfg C.ShimVideoCaptureStartParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Cap":      unsafe.Offsetof(cCfg.cap),
			"Callback": unsafe.Offsetof(cCfg.callback),
			"Ctx":      unsafe.Offsetof(cCfg.ctx),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoDecoderCreateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoDecoderCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codec":    unsafe.Offsetof(cCfg.codec),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoDecoderDecodeParamsLayout() cStructLayout {
	var cCfg C.ShimVideoDecoderDecodeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Data":       unsafe.Offsetof(cCfg.data),
			"Size":       unsafe.Offsetof(cCfg.size),
			"Timestamp":  unsafe.Offsetof(cCfg.timestamp),
			"IsKeyframe": unsafe.Offsetof(cCfg.is_keyframe),
			"YDst":       unsafe.Offsetof(cCfg.y_dst),
			"UDst":       unsafe.Offsetof(cCfg.u_dst),
			"VDst":       unsafe.Offsetof(cCfg.v_dst),
			"OutWidth":   unsafe.Offsetof(cCfg.out_width),
			"OutHeight":  unsafe.Offsetof(cCfg.out_height),
			"OutYStride": unsafe.Offsetof(cCfg.out_y_stride),
			"OutUStride": unsafe.Offsetof(cCfg.out_u_stride),
			"OutVStride": unsafe.Offsetof(cCfg.out_v_stride),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoEncoderConfigLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Width":            unsafe.Offsetof(cCfg.width),
			"Height":           unsafe.Offsetof(cCfg.height),
			"BitrateBps":       unsafe.Offsetof(cCfg.bitrate_bps),
			"Framerate":        unsafe.Offsetof(cCfg.framerate),
			"KeyframeInterval": unsafe.Offsetof(cCfg.keyframe_interval),
			"H264Profile":      unsafe.Offsetof(cCfg.h264_profile),
			"VP9Profile":       unsafe.Offsetof(cCfg.vp9_profile),
			"PreferHW":         unsafe.Offsetof(cCfg.prefer_hw),
		},
	}
}

func cShimVideoEncoderCreateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codec":    unsafe.Offsetof(cCfg.codec),
			"Config":   unsafe.Offsetof(cCfg.config),
			"ErrorOut": unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoEncoderEncodeParamsLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderEncodeParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"YPlane":        unsafe.Offsetof(cCfg.y_plane),
			"UPlane":        unsafe.Offsetof(cCfg.u_plane),
			"VPlane":        unsafe.Offsetof(cCfg.v_plane),
			"YStride":       unsafe.Offsetof(cCfg.y_stride),
			"UStride":       unsafe.Offsetof(cCfg.u_stride),
			"VStride":       unsafe.Offsetof(cCfg.v_stride),
			"Timestamp":     unsafe.Offsetof(cCfg.timestamp),
			"ForceKeyframe": unsafe.Offsetof(cCfg.force_keyframe),
			"DstBuffer":     unsafe.Offsetof(cCfg.dst_buffer),
			"DstBufferSize": unsafe.Offsetof(cCfg.dst_buffer_size),
			"OutSize":       unsafe.Offsetof(cCfg.out_size),
			"OutIsKeyframe": unsafe.Offsetof(cCfg.out_is_keyframe),
			"ErrorOut":      unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoEncoderSetBitrateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderSetBitrateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Encoder":    unsafe.Offsetof(cCfg.encoder),
			"BitrateBps": unsafe.Offsetof(cCfg.bitrate_bps),
			"ErrorOut":   unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoEncoderSetFramerateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderSetFramerateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Encoder":   unsafe.Offsetof(cCfg.encoder),
			"Framerate": unsafe.Offsetof(cCfg.framerate),
			"ErrorOut":  unsafe.Offsetof(cCfg.error_out),
		},
	}
}

func cShimVideoTrackSourceCreateParamsLayout() cStructLayout {
	var cCfg C.ShimVideoTrackSourceCreateParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"PC":     unsafe.Offsetof(cCfg.pc),
			"Width":  unsafe.Offsetof(cCfg.width),
			"Height": unsafe.Offsetof(cCfg.height),
		},
	}
}

func cShimVideoTrackSourcePushFrameParamsLayout() cStructLayout {
	var cCfg C.ShimVideoTrackSourcePushFrameParams
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Source":      unsafe.Offsetof(cCfg.source),
			"YPlane":      unsafe.Offsetof(cCfg.y_plane),
			"UPlane":      unsafe.Offsetof(cCfg.u_plane),
			"VPlane":      unsafe.Offsetof(cCfg.v_plane),
			"YStride":     unsafe.Offsetof(cCfg.y_stride),
			"UStride":     unsafe.Offsetof(cCfg.u_stride),
			"VStride":     unsafe.Offsetof(cCfg.v_stride),
			"TimestampUs": unsafe.Offsetof(cCfg.timestamp_us),
		},
	}
}
