// Code generated by go generate; DO NOT EDIT.

//go:build ffigo_cgo

package ffi

/*
#cgo CFLAGS: -I${SRCDIR}/../../shim
#include "shim.h"
*/
import "C"

import "unsafe"

type cStructLayout struct {
	size    uintptr
	offsets map[string]uintptr
}

func cShimAudioEncoderConfigLayout() cStructLayout {
	var cCfg C.ShimAudioEncoderConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"SampleRate": unsafe.Offsetof(cCfg.sample_rate),
			"Channels":   unsafe.Offsetof(cCfg.channels),
			"BitrateBps": unsafe.Offsetof(cCfg.bitrate_bps),
		},
	}
}

func cShimBandwidthEstimateLayout() cStructLayout {
	var cCfg C.ShimBandwidthEstimate
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"TimestampUs":      unsafe.Offsetof(cCfg.timestamp_us),
			"TargetBitrateBps": unsafe.Offsetof(cCfg.target_bitrate_bps),
			"AvailableSendBps": unsafe.Offsetof(cCfg.available_send_bps),
			"AvailableRecvBps": unsafe.Offsetof(cCfg.available_recv_bps),
			"PacingRateBps":    unsafe.Offsetof(cCfg.pacing_rate_bps),
			"CongestionWindow": unsafe.Offsetof(cCfg.congestion_window),
			"LossRate":         unsafe.Offsetof(cCfg.loss_rate),
		},
	}
}

func cShimCodecCapabilityLayout() cStructLayout {
	var cCfg C.ShimCodecCapability
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"MimeType":    unsafe.Offsetof(cCfg.mime_type),
			"ClockRate":   unsafe.Offsetof(cCfg.clock_rate),
			"Channels":    unsafe.Offsetof(cCfg.channels),
			"SDPFmtpLine": unsafe.Offsetof(cCfg.sdp_fmtp_line),
			"PayloadType": unsafe.Offsetof(cCfg.payload_type),
		},
	}
}

func cShimDeviceInfoLayout() cStructLayout {
	var cCfg C.ShimDeviceInfo
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"deviceID": unsafe.Offsetof(cCfg.device_id),
			"label":    unsafe.Offsetof(cCfg.label),
			"kind":     unsafe.Offsetof(cCfg.kind),
		},
	}
}

func cShimErrorBufferLayout() cStructLayout {
	var cCfg C.ShimErrorBuffer
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Message": unsafe.Offsetof(cCfg.message),
		},
	}
}

func cShimICECandidateLayout() cStructLayout {
	var cCfg C.ShimICECandidate
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Candidate":     unsafe.Offsetof(cCfg.candidate),
			"SDPMid":        unsafe.Offsetof(cCfg.sdp_mid),
			"SDPMLineIndex": unsafe.Offsetof(cCfg.sdp_mline_index),
		},
	}
}

func cShimICEServerLayout() cStructLayout {
	var cCfg C.ShimICEServer
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"URLs":       unsafe.Offsetof(cCfg.urls),
			"URLCount":   unsafe.Offsetof(cCfg.url_count),
			"Username":   unsafe.Offsetof(cCfg.username),
			"Credential": unsafe.Offsetof(cCfg.credential),
		},
	}
}

func cShimPacketizerConfigLayout() cStructLayout {
	var cCfg C.ShimPacketizerConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Codec":       unsafe.Offsetof(cCfg.codec),
			"SSRC":        unsafe.Offsetof(cCfg.ssrc),
			"PayloadType": unsafe.Offsetof(cCfg.payload_type),
			"MTU":         unsafe.Offsetof(cCfg.mtu),
			"ClockRate":   unsafe.Offsetof(cCfg.clock_rate),
		},
	}
}

func cShimPeerConnectionConfigLayout() cStructLayout {
	var cCfg C.ShimPeerConnectionConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"ICEServers":           unsafe.Offsetof(cCfg.ice_servers),
			"ICEServerCount":       unsafe.Offsetof(cCfg.ice_server_count),
			"ICECandidatePoolSize": unsafe.Offsetof(cCfg.ice_candidate_pool_size),
			"BundlePolicy":         unsafe.Offsetof(cCfg.bundle_policy),
			"RTCPMuxPolicy":        unsafe.Offsetof(cCfg.rtcp_mux_policy),
			"SDPSemantics":         unsafe.Offsetof(cCfg.sdp_semantics),
		},
	}
}

func cShimRTCStatsLayout() cStructLayout {
	var cCfg C.ShimRTCStats
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"TimestampUs":                 unsafe.Offsetof(cCfg.timestamp_us),
			"BytesSent":                   unsafe.Offsetof(cCfg.bytes_sent),
			"BytesReceived":               unsafe.Offsetof(cCfg.bytes_received),
			"PacketsSent":                 unsafe.Offsetof(cCfg.packets_sent),
			"PacketsReceived":             unsafe.Offsetof(cCfg.packets_received),
			"PacketsLost":                 unsafe.Offsetof(cCfg.packets_lost),
			"RoundTripTimeMs":             unsafe.Offsetof(cCfg.round_trip_time_ms),
			"JitterMs":                    unsafe.Offsetof(cCfg.jitter_ms),
			"AvailableOutgoingBitrate":    unsafe.Offsetof(cCfg.available_outgoing_bitrate),
			"AvailableIncomingBitrate":    unsafe.Offsetof(cCfg.available_incoming_bitrate),
			"CurrentRTTMs":                unsafe.Offsetof(cCfg.current_rtt_ms),
			"TotalRTTMs":                  unsafe.Offsetof(cCfg.total_rtt_ms),
			"ResponsesReceived":           unsafe.Offsetof(cCfg.responses_received),
			"FramesEncoded":               unsafe.Offsetof(cCfg.frames_encoded),
			"FramesDecoded":               unsafe.Offsetof(cCfg.frames_decoded),
			"FramesDropped":               unsafe.Offsetof(cCfg.frames_dropped),
			"KeyFramesEncoded":            unsafe.Offsetof(cCfg.key_frames_encoded),
			"KeyFramesDecoded":            unsafe.Offsetof(cCfg.key_frames_decoded),
			"NACKCount":                   unsafe.Offsetof(cCfg.nack_count),
			"PLICount":                    unsafe.Offsetof(cCfg.pli_count),
			"FIRCount":                    unsafe.Offsetof(cCfg.fir_count),
			"QPSum":                       unsafe.Offsetof(cCfg.qp_sum),
			"AudioLevel":                  unsafe.Offsetof(cCfg.audio_level),
			"TotalAudioEnergy":            unsafe.Offsetof(cCfg.total_audio_energy),
			"ConcealmentEvents":           unsafe.Offsetof(cCfg.concealment_events),
			"DataChannelsOpened":          unsafe.Offsetof(cCfg.data_channels_opened),
			"DataChannelsClosed":          unsafe.Offsetof(cCfg.data_channels_closed),
			"MessagesSent":                unsafe.Offsetof(cCfg.messages_sent),
			"MessagesReceived":            unsafe.Offsetof(cCfg.messages_received),
			"BytesSentDataChannel":        unsafe.Offsetof(cCfg.bytes_sent_data_channel),
			"BytesReceivedDataChannel":    unsafe.Offsetof(cCfg.bytes_received_data_channel),
			"QualityLimitationReason":     unsafe.Offsetof(cCfg.quality_limitation_reason),
			"QualityLimitationDurationMs": unsafe.Offsetof(cCfg.quality_limitation_duration_ms),
			"RemotePacketsLost":           unsafe.Offsetof(cCfg.remote_packets_lost),
			"RemoteJitterMs":              unsafe.Offsetof(cCfg.remote_jitter_ms),
			"RemoteRoundTripTimeMs":       unsafe.Offsetof(cCfg.remote_round_trip_time_ms),
			"JitterBufferDelayMs":         unsafe.Offsetof(cCfg.jitter_buffer_delay_ms),
			"JitterBufferTargetDelayMs":   unsafe.Offsetof(cCfg.jitter_buffer_target_delay_ms),
			"JitterBufferMinimumDelayMs":  unsafe.Offsetof(cCfg.jitter_buffer_minimum_delay_ms),
			"JitterBufferEmittedCount":    unsafe.Offsetof(cCfg.jitter_buffer_emitted_count),
		},
	}
}

func cShimRTPEncodingParametersLayout() cStructLayout {
	var cCfg C.ShimRTPEncodingParameters
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"RID":                   unsafe.Offsetof(cCfg.rid),
			"MaxBitrateBps":         unsafe.Offsetof(cCfg.max_bitrate_bps),
			"MinBitrateBps":         unsafe.Offsetof(cCfg.min_bitrate_bps),
			"MaxFramerate":          unsafe.Offsetof(cCfg.max_framerate),
			"ScaleResolutionDownBy": unsafe.Offsetof(cCfg.scale_resolution_down_by),
			"Active":                unsafe.Offsetof(cCfg.active),
			"ScalabilityMode":       unsafe.Offsetof(cCfg.scalability_mode),
		},
	}
}

func cShimRTPSendParametersLayout() cStructLayout {
	var cCfg C.ShimRTPSendParameters
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Encodings":     unsafe.Offsetof(cCfg.encodings),
			"EncodingCount": unsafe.Offsetof(cCfg.encoding_count),
			"TransactionID": unsafe.Offsetof(cCfg.transaction_id),
		},
	}
}

func cShimScreenInfoLayout() cStructLayout {
	var cCfg C.ShimScreenInfo
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"id":       unsafe.Offsetof(cCfg.id),
			"title":    unsafe.Offsetof(cCfg.title),
			"isWindow": unsafe.Offsetof(cCfg.is_window),
		},
	}
}

func cShimSessionDescriptionLayout() cStructLayout {
	var cCfg C.ShimSessionDescription
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Type": unsafe.Offsetof(cCfg._type),
			"SDP":  unsafe.Offsetof(cCfg.sdp),
		},
	}
}

func cShimVideoEncoderConfigLayout() cStructLayout {
	var cCfg C.ShimVideoEncoderConfig
	return cStructLayout{
		size: unsafe.Sizeof(cCfg),
		offsets: map[string]uintptr{
			"Width":            unsafe.Offsetof(cCfg.width),
			"Height":           unsafe.Offsetof(cCfg.height),
			"BitrateBps":       unsafe.Offsetof(cCfg.bitrate_bps),
			"Framerate":        unsafe.Offsetof(cCfg.framerate),
			"KeyframeInterval": unsafe.Offsetof(cCfg.keyframe_interval),
			"H264Profile":      unsafe.Offsetof(cCfg.h264_profile),
			"VP9Profile":       unsafe.Offsetof(cCfg.vp9_profile),
			"PreferHW":         unsafe.Offsetof(cCfg.prefer_hw),
		},
	}
}
