#!/bin/bash
#
# Build libwebrtc from source at a pinned revision and install it into a local
# prefix that libgowebrtc's Bazel build can consume.
#
# Linux builds use use_custom_libcxx=false so the resulting libwebrtc archive
# links cleanly with the shim's libstdc++-based toolchain.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

WEBRTC_GIT_REV="${WEBRTC_GIT_REV:-d2eaa5570fc9959f8dbde32912a16366b8ee75f4}"
WEBRTC_BRANCH_HEAD="${WEBRTC_BRANCH_HEAD:-7390}"
WEBRTC_CACHE_DIR="${WEBRTC_CACHE_DIR:-$HOME/.cache/libgowebrtc/webrtc}"
DEPOT_TOOLS_DIR="${DEPOT_TOOLS_DIR:-$HOME/.cache/libgowebrtc/depot_tools}"
TARGET_PLATFORM="${TARGET_PLATFORM:-}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/libwebrtc}"
WEBRTC_INSTALL_BUILD_DEPS="${WEBRTC_INSTALL_BUILD_DEPS:-0}"
WEBRTC_GCLIENT_JOBS="${WEBRTC_GCLIENT_JOBS:-2}"

log_info()    { echo -e "\033[0;34m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; }
log_error()   { echo -e "\033[0;31m[ERROR]\033[0m $1"; }
log_warn()    { echo -e "\033[0;33m[WARN]\033[0m $1"; }
log_step()    { echo -e "\n\033[0;32m==>\033[0m \033[0;34m$1\033[0m"; }

detect_platform() {
    local os cpu
    case "$(uname -s)" in
        Darwin) os="darwin" ;;
        Linux)  os="linux" ;;
        *)      os="unknown" ;;
    esac
    case "$(uname -m)" in
        i386|i486|i586|i686|x86) cpu="386" ;;
        arm64|aarch64) cpu="arm64" ;;
        armv7l|armv7|armv6l|armv6|armhf) cpu="arm" ;;
        x86_64|amd64|AMD64) cpu="amd64" ;;
        *) cpu="unknown" ;;
    esac
    echo "${os}_${cpu}"
}

show_help() {
    cat <<EOF
Build libwebrtc from source at a pinned revision.

Usage: ./scripts/build_libwebrtc_source.sh [OPTIONS]

Options:
  --target PLATFORM      Target platform (darwin_arm64, darwin_amd64, linux_386, linux_amd64, linux_arm64, linux_arm)
  --install-dir DIR      Install prefix for the built archive and headers
  --install-build-deps   Run WebRTC's Linux build dependency installer
  --help                 Show this help

Environment:
  WEBRTC_GIT_REV             Pinned WebRTC revision (default: $WEBRTC_GIT_REV)
  WEBRTC_BRANCH_HEAD         Informational branch-head marker (default: $WEBRTC_BRANCH_HEAD)
  WEBRTC_CACHE_DIR           Checkout/cache location (default: $WEBRTC_CACHE_DIR)
  DEPOT_TOOLS_DIR            depot_tools checkout location (default: $DEPOT_TOOLS_DIR)
  WEBRTC_INSTALL_BUILD_DEPS  Linux-only dependency bootstrap flag (default: $WEBRTC_INSTALL_BUILD_DEPS)
  WEBRTC_GCLIENT_JOBS        gclient parallelism (default: $WEBRTC_GCLIENT_JOBS)

Examples:
  ./scripts/build_libwebrtc_source.sh --target linux_amd64 --install-dir /tmp/libwebrtc
  ./scripts/build_libwebrtc_source.sh --target linux_386 --install-dir /tmp/libwebrtc_x86
  WEBRTC_INSTALL_BUILD_DEPS=1 ./scripts/build_libwebrtc_source.sh --target linux_arm64
EOF
    exit 0
}

target_os_for() {
    case "$1" in
        darwin_*) echo "mac" ;;
        linux_*) echo "linux" ;;
        *) return 1 ;;
    esac
}

out_dir_for() {
    case "$1" in
        darwin_arm64) echo "out/libgowebrtc-darwin-arm64" ;;
        darwin_amd64) echo "out/libgowebrtc-darwin-amd64" ;;
        linux_386)    echo "out/libgowebrtc-linux-x86" ;;
        linux_amd64)  echo "out/libgowebrtc-linux-amd64" ;;
        linux_arm64)  echo "out/libgowebrtc-linux-arm64" ;;
        linux_arm)    echo "out/libgowebrtc-linux-arm" ;;
        *) return 1 ;;
    esac
}

gn_args_for() {
    case "$1" in
        darwin_arm64)
            cat <<'EOF'
target_os="mac"
target_cpu="arm64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
EOF
            ;;
        darwin_amd64)
            cat <<'EOF'
target_os="mac"
target_cpu="x64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
EOF
            ;;
        linux_386)
            cat <<'EOF'
target_os="linux"
target_cpu="x86"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
EOF
            ;;
        linux_amd64)
            cat <<'EOF'
target_os="linux"
target_cpu="x64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
EOF
            ;;
        linux_arm64)
            cat <<'EOF'
target_os="linux"
target_cpu="arm64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
EOF
            ;;
        linux_arm)
            cat <<'EOF'
target_os="linux"
target_cpu="arm"
target_arm_version=7
arm_use_neon=true
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
EOF
            ;;
        *)
            return 1
            ;;
    esac
}

ensure_depot_tools() {
    if [[ -x "$DEPOT_TOOLS_DIR/fetch" && -x "$DEPOT_TOOLS_DIR/gclient" ]]; then
        return
    fi

    log_step "Installing depot_tools"
    mkdir -p "$(dirname "$DEPOT_TOOLS_DIR")"
    rm -rf "$DEPOT_TOOLS_DIR"
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git "$DEPOT_TOOLS_DIR"
}

bootstrap_depot_tools() {
    export DEPOT_TOOLS_DIR
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
    export DEPOT_TOOLS_METRICS=0

    if [[ -f "$DEPOT_TOOLS_DIR/python3_bin_reldir.txt" ]]; then
        return
    fi

    log_step "Bootstrapping depot_tools"
    "$DEPOT_TOOLS_DIR/ensure_bootstrap"
}

retry_command() {
    local attempts="$1"
    local delay_seconds="$2"
    shift 2

    local try=1
    while true; do
        if "$@"; then
            return 0
        fi

        if (( try >= attempts )); then
            return 1
        fi

        log_warn "Command failed (attempt $try/$attempts): $*"
        log_warn "Retrying in ${delay_seconds}s..."
        sleep "$delay_seconds"
        try=$((try + 1))
        delay_seconds=$((delay_seconds * 2))
    done
}

sync_webrtc_checkout() {
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
    export GCLIENT_PY3=1
    export GCLIENT_SUPPRESS_GIT_VERSION_WARNING=1
    export DEPOT_TOOLS_METRICS=0
    export DEPOT_TOOLS_UPDATE=0

    mkdir -p "$WEBRTC_CACHE_DIR"
    cd "$WEBRTC_CACHE_DIR"

    if [[ ! -d "$WEBRTC_CACHE_DIR/src/.git" ]]; then
        log_step "Fetching WebRTC source"
        fetch --nohooks --no-history webrtc
    fi

    log_step "Syncing WebRTC source"
    cd "$WEBRTC_CACHE_DIR/src"
    retry_command 4 15 git fetch https://webrtc.googlesource.com/src "$WEBRTC_GIT_REV" --depth 1
    git checkout --detach "$WEBRTC_GIT_REV"

    cd "$WEBRTC_CACHE_DIR"
    retry_command 4 30 gclient sync \
        --revision "src@$WEBRTC_GIT_REV" \
        --with_branch_heads \
        --shallow \
        --no-history \
        --jobs "$WEBRTC_GCLIENT_JOBS" \
        --reset \
        --force
}

maybe_install_linux_build_deps() {
    local target_os
    target_os="$(target_os_for "$TARGET_PLATFORM")"
    if [[ "$target_os" != "linux" || "$WEBRTC_INSTALL_BUILD_DEPS" != "1" ]]; then
        return
    fi

    local install_script="$WEBRTC_CACHE_DIR/src/build/install-build-deps.sh"
    if [[ ! -x "$install_script" ]]; then
        log_error "Missing Linux dependency installer: $install_script"
        exit 1
    fi

    log_step "Installing WebRTC Linux build dependencies"
    "$install_script" --no-prompt --no-chromeos-fonts

    if [[ "$TARGET_PLATFORM" != "linux_386" ]]; then
        return
    fi

    if ! command -v apt-get >/dev/null 2>&1; then
        log_warn "linux_386 source builds need a 32-bit multilib toolchain; install gcc-multilib/g++-multilib manually on this distro"
        return
    fi

    local sudo_cmd=()
    if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
        if ! command -v sudo >/dev/null 2>&1; then
            log_error "linux_386 source builds need sudo or root to install multilib packages"
            exit 1
        fi
        sudo_cmd=(sudo)
    fi

    log_step "Installing Linux x86 multilib build dependencies"
    "${sudo_cmd[@]}" dpkg --add-architecture i386
    "${sudo_cmd[@]}" apt-get update
    "${sudo_cmd[@]}" apt-get install -y \
        gcc-multilib \
        g++-multilib \
        libc6-dev-i386 \
        lib32gcc-s1 \
        lib32stdc++6 \
        libdrm-dev:i386 \
        libgbm-dev:i386 \
        libglib2.0-dev:i386 \
        libx11-dev:i386 \
        libxcomposite-dev:i386 \
        libxdamage-dev:i386 \
        libxext-dev:i386 \
        libxfixes-dev:i386 \
        libxrandr-dev:i386 \
        libxrender-dev:i386 \
        libxtst-dev:i386
}

build_webrtc() {
    export PATH="$DEPOT_TOOLS_DIR:$PATH"

    local out_dir gn_args
    out_dir="$(out_dir_for "$TARGET_PLATFORM")"
    gn_args="$(gn_args_for "$TARGET_PLATFORM")"

    log_step "Generating GN files"
    cd "$WEBRTC_CACHE_DIR/src"
    gn gen "$out_dir" --args="$gn_args"

    log_step "Building libwebrtc"
    ninja -C "$out_dir" webrtc
}

install_webrtc() {
    local out_dir archive obj_dir
    out_dir="$(out_dir_for "$TARGET_PLATFORM")"
    archive="$WEBRTC_CACHE_DIR/src/$out_dir/obj/libwebrtc.a"
    obj_dir="$WEBRTC_CACHE_DIR/src/$out_dir/obj"

    if [[ ! -f "$archive" ]]; then
        log_error "Built archive not found: $archive"
        exit 1
    fi

    log_step "Installing libwebrtc"
    mkdir -p "$INSTALL_DIR/include" "$INSTALL_DIR/lib"
    cp "$archive" "$INSTALL_DIR/lib/libwebrtc.a"

    # The monolithic libwebrtc.a does not include every helper archive we need
    # for the shim link (for example the builtin video factory archives), so
    # install the full static-lib tree alongside it.
    mkdir -p "$INSTALL_DIR/lib/obj"
    rsync -a --delete --prune-empty-dirs \
        --include='*/' \
        --include='*.a' \
        --exclude='*' \
        "$obj_dir/" "$INSTALL_DIR/lib/obj/"
    rm -f "$INSTALL_DIR/lib/obj/libwebrtc.a"

    rsync -a --delete --prune-empty-dirs \
        --include='*/' \
        --include='*.h' \
        --include='*.hpp' \
        --include='*.inc' \
        --exclude='*' \
        "$WEBRTC_CACHE_DIR/src/" "$INSTALL_DIR/include/"

    printf '%s\n' "$WEBRTC_GIT_REV" > "$INSTALL_DIR/VERSION"
    printf 'branch-heads/%s\n' "$WEBRTC_BRANCH_HEAD" > "$INSTALL_DIR/WEBRTC_BRANCH"
    printf 'source-build\n' > "$INSTALL_DIR/.libgowebrtc-source-build"

    log_success "Installed source-built libwebrtc to $INSTALL_DIR"
}

main() {
    if [[ -z "$TARGET_PLATFORM" ]]; then
        TARGET_PLATFORM="$(detect_platform)"
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --target)
                TARGET_PLATFORM="$2"
                shift 2
                ;;
            --install-dir)
                INSTALL_DIR="$2"
                shift 2
                ;;
            --install-build-deps)
                WEBRTC_INSTALL_BUILD_DEPS=1
                shift
                ;;
            --help)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    case "$TARGET_PLATFORM" in
        darwin_arm64|darwin_amd64|linux_386|linux_amd64|linux_arm64|linux_arm) ;;
        *)
            log_error "Unsupported target platform: $TARGET_PLATFORM"
            exit 1
            ;;
    esac

    log_info "Target platform: $TARGET_PLATFORM"
    log_info "Pinned WebRTC revision: $WEBRTC_GIT_REV"
    log_info "Branch head: $WEBRTC_BRANCH_HEAD"
    log_info "Cache dir: $WEBRTC_CACHE_DIR"
    log_info "Install dir: $INSTALL_DIR"

    ensure_depot_tools
    bootstrap_depot_tools
    sync_webrtc_checkout
    maybe_install_linux_build_deps
    build_webrtc
    install_webrtc
}

main "$@"
