#!/bin/bash
#
# Build libwebrtc from source at a pinned revision and install it into a local
# prefix that libgowebrtc's Bazel build can consume.
#
# Linux builds use use_custom_libcxx=false so the resulting libwebrtc archive
# links cleanly with the shim's libstdc++-based toolchain.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

WEBRTC_GIT_REV="${WEBRTC_GIT_REV:-d2eaa5570fc9959f8dbde32912a16366b8ee75f4}"
WEBRTC_BRANCH_HEAD="${WEBRTC_BRANCH_HEAD:-7390}"
WEBRTC_SOURCE_URL="${WEBRTC_SOURCE_URL:-https://webrtc.googlesource.com/src.git}"
WEBRTC_CACHE_DIR="${WEBRTC_CACHE_DIR:-}"
DEPOT_TOOLS_DIR="${DEPOT_TOOLS_DIR:-}"
TARGET_PLATFORM="${TARGET_PLATFORM:-}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/libwebrtc}"
WEBRTC_INSTALL_BUILD_DEPS="${WEBRTC_INSTALL_BUILD_DEPS:-0}"
WEBRTC_GCLIENT_JOBS="${WEBRTC_GCLIENT_JOBS:-2}"

log_info()    { echo -e "\033[0;34m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; }
log_error()   { echo -e "\033[0;31m[ERROR]\033[0m $1"; }
log_warn()    { echo -e "\033[0;33m[WARN]\033[0m $1"; }
log_step()    { echo -e "\n\033[0;32m==>\033[0m \033[0;34m$1\033[0m"; }

detect_platform() {
    local os cpu
    case "$(uname -s)" in
        Darwin) os="darwin" ;;
        Linux)  os="linux" ;;
        *)      os="unknown" ;;
    esac
    case "$(uname -m)" in
        i386|i486|i586|i686|x86) cpu="386" ;;
        arm64|aarch64) cpu="arm64" ;;
        armv7l|armv7|armv6l|armv6|armhf) cpu="arm" ;;
        x86_64|amd64|AMD64) cpu="amd64" ;;
        *) cpu="unknown" ;;
    esac
    echo "${os}_${cpu}"
}

HOST_PLATFORM="$(detect_platform)"
DEFAULT_CACHE_ROOT="$HOME/.cache/libgowebrtc/$HOST_PLATFORM"

if [[ -z "$WEBRTC_CACHE_DIR" ]]; then
    WEBRTC_CACHE_DIR="$DEFAULT_CACHE_ROOT/webrtc"
fi

if [[ -z "$DEPOT_TOOLS_DIR" ]]; then
    DEPOT_TOOLS_DIR="$DEFAULT_CACHE_ROOT/depot_tools"
fi

show_help() {
    cat <<EOF
Build libwebrtc from source at a pinned revision.

Usage: ./scripts/build_libwebrtc_source.sh [OPTIONS]

Options:
  --target PLATFORM      Target platform (darwin_arm64, darwin_amd64, linux_386, linux_amd64, linux_arm64, linux_arm)
  --install-dir DIR      Install prefix for the built archive and headers
  --install-build-deps   Run WebRTC's Linux build dependency installer
  --help                 Show this help

Environment:
  WEBRTC_GIT_REV             Pinned WebRTC revision (default: $WEBRTC_GIT_REV)
  WEBRTC_BRANCH_HEAD         Informational branch-head marker (default: $WEBRTC_BRANCH_HEAD)
  WEBRTC_CACHE_DIR           Checkout/cache location (default: $WEBRTC_CACHE_DIR)
  DEPOT_TOOLS_DIR            depot_tools checkout location (default: $DEPOT_TOOLS_DIR)
  WEBRTC_INSTALL_BUILD_DEPS  Linux-only dependency bootstrap flag (default: $WEBRTC_INSTALL_BUILD_DEPS)
  WEBRTC_GCLIENT_JOBS        gclient parallelism (default: $WEBRTC_GCLIENT_JOBS)

Examples:
  ./scripts/build_libwebrtc_source.sh --target linux_amd64 --install-dir /tmp/libwebrtc
  ./scripts/build_libwebrtc_source.sh --target linux_386 --install-dir /tmp/libwebrtc_x86
  WEBRTC_INSTALL_BUILD_DEPS=1 ./scripts/build_libwebrtc_source.sh --target linux_arm64
EOF
    exit 0
}

target_os_for() {
    case "$1" in
        darwin_*) echo "mac" ;;
        linux_*) echo "linux" ;;
        *) return 1 ;;
    esac
}

out_dir_for() {
    case "$1" in
        darwin_arm64) echo "out/libgowebrtc-darwin-arm64" ;;
        darwin_amd64) echo "out/libgowebrtc-darwin-amd64" ;;
        linux_386)    echo "out/libgowebrtc-linux-x86" ;;
        linux_amd64)  echo "out/libgowebrtc-linux-amd64" ;;
        linux_arm64)  echo "out/libgowebrtc-linux-arm64" ;;
        linux_arm)    echo "out/libgowebrtc-linux-arm" ;;
        *) return 1 ;;
    esac
}

gn_args_for() {
    case "$1" in
        darwin_arm64)
            cat <<'EOF'
target_os="mac"
target_cpu="arm64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
EOF
            ;;
        darwin_amd64)
            cat <<'EOF'
target_os="mac"
target_cpu="x64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
use_rtti=true
treat_warnings_as_errors=false
EOF
            ;;
        linux_386)
            cat <<'EOF'
target_os="linux"
target_cpu="x86"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
is_clang=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
use_x11=true
ozone_platform_x11=true
EOF
            ;;
        linux_amd64)
            cat <<'EOF'
target_os="linux"
target_cpu="x64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
is_clang=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
use_x11=true
ozone_platform_x11=true
EOF
            ;;
        linux_arm64)
            cat <<'EOF'
target_os="linux"
target_cpu="arm64"
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
is_clang=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
use_x11=true
ozone_platform_x11=true
libyuv_use_neon=false
libyuv_use_sve=false
libyuv_use_sme=false
EOF
            ;;
        linux_arm)
            cat <<'EOF'
target_os="linux"
target_cpu="arm"
target_arm_version=7
arm_use_neon=true
is_debug=false
is_component_build=false
rtc_include_tests=false
rtc_build_examples=false
rtc_build_tools=false
is_clang=false
use_rtti=true
treat_warnings_as_errors=false
use_custom_libcxx=false
use_custom_libcxx_for_host=false
use_clang_modules=false
use_autogenerated_modules=false
use_sysroot=false
use_x11=true
ozone_platform_x11=true
EOF
            ;;
        *)
            return 1
            ;;
    esac
}

ensure_depot_tools() {
    if [[ -x "$DEPOT_TOOLS_DIR/fetch" && -x "$DEPOT_TOOLS_DIR/gclient" ]]; then
        return
    fi

    log_step "Installing depot_tools"
    mkdir -p "$(dirname "$DEPOT_TOOLS_DIR")"
    rm -rf "$DEPOT_TOOLS_DIR"
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git "$DEPOT_TOOLS_DIR"
}

bootstrap_depot_tools() {
    export DEPOT_TOOLS_DIR
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
    export DEPOT_TOOLS_METRICS=0

    if [[ -f "$DEPOT_TOOLS_DIR/python3_bin_reldir.txt" ]]; then
        return
    fi

    log_step "Bootstrapping depot_tools"
    "$DEPOT_TOOLS_DIR/ensure_bootstrap"
}

retry_command() {
    local attempts="$1"
    local delay_seconds="$2"
    shift 2

    local try=1
    while true; do
        if "$@"; then
            return 0
        fi

        if (( try >= attempts )); then
            return 1
        fi

        log_warn "Command failed (attempt $try/$attempts): $*"
        log_warn "Retrying in ${delay_seconds}s..."
        sleep "$delay_seconds"
        try=$((try + 1))
        delay_seconds=$((delay_seconds * 2))
    done
}

cleanup_broken_git_checkouts() {
    local checkout_root="$WEBRTC_CACHE_DIR/src"
    local -a git_dirs=()
    if [[ ! -d "$checkout_root" ]]; then
        return
    fi

    # Recover from interrupted fetch/sync runs that leave stale Git lock files
    # behind and poison future gclient sync attempts.
    while IFS= read -r lock_file; do
        rm -f "$lock_file"
    done < <(find "$checkout_root" -type f -path '*/.git/index.lock' 2>/dev/null)

    mapfile -t git_dirs < <(find "$checkout_root" -type d -name .git -prune 2>/dev/null)
    for git_dir in "${git_dirs[@]}"; do
        local repo_dir
        [[ -d "$git_dir" ]] || continue
        repo_dir="$(dirname "$git_dir")"
        if [[ "$repo_dir" == "$checkout_root" ]]; then
            continue
        fi
        if git -C "$repo_dir" rev-parse --verify HEAD >/dev/null 2>&1; then
            continue
        fi
        log_warn "Removing incomplete dependency checkout: $repo_dir"
        rm -rf "$repo_dir"
    done
}

configure_webrtc_checkout() {
    local custom_deps_block
    local custom_vars_block
    custom_deps_block=$'    "custom_deps": {\n      "src/third_party/test_fonts/test_fonts": None,'
    if [[ "$TARGET_PLATFORM" == linux_* ]]; then
        custom_deps_block+=$'\n      "src/third_party/llvm-build/Release+Asserts": None,'
    fi
    custom_deps_block+=$'\n    },'
    if [[ "$TARGET_PLATFORM" == linux_* ]]; then
        custom_vars_block=$'    "custom_vars": {\n      "llvm_force_head_revision": True,\n    },'
    fi

    log_step "Configuring WebRTC checkout"
    cat > "$WEBRTC_CACHE_DIR/.gclient" <<EOF
solutions = [
  {
    "name": "src",
    "url": "${WEBRTC_SOURCE_URL}",
    "deps_file": "DEPS",
    "managed": False,
${custom_vars_block}
${custom_deps_block}
  },
]
EOF
}

clone_webrtc_checkout() {
    log_step "Cloning WebRTC source"
    retry_command 4 15 git clone --depth 1 "$WEBRTC_SOURCE_URL" "$WEBRTC_CACHE_DIR/src"
}

prepare_webrtc_download_dirs() {
    # gclient writes bookkeeping files next to the LLVM toolchain download
    # before extraction completes; pre-create the parent to avoid a fresh-cache
    # bootstrap failure on clean Linux containers.
    mkdir -p "$WEBRTC_CACHE_DIR/src/third_party/llvm-build/Release+Asserts"
}

gclient_sync_with_recovery() {
    local attempts=4
    local delay_seconds=30
    local try=1

    while true; do
        cleanup_broken_git_checkouts
        if gclient sync \
            --revision "src@$WEBRTC_GIT_REV" \
            --with_branch_heads \
            --shallow \
            --no-history \
            --nohooks \
            --jobs "$WEBRTC_GCLIENT_JOBS" \
            --reset \
            --force; then
            return 0
        fi

        if (( try >= attempts )); then
            return 1
        fi

        log_warn "gclient sync failed (attempt $try/$attempts)"
        log_warn "Retrying in ${delay_seconds}s..."
        sleep "$delay_seconds"
        try=$((try + 1))
        delay_seconds=$((delay_seconds * 2))
    done
}

sync_webrtc_checkout() {
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
    export GCLIENT_PY3=1
    export GCLIENT_SUPPRESS_GIT_VERSION_WARNING=1
    export DEPOT_TOOLS_METRICS=0
    export DEPOT_TOOLS_UPDATE=0

    mkdir -p "$WEBRTC_CACHE_DIR"
    cd "$WEBRTC_CACHE_DIR"

    if [[ -d "$WEBRTC_CACHE_DIR/src/.git" ]] && ! git -C "$WEBRTC_CACHE_DIR/src" rev-parse --verify HEAD >/dev/null 2>&1; then
        log_warn "Removing incomplete root WebRTC checkout: $WEBRTC_CACHE_DIR/src"
        rm -rf "$WEBRTC_CACHE_DIR/src"
    fi

    configure_webrtc_checkout

    if [[ ! -d "$WEBRTC_CACHE_DIR/src/.git" ]]; then
        clone_webrtc_checkout
    fi

    prepare_webrtc_download_dirs

    log_step "Syncing WebRTC source"
    cd "$WEBRTC_CACHE_DIR/src"
    retry_command 4 15 git fetch "$WEBRTC_SOURCE_URL" "$WEBRTC_GIT_REV" --depth 1
    git checkout --detach "$WEBRTC_GIT_REV"

    cd "$WEBRTC_CACHE_DIR"
    gclient_sync_with_recovery
}

maybe_install_linux_build_deps() {
    local target_os
    target_os="$(target_os_for "$TARGET_PLATFORM")"
    if [[ "$target_os" != "linux" || "$WEBRTC_INSTALL_BUILD_DEPS" != "1" ]]; then
        return
    fi

    local install_script="$WEBRTC_CACHE_DIR/src/build/install-build-deps.sh"
    if [[ ! -x "$install_script" ]]; then
        log_error "Missing Linux dependency installer: $install_script"
        exit 1
    fi

    log_step "Installing WebRTC Linux build dependencies"
    "$install_script" --no-prompt --no-chromeos-fonts

    if ! command -v apt-get >/dev/null 2>&1; then
        log_warn "Skipping explicit Linux X11 build dependency install on this distro; ensure X11 capture dev packages are present manually"
        return
    fi

    local sudo_cmd=()
    if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
        if ! command -v sudo >/dev/null 2>&1; then
            log_error "Linux source builds need sudo or root to install explicit X11 capture build dependencies"
            exit 1
        fi
        sudo_cmd=(sudo)
    fi

    log_step "Installing explicit Linux X11 capture build dependencies"
    "${sudo_cmd[@]}" apt-get update
    "${sudo_cmd[@]}" apt-get install -y \
        libasound2-dev \
        libdrm-dev \
        libgbm-dev \
        libglib2.0-dev \
        libpulse-dev \
        libx11-dev \
        libxcomposite-dev \
        libxdamage-dev \
        libxext-dev \
        libxfixes-dev \
        libxrandr-dev \
        libxrender-dev \
        libxtst-dev

    if [[ "$TARGET_PLATFORM" != "linux_386" ]]; then
        return
    fi

    log_step "Installing Linux x86 multilib build dependencies"
    local gxx_major libstdcxx_dev_pkg
    gxx_major="$(g++ -dumpversion | cut -d. -f1)"
    libstdcxx_dev_pkg="libstdc++-${gxx_major}-dev:i386"
    "${sudo_cmd[@]}" dpkg --add-architecture i386
    "${sudo_cmd[@]}" apt-get install -y \
        gcc-multilib \
        g++-multilib \
        libc6-dev-i386 \
        lib32gcc-s1 \
        lib32stdc++6 \
        "$libstdcxx_dev_pkg" \
        libasound2-dev:i386 \
        libdrm-dev:i386 \
        libgbm-dev:i386 \
        libglib2.0-dev:i386 \
        libpulse-dev:i386 \
        libx11-dev:i386 \
        libxcomposite-dev:i386 \
        libxdamage-dev:i386 \
        libxext-dev:i386 \
        libxfixes-dev:i386 \
        libxrandr-dev:i386 \
        libxrender-dev:i386 \
        libxtst-dev:i386
}

build_webrtc() {
    export PATH="$DEPOT_TOOLS_DIR:$PATH"

    local out_dir gn_args
    local -a ninja_targets=(
        "webrtc"
        "api/video_codecs:builtin_video_decoder_factory"
        "api/video_codecs:builtin_video_encoder_factory"
        "media:rtc_internal_video_codecs"
    )
    out_dir="$(out_dir_for "$TARGET_PLATFORM")"
    gn_args="$(gn_args_for "$TARGET_PLATFORM")"

    log_step "Generating GN files"
    cd "$WEBRTC_CACHE_DIR/src"
    gn gen "$out_dir" --args="$gn_args"

    log_step "Building libwebrtc"
    ninja -C "$out_dir" "${ninja_targets[@]}"
}

create_combined_linux_archive() {
    local output_archive="$1"
    local primary_archive="$2"
    local obj_dir="$3"
    local build_root checkout_root staging_dir archive index
    local -a archives=()

    build_root="$(dirname "$obj_dir")"
    checkout_root="$(dirname "$(dirname "$build_root")")"
    staging_dir="$(mktemp -d)"

    log_step "Combining Linux WebRTC archives"

    mapfile -t archives < <(
        {
            printf '%s\n' "$primary_archive"
            find "$obj_dir" -type f -name '*.a' | sort
        } | awk '!seen[$0]++'
    )

    index=0
    for archive in "${archives[@]}"; do
        local archive_stage member_dir member_index is_thin_archive
        archive_stage="$staging_dir/archive_$index"
        member_dir="$archive_stage/members"
        mkdir -p "$member_dir"
        member_index=0
        is_thin_archive=0

        if file -b "$archive" | grep -Fq "thin archive"; then
            is_thin_archive=1
        fi

        while IFS= read -r member_path; do
            local archive_dir source_path dest_path
            archive_dir="$(cd "$(dirname "$archive")" && pwd)"

            if [[ -z "$member_path" ]]; then
                continue
            fi

            dest_path="$member_dir/$(printf '%06d' "$member_index")_$(basename "$member_path")"

            if (( is_thin_archive )); then
                if [[ "$member_path" == /* && -f "$member_path" ]]; then
                    source_path="$member_path"
                elif [[ -f "$checkout_root/$member_path" ]]; then
                    source_path="$checkout_root/$member_path"
                elif [[ -f "$build_root/$member_path" ]]; then
                    source_path="$build_root/$member_path"
                elif [[ -f "$obj_dir/$member_path" ]]; then
                    source_path="$obj_dir/$member_path"
                elif [[ -f "$archive_dir/$member_path" ]]; then
                    source_path="$archive_dir/$member_path"
                else
                    log_error "Unable to resolve thin archive member $member_path from $archive"
                    return 1
                fi

                cp "$source_path" "$dest_path"
            else
                ar p "$archive" "$member_path" > "$dest_path"
            fi

            member_index=$((member_index + 1))
        done < <(ar t "$archive")

        index=$((index + 1))
    done

    rm -f "$output_archive"
    local -a object_batch=()
    local object_file
    while IFS= read -r -d '' object_file; do
        object_batch+=("$object_file")
        if (( ${#object_batch[@]} >= 200 )); then
            ar qc "$output_archive" "${object_batch[@]}"
            object_batch=()
        fi
    done < <(find "$staging_dir" -type f -name '*.o' -print0 | sort -z)

    if (( ${#object_batch[@]} > 0 )); then
        ar qc "$output_archive" "${object_batch[@]}"
    fi

    ranlib "$output_archive"
    rm -rf "$staging_dir"
}

materialize_linux_archive() {
    local source_archive="$1"
    local output_archive="$2"
    local obj_dir="$3"
    local build_root checkout_root archive_dir staging_dir member_path source_path dest_path
    local member_index=0
    local -a object_batch=()

    if ! file -b "$source_archive" | grep -Fq "thin archive"; then
        cp "$source_archive" "$output_archive"
        return 0
    fi

    build_root="$(dirname "$obj_dir")"
    checkout_root="$(dirname "$(dirname "$build_root")")"
    archive_dir="$(cd "$(dirname "$source_archive")" && pwd)"
    staging_dir="$(mktemp -d)"

    while IFS= read -r member_path; do
        if [[ -z "$member_path" ]]; then
            continue
        fi

        if [[ "$member_path" == /* && -f "$member_path" ]]; then
            source_path="$member_path"
        elif [[ -f "$checkout_root/$member_path" ]]; then
            source_path="$checkout_root/$member_path"
        elif [[ -f "$build_root/$member_path" ]]; then
            source_path="$build_root/$member_path"
        elif [[ -f "$obj_dir/$member_path" ]]; then
            source_path="$obj_dir/$member_path"
        elif [[ -f "$archive_dir/$member_path" ]]; then
            source_path="$archive_dir/$member_path"
        else
            log_error "Unable to resolve thin archive member $member_path from $source_archive"
            return 1
        fi

        dest_path="$staging_dir/$(printf '%06d' "$member_index")_$(basename "$member_path")"
        cp "$source_path" "$dest_path"
        member_index=$((member_index + 1))
    done < <(ar t "$source_archive")

    rm -f "$output_archive"
    while IFS= read -r -d '' dest_path; do
        object_batch+=("$dest_path")
        if (( ${#object_batch[@]} >= 200 )); then
            ar qc "$output_archive" "${object_batch[@]}"
            object_batch=()
        fi
    done < <(find "$staging_dir" -type f -name '*.o' -print0 | sort -z)

    if (( ${#object_batch[@]} > 0 )); then
        ar qc "$output_archive" "${object_batch[@]}"
    fi

    ranlib "$output_archive"
    rm -rf "$staging_dir"
}

verify_linux_archive_symbol() {
    local archive="$1"
    local symbol="$2"
    local search_dir="${3:-}"
    if bash -lc "set +o pipefail; nm -A \"$archive\" 2>/dev/null | grep -Fq \"$symbol\""; then
        return 0
    fi

    if [[ -n "$search_dir" ]]; then
        local matches=()
        local path
        while IFS= read -r -d '' path; do
            if bash -lc "set +o pipefail; nm -A \"$path\" 2>/dev/null | grep -Fq \"$symbol\""; then
                matches+=("$path")
            fi
        done < <(find "$search_dir" -type f \( -name '*.a' -o -name '*.o' \) -print0)

        if (( ${#matches[@]} > 0 )); then
            log_warn "Symbol $symbol exists in source-built outputs:"
            printf '%s\n' "${matches[@]}"
        else
            log_warn "Symbol $symbol was not found in any output under $search_dir"
        fi
    fi

    log_error "Installed Linux archive is missing required symbol: $symbol"
    return 1
}

install_webrtc() {
    local out_dir archive obj_dir
    out_dir="$(out_dir_for "$TARGET_PLATFORM")"
    archive="$WEBRTC_CACHE_DIR/src/$out_dir/obj/libwebrtc.a"
    obj_dir="$WEBRTC_CACHE_DIR/src/$out_dir/obj"

    if [[ ! -f "$archive" ]]; then
        log_error "Built archive not found: $archive"
        exit 1
    fi

    log_step "Installing libwebrtc"
    mkdir -p "$INSTALL_DIR/include" "$INSTALL_DIR/lib"
    if [[ "$TARGET_PLATFORM" == linux_* ]]; then
        local encoder_factory_archive decoder_factory_archive internal_codecs_archive simulcast_encoder_archive
        local software_fallback_wrappers_archive
        encoder_factory_archive="$obj_dir/api/video_codecs/libbuiltin_video_encoder_factory.a"
        decoder_factory_archive="$obj_dir/api/video_codecs/libbuiltin_video_decoder_factory.a"
        internal_codecs_archive="$obj_dir/media/librtc_internal_video_codecs.a"
        simulcast_encoder_archive="$obj_dir/media/librtc_simulcast_encoder_adapter.a"
        software_fallback_wrappers_archive="$obj_dir/api/video_codecs/librtc_software_fallback_wrappers.a"

        materialize_linux_archive "$archive" "$INSTALL_DIR/lib/libwebrtc.a" "$obj_dir"
        materialize_linux_archive "$encoder_factory_archive" "$INSTALL_DIR/lib/libbuiltin_video_encoder_factory.a" "$obj_dir"
        materialize_linux_archive "$decoder_factory_archive" "$INSTALL_DIR/lib/libbuiltin_video_decoder_factory.a" "$obj_dir"
        materialize_linux_archive "$internal_codecs_archive" "$INSTALL_DIR/lib/librtc_internal_video_codecs.a" "$obj_dir"
        materialize_linux_archive "$simulcast_encoder_archive" "$INSTALL_DIR/lib/librtc_simulcast_encoder_adapter.a" "$obj_dir"
        materialize_linux_archive "$software_fallback_wrappers_archive" "$INSTALL_DIR/lib/librtc_software_fallback_wrappers.a" "$obj_dir"

        verify_linux_archive_symbol "$INSTALL_DIR/lib/libbuiltin_video_encoder_factory.a" "CreateBuiltinVideoEncoderFactory" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/libbuiltin_video_decoder_factory.a" "CreateBuiltinVideoDecoderFactory" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/librtc_internal_video_codecs.a" "InternalEncoderFactory" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/librtc_internal_video_codecs.a" "InternalDecoderFactory" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/librtc_simulcast_encoder_adapter.a" "SimulcastEncoderAdapter" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/librtc_software_fallback_wrappers.a" "CreateVideoEncoderSoftwareFallbackWrapper" "$obj_dir" || exit 1
        verify_linux_archive_symbol "$INSTALL_DIR/lib/librtc_software_fallback_wrappers.a" "CreateVideoDecoderSoftwareFallbackWrapper" "$obj_dir" || exit 1
    else
        cp "$archive" "$INSTALL_DIR/lib/libwebrtc.a"
    fi

    rsync -a --delete --prune-empty-dirs \
        --include='*/' \
        --include='*.h' \
        --include='*.hpp' \
        --include='*.inc' \
        --exclude='*' \
        "$WEBRTC_CACHE_DIR/src/" "$INSTALL_DIR/include/"

    printf '%s\n' "$WEBRTC_GIT_REV" > "$INSTALL_DIR/VERSION"
    printf 'branch-heads/%s\n' "$WEBRTC_BRANCH_HEAD" > "$INSTALL_DIR/WEBRTC_BRANCH"
    printf 'source-build\n' > "$INSTALL_DIR/.libgowebrtc-source-build"

    log_success "Installed source-built libwebrtc to $INSTALL_DIR"
}

main() {
    if [[ -z "$TARGET_PLATFORM" ]]; then
        TARGET_PLATFORM="$(detect_platform)"
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --target)
                TARGET_PLATFORM="$2"
                shift 2
                ;;
            --install-dir)
                INSTALL_DIR="$2"
                shift 2
                ;;
            --install-build-deps)
                WEBRTC_INSTALL_BUILD_DEPS=1
                shift
                ;;
            --help)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    case "$TARGET_PLATFORM" in
        darwin_arm64|darwin_amd64|linux_386|linux_amd64|linux_arm64|linux_arm) ;;
        *)
            log_error "Unsupported target platform: $TARGET_PLATFORM"
            exit 1
            ;;
    esac

    log_info "Target platform: $TARGET_PLATFORM"
    log_info "Pinned WebRTC revision: $WEBRTC_GIT_REV"
    log_info "Branch head: $WEBRTC_BRANCH_HEAD"
    log_info "Cache dir: $WEBRTC_CACHE_DIR"
    log_info "Install dir: $INSTALL_DIR"

    ensure_depot_tools
    bootstrap_depot_tools
    sync_webrtc_checkout
    maybe_install_linux_build_deps
    build_webrtc
    install_webrtc
}

main "$@"
